### ISSUE TITLE
Image uploading gets stuck from web client.

### ISSUE THREAD

**Issue by jyasskin** [hachyderm/community#1]
I'm trying to attach an image to a post, using the web client installed as a PWA in Chrome on Android, and it results in the "Uploading" progress bar getting stuck at 100%.

![Stuck Uploading progress bar at 100%](https://user-images.githubusercontent.com/83420/200203885-755619d2-b0ed-435c-88ff-722fbf88b275.png)

I can gather more debugging data in a couple hours.

**Comment by bertjwregeer** [comment]
@jyasskin there's a process that validates it is an image + strips exif + creates smaller versions, that may take a bit depending on the load on the servers. My last upload of an image took about ~2 minutes. Might need to be a little more patient in the mean time.

**Comment by jyasskin** [comment]
Yep, it's much faster now. It might help to route that current wait time back to the UI somehow, but that's probably a feature request for the main codebase rather than here. Thanks for the answer!
