### ISSUE TITLE
Emoji request - JuliaLang

### ISSUE THREAD

**Issue by miguelraz** [hachyderm/community#101]
Hey all 👋🏾 

I'm really liking this instance so far. Thanks a lot!
Seeing as how other programming languages have emoji support, I'd like to ask for the JuliaLang logo to also be added. It's fair use and you can find it here

https://en.wikipedia.org/wiki/Julia_(programming_language)#/media/File:Julia_Programming_Language_Logo.svg

or for emoji size here

![julialang](https://user-images.githubusercontent.com/13056181/204072330-25ba42c6-3206-4aa6-af47-5bd637da1a6a.png)

(this one is my favorite version, and most Julia people would recognize it at that pixel size)
![julia](https://user-images.githubusercontent.com/13056181/204072373-85468fb3-f149-4b07-94e5-9891c88ca28e.png)

Thanks!

**Comment by quintessence** [comment]
Got it! I did the lower one as it resolves better at 128px :)

**Comment by miguelraz** [comment]
I super, duper appreciate all the work people are doing here - but I have the *smallest* nitpick ever - would it be possible to rename the emoji to `:julia:`? I believe that would help being consistent with other servers, see

https://fosstodon.org/@mbauman/109427700685235646

**Comment by quintessence** [comment]
No worries about the request! The reason we went with JuliaLang is so that when a screenreader reads it, it makes sense rather than appearing as the name Julia :)
