### ISSUE TITLE
Various 502/504 errors

### ISSUE THREAD

**Issue by sindarina** [hachyderm/community#102]
I am seeing errors loading various parts of Hachyderm right now. It's not completely offline, as it sometimes goes through, but there's clearly some sort of issue that's preventing the normal, smooth operation.

Just marking it here as a record, in case anyone else is wondering.

**Comment by Saruya** [comment]
Same, completely dead for me, despite the status page thinking everything's operational.

**Comment by sparky005** [comment]
Same here, site seems to be totally down for me

**Comment by sparky005** [comment]
Seems to be back now!

**Comment by chicocvenancio** [comment]
[Grafana](https://grafana.hachyderm.io/public-dashboards/bc9e340202c1495888d8fd849112a813?orgId=0&refresh=1m) doesn't look good, high latency, lots of errors.<img width="1721" alt="image" src="https://user-images.githubusercontent.com/188585/204090327-3f7e8645-667a-436a-99d9-cf209f5afe6a.png">

**Comment by sindarina** [comment]
Yeah, looks like we're back, seems to load fine now, I suddenly have a bunch of notifications from hours ago, etc.

**Comment by sparky005** [comment]
I think there's still some issues. I'm periodically unable to refresh my feed or load notifications. Seems to come and go

**Comment by sindarina** [comment]
Yeah, I just checked, and can't load my home timeline via the web interface, right now.

**Comment by sindarina** [comment]
Now seeing the 504s pop up in the Grafana dashboard, too.

**Comment by chicocvenancio** [comment]
Yep. I'm getting a sad mastadon in 
![Screenshot_20221126-112136_Tusky](https://user-images.githubusercontent.com/188585/204093589-3ff47fb1-5486-4b1c-ad51-2b06c3fe27cc.jpg)
tusky as well.

**Comment by lambda** [comment]
Also having issues despite the status page saying everything is working.

![Screenshot_20221126-103051](https://user-images.githubusercontent.com/37398/204096692-09b40934-cd3b-434a-9908-6918ac8104d7.png)
![Screenshot_20221126-103026](https://user-images.githubusercontent.com/37398/204096696-97685121-f2cf-4db9-b80b-40f4222d1adf.png)

**Comment by logan-life** [comment]
Still down for me as well.

**Comment by chicocvenancio** [comment]
Is there a process for notifying admins beyond this issue?

**Comment by mgrider** [comment]
I was seeing the error screen when trying to load `https://hachyderm.io/settings/preferences/appearance`, but then tried removing `/appearance`, and that loaded near instantly... Got another error when trying to import a follower `.csv`. Something is clearly still a little wonky.

**Comment by lambda** [comment]
Back for me, and looks like the latency and error rates are dropping off in Grafana as well. There seem to have been a couple of major periods of high latency and error rates today.

**Comment by dmah42** [comment]
these should be resolved.  tl;dr: some postgres/pgbouncer configuration needed some tuning.

**Comment by chicocvenancio** [comment]
Thanks for looking into it @dmah42 ! Things are much more stable, but I'm getting 504s trying to send images, is a different issue?

**Comment by lambda** [comment]
I'm seeing more errors and very slow requests again, and a glance at Grafana we see another spike in both.

**Comment by dmah42** [comment]
I think I closed this a hair early.  we are having some rumbling issues still. @taniwha3 can maybe add more flavour.

**Comment by sindarina** [comment]
Yeah, I just got another 504. HugOps to the people debugging the problem 🙂

**Comment by sindarina** [comment]
@sparky005 While we waitl; I just looove your profile picture 😄

**Comment by sparky005** [comment]
Ah hahah thank you @sindarina. That is Monica and I love her :)

**Comment by ollien** [comment]
Looks like this is continuing. I'm noticing on Grafana that response times are taking ~a minute. After it does eventually load, I get a 504. Status page says things are A-ok

**Comment by dmah42** [comment]
it came back. infra team are on it

**Comment by marc703** [comment]
I'm assuming that it is a variation on this issue, but it appears that using MetaText client, I'm getting an error sand timeout but upon reposting it seems to party twice.

**Comment by marc703** [comment]
> I'm assuming that it is a variation on this issue, but it appears that using MetaText client, I'm getting an error and timeout but upon reposting it seems to post twice.

It also seems to take a long time ~1 min to post from the web UI as well.

**Comment by quintessence** [comment]
Going to go ahead and close this issue as it seems to have been resolved with the infra efforts today - please create a new issue if it re-appears and thank you :)
