### ISSUE TITLE
Emoji request: Neovim

### ISSUE THREAD

**Issue by ianbattersby** [hachyderm/community#104]
Whilst I appreciate that we could edge toward emoji bloat, I wondered if we could have one added for Neovim? It's far enough away from Vim to warrant its own logo I feel 🙏 

Official icons: https://neovim.io/logos/neovim-logos.zip

Neovim logo by Jason Long, [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/).

**Comment by quintessence** [comment]
Done :)
