### ISSUE TITLE
Support Near Anonymous Donations

### ISSUE THREAD

**Issue by bravok** [hachyderm/community#105]
As a hachyderm user, @apicultor@hachyderm.io would like to donate in a relatively anonymous way.

Challenge:

Currently Kofi-Paypal requires setting up an account/identifying yourself in a 3rd party system.

Enhancement:

Support additional donation channels that do not require the donor to declare themselves.

**Comment by alxndr42** [comment]
That would be ideal.

Personally, I would be happy for anything that doesn't require Paypal, like Patreon or Open Collective. (Please let me know if you don't want this added to your issue.)

**Comment by krisnova** [comment]
We are considering accepting anonymous funding. See #5 and https://community.hachyderm.io/blog/2022/12/04/growth-and-sustainability/#donations

Are there specific funding services you would advocate for and why?

**Comment by OneJaeAtATime** [comment]
https://opencollective.com is one that I like a lot. It transparently shows funding, but also makes it seem like less of a for-profit fundraising. My partner's instance he is on uses it for funding.

**Comment by quintessence** [comment]
GitHub Sponsors is now available and additional options coming soon :D 

https://github.com/sponsors/nivenly
