### ISSUE TITLE
Rules page is missing NSFW rule

### ISSUE THREAD

**Issue by alexbbrown** [hachyderm/community#107]
The rules here

https://hachyderm.io/about

![image](https://user-images.githubusercontent.com/2532344/204162116-781dcb71-6d17-4ee0-9854-8d39e7078c1a.png)

Are missing 3 categories of behaviour which are called out here:

https://github.com/hachyderm/community

Which are: 

> * Fundraising Accounts
> * Ad / Marketing Accounts
> This includes promos, discount codes, etc.
> * 18+ / NSFW Accounts

Some users confused by this omission when they are banned for NSFW.

suggestion:
Add to the end of the rules list on the about page

> **limit or avoid the use of**
> Fundraising Accounts
> Ad / Marketing Accounts
> This includes promos, discount codes, etc.
> 18+ / NSFW Accounts
>

**Comment by quintessence** [comment]
Yes! We're going to be updating the way the About page after we're done adding some additional documents to link to there. The short explanation is that NSFW content is fine on a one-off basis, we don't want to be spending all our mod time on content, but that we do limit certain account types that are not "generic user". In this case it's not that NSFW content itself is banned, just that we don't allow NSFW focused accounts.

**Comment by quintessence** [comment]
I have been working on the Account Types documentation and this is now reflected on our About page :)
