### ISSUE TITLE
503 Error when searching for remote post

### ISSUE THREAD

**Issue by KitKat31337** [hachyderm/community#108]
When searching for a remote post by its url I am getting a 503 error.

**Comment by quintessence** [comment]
Can you provide the URL? One explanation is the instance might not be one we federate with :)

**Comment by KitKat31337** [comment]
https://firekitten.social/@KittyFangs/109418931209084504

This is the post I was trying to pull up to boost with my hachyderm account.  It did eventually work, but was giving me 503 errors over like an hour of retrying.  My follow to the same account from my hachyderm account seemed very bugged out at the same time, saying I wasn't following, then it was pending (target account doesn't have approval turned on), and then finally it was saying I was following again (this is the time I could then pull up the link)

I run firekitten.social, and its sidekiq queues are mostly idle as it is a very small instance.  I think the timing was following some maintenance, so I think hachyderm was just trying to catch up on things.
