### ISSUE TITLE
Increased latency / timeouts (EU/DE)

### ISSUE THREAD

**Issue by ThisIsMissEm** [hachyderm/community#115]
Hi, hopefully this is the right place to post it, but I'm noticing an overall increase in latency in the EU, and getting timeouts when performing interactions. I am using metatext as a client, so this could be related to #114, but as the delay doesn't seem consistent, I don't think this is the case.

sometimes interactions are instantaneous, but majority of the time it's 30-90s to post on Hachyderm, often with timeouts.

I don't believe this to be related to my network, as I've tried various local things first & get similar results when switching to 5G (although both are the same provider)

**Comment by ThisIsMissEm** [comment]
I think this is related to which server the Person I'm responding to is on, as I noticed one reply went through (even though metatext failed to notice), and had linkification of the username mentioned, but the other didn't.

I'm not sure if Mastodon makes links to users in replies a client or server feature, but it seems this is where the latency is.

e.g., infosec.exchange is a particularly slow instance to reply to, but mastodon.online fairly fast.

Maybe this gives more to look into?

**Comment by ash1maa** [comment]
Just tried to log on from web and it seems to be down completely

**Comment by untitaker** [comment]
All requests time out for me, in EU.

**Comment by trawler** [comment]
I can confirm the same for me (EU/DE). Been using mastodon/toot/metatext and been experiencing timeouts when uploading media.
But social media can wait :) thanks for the awesome work!

**Comment by ThisIsMissEm** [comment]
I know media uploads have had issues, which seems to be a separate issue, as far as I can tell, as I've been seeing this on non-media posts that are replies

**Comment by helmingstay** [comment]
For folks tracking this, worth keeping an eye on instance status here:
https://status.hachyderm.io/
At the moment, we're seeing max response times above 1s. 
![hackyderm-status](https://user-images.githubusercontent.com/618613/204629521-b7a257f3-88c8-45c3-8660-0405a6895bd5.png)

**Comment by untitaker** [comment]
The status dashboard fails to capture a lot about the user experience, you'll find a few threads about that. GET is fairly fast on my end (probably a few seconds), but POST takes up to a minute.

**Comment by quintessence** [comment]
👋 Hachyderm Mod here

FYI we were / are continuing to recover from an outage, see comment on closed issue here:

https://github.com/hachyderm/community/issues/117#issuecomment-1330033935

TLDR:

There were some issues with images and posts queuing that should be clearing up (starting at around 12:00 / noon GMT and lasting several hours due to the volume of data involved).

We'll be able to expand on this more in a public facing announcement, I mostly wanted to confirm that 1 ) we saw this and 2 ) it is tied to another issue we worked on :)

**Comment by ThisIsMissEm** [comment]
@quintessence ah! Okay, thanks for the response! And thanks for all you & others are doing!
