### ISSUE TITLE
Home timelines are behind (sidekiq ingress queue latency?)

### ISSUE THREAD

**Issue by sparky005** [hachyderm/community#117]
I follow some of the same users on different accounts. On hachyderm, it looks like posts from other servers are not appearing in the home timeline or on users profiles for a couple hours, where they show up quickly on other servers. I guess this could just be the server catching up from when it was down, but just notifying just in case it's something more serious.

**Comment by sparky005** [comment]
I don't really know what sidekiq is but I'm guessing that's the issue lol. Hopefully it catches up! 
![2C848726-4FD1-4D19-A72D-5641F7E77D82](https://user-images.githubusercontent.com/5643040/204413877-8129966f-93a3-4928-b12f-53076a0a0a10.jpeg)

**Comment by sparky005** [comment]
Hmm sadly these latencies appear to be getting worse :( 
![926FB637-5C6A-458E-A499-30DDBB5FE33F](https://user-images.githubusercontent.com/5643040/204417655-e685ffa3-e76b-464e-b0ea-fe3babd2e9be.jpeg)

**Comment by pudquick** [comment]
Agreed - mine seems to be running about 5 hours behind currently

**Comment by krisnova** [comment]
yes we are aware -- we are in the middle of recovering from the outage earlier and will post an announcement as soon as we are stable again -- thank you for reporting it here and being patient with us

**Comment by quintessence** [comment]
Following up on Nóva's post - most of these should be back down. We're going to be putting out public facing announcements later. Thank you again for posting here :) 

-- Hachyderm Mod

**Comment by sparky005** [comment]
Thanks @quintessence, but I think the issues with the ingress queue are still ongoing. My home timeline is still at least three hours behind for posts from other instances and doesn't really seem to be catching up. Should we expect the queue latencies to start going down now?

**Comment by superchromix** [comment]
This issue has been marked "closed", but the same issue is ongoing.  

My home timeline is more than 5 hours behind.  Posts more than 5 hours old from users followed on other instances are not showing on my timeline.

Web interface, located in Germany.  Thanks.
