### ISSUE TITLE
grafana is down (http 502)

### ISSUE THREAD

**Issue by ezracelli** [hachyderm/community#118]
https://grafana.hachyderm.io/public-dashboards/bc9e340202c1495888d8fd849112a813?orgId=0&refresh=30s

**Comment by quintessence** [comment]
Ah hrm. Grafana as a service isn't down but I think maybe the URL might've changed for some reason. Looking into it now - thank you for telling us!

**Comment by quintessence** [comment]
Ah the URL is changing due to other changes we made. We finishing the new public dashboard and I'll fix the links on our About page and Community docs once we're done. Thank you again!

**Comment by ezracelli** [comment]
ahh gotcha! thanks for the update @quintessence 😇

**Comment by quintessence** [comment]
You're welcome!
