### ISSUE TITLE
Temporarily close registrations?

### ISSUE THREAD

**Issue by gmorenz** [hachyderm/community#122]
With hachyderm's infrastructure temporarily over capacity, I think it would make sense to temporarily close new registrations. This would avoid people new to mastodon having a bumpy starting experience, and it would maybe very slightly reduce the load.

**Comment by quintessence** [comment]
👋  Moderator Here :) 

Thank you for your suggestion! It's actually not new users that are contributing to the current spike, as the bulk of our 3000% growth came immediately in the Twitter migration. The number of new users we received after that main surge has been pretty nominal (by comparison). That said, having that significant of an unplanned surge in such a short timeframe means that the initial infra design wasn't built for that, and is why we're migrating and being as transparent as we can about that while also doing the migration itself to more robust infrastructure for the usage and expected growth we're seeing.

Nóva has a post that outlines the specific numbers, but essentially pre-Twitter migration / as of the 1st of this month we had ~700 users. In the two weeks of the bulk of the Twitter migration that scaled to 27k, and now we're adjusting the infra to handle that size and (as mentioned) expected growth.

**Comment by sparky005** [comment]
Even so, wouldn't it be better to close registrations so that new users are not met with a subpar experience?

**Comment by dclements** [comment]
@sparky005 Right. It isn't so much the problems with the scaling as "what kind of experience can new registrants expect in their first 24 hours?"

I want them to have the best experience possible so that they stick around after that ^_^

**Comment by sindarina** [comment]
I feel it's a bit dishonest to pretend that the entirety of that 'main surge' happened overnight, and that there was no moment when you could have capped signups before this. When I joined, it was between 6-7K, IIRC, and I am reasonably sure that it was still below 20K by the time I opened #92.

And yes, at this point it's mainly about not making the problem worse, specifically for anyone who joins right now, and finds themselves essentially being unable to use their account within normal parameters. It's an acknowledgement that a pause is needed, because you cannot guarantee the basics at the moment. Don't drop new people into that.

**Comment by sindarina** [comment]
![Screenshot 2022-11-30 at 08 23 41](https://user-images.githubusercontent.com/6074566/204740201-59f52f69-1855-4491-be35-4dc8c0fe601c.png)

"they just showed up" when you had the option to cap signups is not an honest representation of what happened 😕

**Comment by untitaker** [comment]
@sindarina i fully agreed with your original issue at #92 but you really don't have to be an ass about it. i would also like to know why they're keeping signups open because it makes zero sense to me, but it is a holiday season after all and posting through it won't get them to act faster. they have heard you.

**Comment by sindarina** [comment]
> but you really don't have to be an ass about it.

@untitaker I'm not the one being an ass here, bub.

> it's _only_ been a week after you've first opened #92.

A week is a very long time, under the current circumstances. There were plenty of Mastodon instance admins in the past few weeks who got surprised by their sudden growth, closing signups has been a common refrain in terms of advice given, etc. The Hachyderm team could have capped it at 10K, 15K, 20K, and probably have prevented this from happening as soon as it did, bought themselves enough time to work on their longer-term strategy, move stuff around, etc. They didn't, and that was a deliberate choice on their part.

As for 'they heard me'; I have no reason to believe that they actually did when their response so far has been to close issues before they are resolved, delete mod responses that were criticized, and then lock down the issue to prevent any further discussion from happening. That is not a sign of a healthy community.

**Comment by mjfisher-bbllp** [comment]
Latest update to the readme here says that signups are now closed til after the ops team finishes scaling up the architecture. ❤️ Site seems to be orders of magnitude healthier now that they’ve got us moved mostly off of the old NFS backend storage.

**Comment by sindarina** [comment]
They don't seem to be actually closed, though. I can still walk through the signup workflow, agree to the rules, enter new account data, and so forth. Compare that to, say, the same signup flow on .lol, which looks like this;

![Screenshot 2022-12-01 at 15 01 34](https://user-images.githubusercontent.com/6074566/205072443-fe6d88e2-a29a-40f3-a136-9879a51fe559.png)

**Comment by wlonkly** [comment]
I'd go so far as to say it's no longer necessary. Things are _snappy_. 

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1545955/205180782-59c61654-6df0-41b3-b506-8a60bfb6866b.png">

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1545955/205180789-76a96702-7f47-4585-bf34-aa451cc6647f.png">

**Comment by untitaker** [comment]
Hachyderm is indeed up and very fast. I would strongly argue that a serious discussion about sustainability of hachyderm is necessary. @sindarina initially asked some good questions in #92. Now that we're through the weeds and the mod team has some breathing room, I'll reiterate and add to them:

* who is expected to pay for hachyderm?
* if hachyderm shuts down, how much notice do we get?
* what are the growth goals?

See also the _just opened_ #146.

See also, fosstodon's plans here: https://hub.fosstodon.org/longevity-and-fosstodon/ -- this is what I would want from hachyderm. I would not expect this sort of contingency plan from a 200-user instance, but hachyderm hosts a significant portion of the fediverse now, whether y'all asked for it or not.

I also want to say that discussions like #92 were extremely heated towards the end, during the downtime. I understand that locking was the right decision at the time. But I feel that the hachyderm team still owes us answers, regardless of _how_ the questions were asked.

**Comment by gmorenz** [comment]
To start with the potentially obvious, I speak with no authority here. I'm just a random user.

I think those are reasonable questions to ask @untitaker - but probably not *right now*. The site is just coming out of firefighting mode, and the people running the site are volunteers. They almost certainly need, and definitely deserve, some downtime before they start crafting policy documents. Rushing policies like the ones you're talking about isn't doing anyone any favours.

I also think that just as a matter of organizing discussion this issue is the wrong issue to be raising these concerns in. This issue was fundamentally a proposal for a short term measure during fire fighting to limit the damage, not about crafting policy. Which is also why I've closed it now that the immediate fire is out and the proposal is moot.

**Comment by helmingstay** [comment]
Another random user here. I believe the above discussion contains a lot of valuable information. I understand that @gmorenz closed this as OP.  I don't 100% agree with closing this now,  but I feel like the breadcrumb trail to #146 provides a critical linkage to future discussion.

In any case, here still seems like a reasonable place to remark on this thread, which feels as relevant now as it was 2 days ago. A few highlights:
* Some important discussion of time-scales here. I expect that some rest for the core crew is high priority now. I also agree that a week is a really long time in this context.
* I feel that @untitaker's last comment^^ does an excellent job summarizing key points raised by some (and presumably left unsaid by others), and offers an important point of comparison with "peer" instances along with helpful resources.
* In the last 24 hours, I feel like the team heard and responded to many of the concerns raised here. @quintessence & other mods have done a lot of outreach & organization here on github, and Nova's widely-distributed blog post provided detailed & transparent feedback about the technical side.
* A through-line that @sindarina has raised is the distinction between designing technical vs social solutions. As another random user, I trust and appreciate the core team's technical skills and commitment. I'm also acutely aware that social organization, including politics and governance, is hard.

I appreciate everyone's considered input here. Again, as a random user, I hope we can continue having this conversation as folks get some time to rest and recover.

**Comment by helmingstay** [comment]
A final note related to the above: the following resource below was suggested by Hachydermian @ kweerious as relevant to ongoing governance discussion. For folks interested in the above discussion may find this useful:

https://dougbelshaw.com/blog/2022/11/25/defederation-and-governance-processes/

**Comment by kynan** [comment]
Would it make sense to add a clearer message on why registrations are currently closed and if / when they might reopen?

Currently you get "Creating an account on <strong>hachyderm.io</strong> is currently not possible, but please keep in mind that you do not need an account specifically on <strong>hachyderm.io</strong> to use Mastodon." when trying to create a new account and it's not straightforward to find out what's going on.

**Comment by gmorenz** [comment]
@kynan - fwiw I believe that registrations are closed to mitigate [this attack](https://hackmd.io/rD9nsTz1QeuPT-erxqjY-A?view).
