### ISSUE TITLE
Support non paypal donations

### ISSUE THREAD

**Issue by piccolbo** [hachyderm/community#124]
I have no idea how difficult this is, but for me it was a blocker as I've deleted my paypal account after a recent change in their user agreement. My credit cards are quivering with desire to contribute to the greater glory of hachyderm, but are frustrated. Please help them ;) Maybe open a Patreon or equivalent? Thanks

**Comment by piccolbo** [comment]
My initial impression was wrong, one can pay without an account on paypal.

**Comment by piccolbo** [comment]
My second impression was wrong, the payment funnel ends with "pay and create account". The CCs broke down in plastic tears.

**Comment by maxfragg** [comment]
I second this request. An option to support this project with Patreon or similar would be very appreciated

**Comment by alxndr42** [comment]
Thirded, something like Patreon or Open Collective would be lovely, but anything not requiring Paypal would make me happy.

**Comment by alxndr42** [comment]
https://community.hachyderm.io/blog/2022/12/04/growth-and-sustainability/#donations
