### ISSUE TITLE
Please update status page as service is more or less completely down

### ISSUE THREAD

**Issue by madrobby** [hachyderm/community#125]
Right now hachyderm.io is essentially unusable (hours-long delays, can't post any attachments, normal text posts work like half of the time and are extremely slow)—and I often can't even load the web interface to see the in-app announcements. 

As that status page is separate from the web app/APIs, it would be great to update the status page with what's happening behind the scenes.

Also, I'd suggest to turn off signups right now (as suggested #122), not because of load but because the site does not work.

**Comment by helmingstay** [comment]
See also discussion in #92

**Comment by madrobby** [comment]
> [io](https://status.hachyderm.io)?

Yes

**Comment by alexbbrown** [comment]
There is better information on the status page but it takes a couple clicks.

![image](https://user-images.githubusercontent.com/2532344/204847633-87f248c6-ff36-4c06-bb38-8ecd0768d11b.png)

which takes you to the status for just the mastodon server

https://status.hachyderm.io/791626718

then scroll to the bottom where the log is

![image](https://user-images.githubusercontent.com/2532344/204847888-f28823f7-c9e8-4bf4-94d1-c2eeacaf03f9.png)

**Comment by benwis** [comment]
👋 Mod here
This page is 100% automated currently. Our infrastructure team is working on resolving current issues. Once they get some time, we have plants to rework our error and outage reporting to be more helpful.

Thanks for reporting this!

**Comment by madrobby** [comment]
There’s literally a manually entry on that page (for the maintenance). :) Anyway it seems mostly back to normal and wishing you good luck with it.

**Comment by wlonkly** [comment]
> literally a manually entry on that page (for the maintenance).

That's from Nov 21, the 4.0.2 upgrade.

**Comment by quintessence** [comment]
👋 Hello another mod here.

Some additional context: as we're moving to new production infrastructure, the way that our various monitoring tools are connected to the current-soon-to-be-past infrastructure is falling out of sync and is _also_ being migrated and updated. 

We have a new GitHub issue, #143 , that we created to be a top-level issue to the migration to help explain this and provide one place for us to answer questions  / respond to issues that are as a result of the migration.
