### ISSUE TITLE
Realtime automated user feedback during service interruptions 

### ISSUE THREAD

**Issue by helmingstay** [hachyderm/community#127]
This issue relates to several recent & more specific issues around service interruptions and server response times, including double-posts (#103  ), high latency (#115 ),  new user sign-ups (#92 , #122 ), and access to status page (#125). I've tried to incorporate some salient points from the discussion in those threads.

Background & current state: 
* status.hachyderm.io shows uptime and latency (for REST GET but not POST, #115 ). User experience is heavily impacted by POST latency, leading to double-posting and/or lost posts, further stressing the system.
* The lack of information during service interruptions leads to user confusion, resulting in lots of related issues being filed and presumably burning admin time.
* Announcements have been used during recent service interruptions to provide some feedback. As far as I can tell, system announcements lack timestamps, and past announcements are not readily available/
* There was some admin discussion about a separate status page in the discussion of #92 (which seems to have moved?).

One or more sources of automated realtime user feedback about ongoing or expected systems interruptions (or other system issues) would solve several issues:
* Orient new users who are uncertain about expected behavior
* Guide experienced users' use of the system - "oh, i'll come back when things slow down"
* Guide user behavior to reduce system stresses (repeatedly refreshing and/or posting)
* Free admins from putting out fires.

I'm not qualified to rank or judge potential solutions, but a status bot seems like one simple option that's platform-neutral. Also, multiple cross-listed sources of realtime information could also improve visibility and accessibility to system users.

**Comment by alexbbrown** [comment]
Mod notes new dashboard : https://github.com/hachyderm/community/issues/118#issuecomment-1331223363

**Comment by helmingstay** [comment]
Also relevant: #121, #128 , and #129

**Comment by sindarina** [comment]
Yeah, they need to post a new dashboard link, but so far they haven't yet, as far as I am aware. The official link, at the bottom of the README in this repository, still points to the old one, which no longer works.

Ideally #118 should not have been closed until the new link was available, and thus accessible to the rest of us.

**Comment by helmingstay** [comment]
@sindarina Re #118, agreed. It also seems to me like hunting for status information during times of stress is non-ideal. As in, when Grafana eventually gets fixed, that dashboard (or status.hachyderm.io) won't be immediately apparent to casual users.
 
Any idea if hachyderm.io system announcements propagate cleanly to all clients? This seems like another obvious path for automated *in-channel* status updates.

**Comment by sindarina** [comment]
I know that the Metatext client surfaced those, but so far I haven't found if Toot! does, or where. I basically use the web interface on my desktop to check if there are any announcements. Just posted a screenshot of the most recent one here; https://github.com/hachyderm/community/issues/129#issuecomment-1331750293

**Comment by benwis** [comment]
👋 Mod here
These are all good ideas. The current status.hachyderm.io page is very rough. As y'all have mentioned, it doesn't have POST latency. It also doesn't show the status of all the different servers that serve the different regions. Or queue times.  We do have some internal tools that we use to see and triage that, and some info that is visible on our public grafana dashboard(which is currently down). 

Currently the page is also fully automated, I'd like to see manual outage updates posted there. Once the current infrastructure upgrades are complete, we plan to update that page and try to put together a more cohesive plan for outage reporting.

I love the idea of automated user feedback, however I'm not sure how feasible that is without modifying Mastodon itself, which is something we're trying to avoid. Perhaps that is a good suggestion for the Mastodon developers?

Thanks for bearing with us while we make these changes.

**Comment by dmah42** [comment]
i think at this point we have:

* updated the public grafana and ensured it's hosted off the rest of the fleet (so it should remain _mostly_ unaffected by outages).
* routinely included date-time stamps in announcements
* automated alerting that posts to the hachyderm channel on the discord (which is public) that lets anyone know about issues at the same time as we find out

what we're missing is:

* a status bot on the instance (questionable usefulness if the instance is down :D )
* automated status updates on status.hachyderm.io (limitation of the site we're using)

i expect we are in a better place than we were when this issue was posted, but there's still more we can do.  leaving this open for someone to plan the next phase.

**Comment by quintessence** [comment]
Closing this one for now :)
