### ISSUE TITLE
502 errors refreshing feeds

### ISSUE THREAD

**Issue by alexbbrown** [hachyderm/community#128]
I'm using metatext client.  

Trying to refresh the feeds eg home and federated but it shows error 502

**Comment by helmingstay** [comment]
FYI, Hachyderm is currently down and/or struggling.
![Screenshot from 2022-11-30 01-56-29](https://user-images.githubusercontent.com/618613/204728669-df0b40d7-f9ac-46c5-b437-34750ff37858.png)

**Comment by marc703** [comment]
Still getting 502 and 504 error fairly frequently (one or two minutes between them)

**Comment by alexbbrown** [comment]
Still getting 50x errors almost always when posting, even when the post goes through fine

**Comment by janvanveldhuizen** [comment]
The website feels sluggish today. A lot of 50x errors...
