### ISSUE TITLE
hachyderm.io unreachable from EU

### ISSUE THREAD

**Issue by superchromix** [hachyderm/community#129]
As the title says, the server is not reachable from the EU at this time.

**Comment by helmingstay** [comment]
FYI, Hachyderm is currently down and/or struggling.
![Screenshot from 2022-11-30 01-56-29](https://user-images.githubusercontent.com/618613/204728669-df0b40d7-f9ac-46c5-b437-34750ff37858.png)

**Comment by superchromix** [comment]
I see, at least the status page is working.

**Comment by sindarina** [comment]
It seems to be back for me, at least for the moment. In case it goes down again, here's a screenshot of the most recent announcement;

![Screenshot 2022-11-30 at 08 30 18](https://user-images.githubusercontent.com/6074566/204734996-32ffcc1e-3615-4c8c-b2c7-a6984c3811f3.png)

**Comment by sindarina** [comment]
Nope, back down again, now getting the stock nginx 504 from the front-end node.

**Comment by superchromix** [comment]
Seems to be working at the moment.

**Comment by sindarina** [comment]
Yeah, it's still having issues, I am getting 504s when I try to load my own timeline again.
