### ISSUE TITLE
Remove link to defunct Discord server?

### ISSUE THREAD

**Issue by schrierc** [hachyderm/community#13]
I joined the "official Discord" when reading https://hachyderm.io/about/more. This Discord server appears to be abandoned and the replacement Discord server (Aurea runtime) doesn't seem related to Hachyderm. Should the link be removed?

**Comment by mauvehed** [comment]
I believe you’ve joined the correct discord, but did not see the steps mentioned to obtain access to the rest of the server (easily missed, given they are at the top of the same channel where the endless list of new-threads requesting access are posted).

_The mention of the Aurae having moved homes is actually unrelated to the Discord itself and is jus misleading._ 

If you scroll to the VERY top of #gateway-firewall-public you’ll see the list of steps required to gain access to the rest of the Discord:

> You have arrived to the Nivenly discord instance. Newcomers to the server arrive here by default. 
> 
> This is the only ⚠️ Public ⚠️ channel on the instance. 
> 
> This is the <#858148455393263646> channel where we allow people to request to join the Discord. If you already have access to other channels such as 💬-general on the server you may ignore this message. If you are new here and wondering how to access the rest of the instance please keep reading.
> 
> 🚪 The Nivenly Instance is currently closed to the unmoderated public. In other words you will need to communicate with someone before we let you in.
> 
> In order to access the rest of the instance, and other channels. Please read the rules, verify your email, and introduce yourself upon arrival by creating a thread in this space. We want to know who you are, so we also suggest linking your Discord to any other social media you have.
> 
> Just say hello and offer a small sentence on why you are here. That will let our moderators know that you are interested in joining. After creating a thread our moderators will be with you as soon as we can. Share as much or as little as you like, in general the more the better. But nothing longer than a paragraph is needed.
> 
> This is your **first and final warning ** to take our rules seriously. 

So I think the feedback here for @krisnova or the Discord team is that with the threads requesting access to the main discord in the same channel as the explanation of the steps required, it’s very easy to not scroll up and miss it entirely (I almost did myself).

**Comment by quintessence** [comment]
Apologies just seeing this - Mauvhead is correct, the Discord is not defunct there is just a gateway so we can moderate the Discord more effectively. The steps that are copied in above are the correct steps for joining the Nivenly Discord.
