### ISSUE TITLE
Notifications are dropped on the floor

### ISSUE THREAD

**Issue by untitaker** [hachyderm/community#130]
Any replies to my posts from both remote and local accounts are not visible in the Notifications tab. They are visible in the thread view and on the author's profile, however.

The posts affected were follower-only but I am not sure that is required to repro the issue.

**Comment by benwis** [comment]
👋 Mod here
Hi! We've been experiencing various issues with our infrastructure in the last few days, and have made numerous improvements to address them. Everything is a bit more stable now, is this still a problem you're experiencing?

**Comment by untitaker** [comment]
I just tested from another account on treehouse.systems to ping myself 5 minutes ago, and it's still broken. That said I have received at least one notification since then.

My impression is that some requests are timing out all the same and it affects inter-server communications. The web UI does load fine for me (from EU), but that might be just because I'm hitting varnish.

**Comment by untitaker** [comment]
Federation into the other direction works fine. So I am actually able to post on hachyderm and the mention arrives at treehouse the _instant the POST request returns_.

**Comment by benwis** [comment]
Ah OK,
That seems to just be a general symptom of some of our ongoing service issues. We have another period of upgrades tonight, could you let us know tomorrow if you're still experiencing this?

**Comment by untitaker** [comment]
sure!

**Comment by untitaker** [comment]
i think this is fixed. another issue relating to notifications is that the unread counter never clears, but I think that might be temporary
