### ISSUE TITLE
Grafana public dashboard link in Community readme.md is still stale

### ISSUE THREAD

**Issue by mjfisher-bbllp** [hachyderm/community#131]
The link to the public Grafana dashboard in the Community readme.md is still stale; it directs to a “public dashboard not found” message.  Please update…thanks!

**Comment by benwis** [comment]
👋 Mod here
With our recent changes in architecture, we have moved the dashboard to a new URL, and need to hook it up with all the data again. Once it's ready, I'll be happy to post it here and update the Readme.  Thanks for reporting this!

**Comment by mjfisher-bbllp** [comment]
🙌
