### ISSUE TITLE
Not reciving verification email

### ISSUE THREAD

**Issue by rssnyder** [hachyderm/community#133]
I initially signed up using a protonmail.ch address, and later tried a gmail.com address, neither receiving the verification email. Yes I checked the spam folders.

**Comment by alxndr42** [comment]
Same, on two different email accounts, outgoing email is probably affected by the current load situation.

**Comment by tmas** [comment]
I'm having the same issue - the email in question is a G Suite account if that helps at all.

It looks like Hachyderm is set up to use Mailgun, so it's probably not an email deliverability issue. Assuming the Mailgun is still in good standing, maybe there's a backed up queue responsible for sending verification emails?

**Comment by ahanselka** [comment]
I'm having the same issue in getting an email. However, when I signed up for an account in the first place I got a 500 error of some sort. I thought the registration had failed, but when I tried to sign up again, it said my details were already taken. So perhaps it is just a queue of emails 🤷

**Comment by benwis** [comment]
👋 Mod here
Thanks for bringing this to our attention. It appears we may have an issue with outgoing email. I don't think it's related to the email addresses each of you provided.  I will update this thread once the issue has been resolved, and if it requires any more action on your part.

**Comment by rssnyder** [comment]
I got all the pending emails, and just re-requested and got it right away. Thanks @benwis

**Comment by benwis** [comment]
Thanks again! We think emails should be normal again. Please reopen if that's not the case
