### ISSUE TITLE
Unable to claim username

### ISSUE THREAD

**Issue by heyvito** [hachyderm/community#135]
Hi there, folks!
I was trying to signup as `@vito`, but although the user does not exist on that instance, I'm unable to claim it. 🤔 

Can anyone help me claiming it?

Thanks! ❤️

**Comment by quintessence** [comment]
👋 Mod here

It looks like a user previously registered the name, so while there's not an active account with the name, the name stays "reserved". The slightly longer explanation has to do with how accounts federate and why they can't be "undeleted" - another user can't claim a previously used username any more than the original user. ❤️

**Comment by heyvito** [comment]
Hi @quintessence! Thank you so much for explaining! It makes complete sense!

Best wishes! 💛
