### ISSUE TITLE
Unable to upload images (500 error code)

### ISSUE THREAD

**Issue by dclements** [hachyderm/community#137]
I was attempting to upload an image (a screenshot from the ActivityPub spec) and I keep getting 500 errors. Rest of the service seems to be behaving properly (it's slow but working) but it is entirely consistent on image uploads.

Sequence:

1. Write some text in a message.
2. Hit the "upload" button.
3. Select file. 

System then spins for a few seconds and returns a 500. In the web interface this is in a little popover that is blink-and-you-miss-it fast. In metatext it is front and center in the screen. 

Tests:

1. Attempted to use the web client (instead of Metatext) and got the same result. 
2. Attempted to upload several different images of different types, sizes etc.
3. Waited five minutes and tried again. 

None of these changed the outcome.

**Comment by quintessence** [comment]
Thank you for opening this! I believe we have fixed it - can you confirm?

**Comment by krisnova** [comment]
I suspect we continue to see flakey uploads like this for the next few days. There is a longer and more formal explanation [here in hackmd](https://hackmd.io/5Cv4SZmBS82mNyMiWuQ7Kg). 

Basically our database is very slow right now, and there isn't much we can do about it until the team gets online tomorrow. Thank you for reporting the issue. I hope others find this space and also realize we are working on it!
