### ISSUE TITLE
Add sidekiq queues to status page

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#138]
I think adding the sidekiq queues status to the hachyderm status page would help pretty much to better understand what the current status is.

**Comment by dmah42** [comment]
i'm hoping to bring back the public grafana page that has that on it.. i hope that would suffice?

**Comment by blueturtleai** [comment]
Tbh, I don’t know what grafana is, but I just wait and see 😀. Will it also include the sidekiq queue status?

**Comment by dmah42** [comment]
yes

**Comment by blueturtleai** [comment]
That’s great!

**Comment by dmah42** [comment]
https://grafana.hachyderm.io/public :)

**Comment by blueturtleai** [comment]
Great, thanks!
