### ISSUE TITLE
Gentle request: IPv6 connectivity

### ISSUE THREAD

**Issue by squeed** [hachyderm/community#14]
First of all: thanks for running this! It's been fun to see it take off.

It would be nice to have ipv6 connectivity. For me, personally, my ISPs CGN is utter trash, and ipv4 can be an order-of-magnitude slower to initiate connections. And this is with a 1gbit cable modem about 30 meters from the CMTS.

Let me know there's any way I can help.

**Comment by krisnova** [comment]
So we need to identify an EU centric hosting option that meets the following criteria:

 - Not a large tech giant
 - Reliable
 - Works well with US credit cards/customers
 - Affordable 
 - IPv6 addresses 

Ideally it would be something in Iceland that allows us to put our own hardware in the rack. 

Open for suggestions. Right now the ISP in seattle only offers IPv4

**Comment by squeed** [comment]
One option is Hetzner. They’re a German-based provider with a reputation for low prices, cheap bandwidth, and decent reliability. And they’ll take your dollars just fine.

I’ve never used them, but the admin of canhazip.com talked on a podcast about how Hetzner was the only way he could afford to run the service.

**Comment by SuperQ** [comment]
If you're looking for a colo on the west coast, [IO Cooperative](https://iocoop.org/) supports IPv6. We have rack space and VPS service in the SF Bay Area.

**Comment by BlueHatbRit** [comment]
> One option is Hetzner. They’re a German-based provider with a reputation for low prices, cheap bandwidth, and decent reliability. And they’ll take your dollars just fine.
>
> I’ve never used them, but the admin of canhazip.com talked on a podcast about how Hetzner was the only way he could afford to run the service.

I've been using Hetzner for a couple years now and it's rock solid in my experience. The Server Auction gives a good chance to pickup some good hardware at a very good price and I've never had any issues with downtime from them. They provide an IPv4 at a small additional cost and an IPv6 range, a /64 by default I believe. Along with some other things I'm hosting a mastodon instance with full IPv6 support so it is definetely possible to do.

They have locations in Germany and Finland with colo options in those locations as well. Here are a couple of links should anyone want to explore them in more detail.

Dedicated server auction (hardware originally specced for other customers now offered for a lower price for re-use) - https://www.hetzner.com/sb
Colocation plans - https://www.hetzner.com/colocation
Storage box's which are a good option for backup storage should you want to consider them for it as w ell - https://www.hetzner.com/storage/storage-box

**Comment by jfieber** [comment]
@krisnova CenturyLink in Seattle—and I'm making ISP assumptions based on whois—does offer v6 with the big caveat that it is 6rd. So a tunnel inside the pppoe tunnel, shrinking the MTU to the bare minimum for v6 to work at all. With CL, your v6 prefix embeds your assigned v4 so if you don't pay for a static v4, welcome to periodic network renumbering mayhem! But if you pay for a static v4, your v6 prefix should become static with it, and a /56 is quite a lot of address space for a basement rack.

**Comment by squeed** [comment]
It seems like IPv6 connectivity is rolled out. That was fast! I suspect this can be closed.

Y'all are the best.

**Comment by dmah42** [comment]
we are indeed using hetzner (and linode) and have enabled IPv6 routes <3
