### ISSUE TITLE
Public Grafana dashboard throws error, has no data

### ISSUE THREAD

**Issue by sindarina** [hachyderm/community#140]
![Screenshot 2022-12-01 at 14 55 05](https://user-images.githubusercontent.com/6074566/205071251-e80418d4-7a13-42c4-a58c-7b1fbc9983d4.png)

Every panel is empty, with a red warning in its top-left corner, and a "error running public dashboard panel queries" pops up for a few seconds when you (re)load the dashboard [via the link](https://grafana.hachyderm.io/public-dashboards/445bbb0e169f4e86b1d1eeee7e50c92a?orgId=0&refresh=5m) on the main README page.

**Comment by quintessence** [comment]
Mod here. 

This issue and others related to the migration are being closed and users redirected to discuss on issue #143.

**Comment by krisnova** [comment]
We intend to leverage this (new) endpoint for public graphs now that the migration is (more) complete.

https://grafana.hachyderm.io/public
