### ISSUE TITLE
Infinity rainbow custom emoji

### ISSUE THREAD

**Issue by dietrichm** [hachyderm/community#142]
The infinity rainbow is used by the neurodiversity community and [autism rights movement](https://en.wikipedia.org/wiki/Autism_rights_movement) to symbolise the spectrum of neurodiverse experiences. It would be nice to have this added as a custom emoji.

Wikipedia has an example SVG: https://commons.wikimedia.org/wiki/File:Autism_spectrum_infinity_awareness_symbol.svg

Neurodifferent.me, another Mastodon instance, uses the following image: https://media.neurodifferent.me/custom_emojis/images/000/000/002/original/4bf9ddc625481089.png

**Comment by quintessence** [comment]
First custom emoji post migration 🎉 ^.^ Done ^.^
