### ISSUE TITLE
Boosts and favourites not showing for posts from other instances

### ISSUE THREAD

**Issue by superchromix** [hachyderm/community#145]
Not sure if this issue is related to the migration or not.

When I check recent posts on my timeline, posted by users from other instances which I follow, the boosts and favourites (e.g. “Boosted by.. “ and “Favourited by.. “ are not appearing, even though the posts have been boosted and favourited.

For older posts (before the outage) this info is showing correctly.

Thanks!

**Comment by quintessence** [comment]
👋 Mod here

We were doing a migration earlier today - it should be complete and the service should be stable as of a few hours ago. Can you tell me if you're still experiencing this issue?

**Comment by superchromix** [comment]
The “boosted by” and “favourited by” info shows up correctly via the web interface, but not in the Toot! for iOS app.  

At this time, for pre-migration posts, e.g. posts older than a few days, this info shows correctly in the Toot! app.

**Comment by superchromix** [comment]
The boost/favourites info shows correctly in Metatext, so this issue seems to be specific to Toot!.

**Comment by superchromix** [comment]
The behaviour seems to be inconsistent.  For some posts, the info is missing from the web interface.  For others, it’s there.  I will keep an eye on the issue for a few days.

**Comment by quintessence** [comment]
Checking in on this one? :)
