### ISSUE TITLE
Some followed accounts in a weird state after follows.csv import

### ISSUE THREAD

**Issue by alxndr42** [hachyderm/community#148]
I migrated to Hachyderm.io today, and the follower migration was flawless! But when I imported the `follows.csv` from my old instance, roughly a third of the accounts ended up in a weird state: they are listed under `/following`, but the icon on the right side is a grey `+`, and the button on their profile page says `Follow`. When I click on either, the state changes, but only until I refresh the page. I'm seeing toots/boosts from some of them on my personal timeline, though. 🙃 My username is `@alxndr`.

Also: #HugOps, thank you so much for your work! ❤️

**Comment by maxfragg** [comment]
can confirm, I see the same for my account `@mxk` - but it seams to "heal" over time for most accounts.
By now, most accounts left in a strange state are protected accounts hosted on my old instance `chaos.social` - I assume this is not just a coincidence.

**Comment by alxndr42** [comment]
I'm not noticing automatic changes yet. Some of my missing accounts are protected, some are not. FWIW, when I try to click `Follow` on the protected accounts, the status reverts immediately, no page refresh necessary.

**Comment by quintessence** [comment]
👋  Mod here

Depending on how many follows you are importing the important may not appear instantaneous. We don't have exact math yet, but there does seem to be lag as the imports and federation "catch up". We don't have exact math on this yet, but I have a couple questions:

- How many are you expecting total and how many do you have so far
- Are there any patterns that you can tell in the import that are "successful faster" or no? e.g. "local is immediate" or "protected accounts seem to be missing" and so on

Thank you!

**Comment by maxfragg** [comment]
The state remains, and I started my migration intentionally with a decent waiting period after the migration.
Take my account `mxk` and `@lazy_bobcat@chaos.social` if you need an example

**Comment by alxndr42** [comment]
On my account (`@alxndr`), the issue affects local and (mostly) remote accounts, on multiple instances. Mostly unprotected accounts, IIRC.

I don't believe it's a matter of "catching up", because when I look at the account profiles on their own server, I can see that my `hachyderm.io` account is following them, and vice versa. (Hence their posts/boosts in my personal timeline, I suppose.)

As for the numbers, my `/following` page says I'm following 120 accounts, and I count 42 grey icons.

**Comment by alxndr42** [comment]
Update: I followed another account today (not protected, external), which immediately went into `Awaiting approval` state. Again, the external profile already showed that I was following it.

But now, a few hours later, all the other accounts no longer have grey icons! Not sure what to make of this, but at least I went from 42 "following, but not showing it" accounts to only one. :tada:

**Comment by quintessence** [comment]
Excellent! I wonder if there were two things clogging the pipes for the events related to your request - the migration and then the DDoS we fended off the other day backing up our queues briefly. I'm going to go ahead and close this issue for now but if it recurs please open a new one :)
