### ISSUE TITLE
Get added to https://fediverse.space

### ISSUE THREAD

**Issue by jakesmolka** [hachyderm/community#15]
Absolutely optional and only nice-to-have. https://fediverse.space is a neat illustration of the fediverse and how that (honestly impressive) network is spun.

https://fediverse.space/about explains how to get added:
> How do I add my personal instance?
> Click on the Administration link in the top right to opt-in.

https://fediverse.space/admin/login in turn states
> You must be the instance admin to manage how fediverse.space (sic, missing end?)

**Comment by krisnova** [comment]
Added https://fediverse.space/instance/hachyderm.io
