### ISSUE TITLE
Something weird is going on

### ISSUE THREAD

**Issue by alexschrod** [hachyderm/community#153]
I noticed I was having trouble loading the full size images on Hachyderm, so I went to the [Grafana](https://grafana.hachyderm.io/public-dashboards/445bbb0e169f4e86b1d1eeee7e50c92a?orgId=0&refresh=5m) link that Nova posted yesterday, and noticed that the "pull" Sidekiq queue was growing at an enormous rate. When I first looked at the page, it had gone to a latency of 3 minutes in... 3 minutes and now it's already at 8 a few minutes later. I figure it means something fishy is going on.

**Comment by alexschrod** [comment]
Here's a screenshot of what I was seeing for the sake of posterity:
![image](https://user-images.githubusercontent.com/767490/205429608-b9584efe-d6f1-4809-8027-49ddfab92510.png)

**Comment by ineffyble** [comment]
Related: https://github.com/mastodon/mastodon/issues/21977

**Comment by quintessence** [comment]
👋  Mod here

@ineffyble is correct - this AM, multiple instances - including ours - were subjected to a DDoS. We were able to contain ours and have some notes that Nóva published in here thread here:

https://hachyderm.io/@nova/109451797235439044

OP can you let us know if you're still experiencing this issue?

**Comment by alexschrod** [comment]
@quintessence Media seem to be loading just fine again. I'll close the issue for now, thanks for the feedback.

**Comment by quintessence** [comment]
Excellent thank you!
