### ISSUE TITLE
Domain farm in action

### ISSUE THREAD

**Issue by piccolbo** [hachyderm/community#154]
I took a look at the federated timeline and I see only spammy posts from domains like

3ggqbyltr.activitypub-troll.cf

With minimal content

1h
1nyghw775@3ggqbyltr.activitypub-troll.cf
1nyghw775 @1nyghw775@3ggqbyltr.activitypub-troll.cf
@1a61qk2ak @19scasybn

I can't block it or at least it would be a fool's errand because every post is coming from a different subdomain. I think the bad actors are finding mastodon weaknesses. I don't see any payload. At least they are honest, the domain declares itself as a troll. Not sure what we can do, maybe there is an admin-level tool to deal with this, but, as a user, they just saturated my federated timeline and there's  nothing I can do.

**Comment by Ghryphen** [comment]
Just adding a screenshot for reference.

![Screenshot_20221203_025134](https://user-images.githubusercontent.com/128811/205437339-cbd1b9fd-b102-4f39-b175-22e33a2689d2.png)

**Comment by ineffyble** [comment]
> I can't block it or at least it would be a fool's errand because every post is coming from a different subdomain. 

If you block the domain itself (activitypub-troll.cf), that will apply to all subdomains.

**Comment by ineffyble** [comment]
Related: https://github.com/mastodon/mastodon/issues/21977

**Comment by piccolbo** [comment]
For my education, how do you do that? When I see a spammy message I click
on the three door menu, block domain. I get a dialog to confirm the block
on the subdomain without a chance to edit it.

**Comment by ineffyble** [comment]
@piccolbo Oh, hmm, I'm wrong. Instance-level domain blocks apply to subdomains. But users can only block specific domains.

**Comment by piccolbo** [comment]
Thanks for the clarification. I guess we'll report to mods and they'll do the clock. It seems to have stopped.
