### ISSUE TITLE
Sessions showing with IP addresses in the shared address space

### ISSUE THREAD

**Issue by Wiltuk** [hachyderm/community#155]
Since the migration sessions appear to be showing up with IP addresses in the shared address space.

Here are two sessions on my account, one two days ago with a correct IP address and the current session with an IP within 100.64.0.0/10
<img width="698" alt="Screenshot 2022-12-03 at 10 59 25" src="https://user-images.githubusercontent.com/4584580/205437594-4556bd92-3748-4f88-9c0d-8c298f27759f.png">

This could potentially prevent users from being able to identify unauthorised access to their account.

**Comment by Wiltuk** [comment]
It looks like this has been fixed now:

![Untitled](https://user-images.githubusercontent.com/4584580/205996325-1d154b85-3796-41d3-8b86-46f2a2a0f3db.jpg)

**Comment by quintessence** [comment]
👋  Mod here

Ah you beat me to it! Apologies I thought I had hit "enter" on my response last night when I tagged it / self assigned. In any event: the short version is minor change in the X-Forwarded-For header :)
