### ISSUE TITLE
Resources from toot.community

### ISSUE THREAD

**Issue by j3j5** [hachyderm/community#156]
I saw that [toot.community](https://hachyderm.io/@jorijn@toot.community/109449478726212083) open-sourced [their infrastructure setup](https://blog.toot.community/posts/open-sourcing-toot-community/). 

I know we are not using Kubernetes but it may be a useful resource to have handy in case we ever move to such a setup. There may also be some other configs that the admins may want to check. They have their own [GitHub](https://github.com/toot-community) as well.

Not sure if there's already another place where this can be added instead of as an issue.

**Comment by quintessence** [comment]
👋 Mod here :) 

We actually have made our infra public on our blog:

https://community.hachyderm.io/blog/2022/12/03/leaving-the-basement/

As for opening the infra to the public, we haven't done so at this time but it doesn't mean we won't in the future :) We just have other issues that we've been handling on a higher priority :)

**Comment by j3j5** [comment]
Oh, I know, and I think is awesome. I didn't mean to pressure or anything, opening the issue I just wanted to post the link somewhere that wouldn't get lost because I thought their experience may be useful to the team at some point. 

Feel free to close if this is not the best way to share such resources, but it wasn't about "hachyderm doing the same thing" but more as in "what they wrote may be useful for us".

**Comment by quintessence** [comment]
Not taken as pressure at all :) I just wanted to make sure that you saw what we did currently have available.

We have discussed putting more thorough infra up, and if/when it is live it will live on the new Community Page under the docs section so it is easily discoverable :)

**Comment by quintessence** [comment]
We're still updating this page, but FYI

https://community.hachyderm.io/docs/infrastructure/

This is what we will be keeping updated as the "source of truth" for our infra.
