### ISSUE TITLE
Add emacs custom emoji

### ISSUE THREAD

**Issue by danwlsn** [hachyderm/community#16]
I would love to add the emacs emoji into my name :) 

![emacs](https://user-images.githubusercontent.com/1922851/201052545-6f2bd1d7-afe5-420d-949d-f98c1912e88c.png)

Taken from [slackmojis](https://slackmojis.com/emojis/2228-emacs)

**Comment by krisnova** [comment]
I support this.

**Comment by krisnova** [comment]
Added!
