### ISSUE TITLE
Hachyderm Blog: broken links

### ISSUE THREAD

**Issue by piccolbo** [hachyderm/community#168]
It seems the View page source and  edit this page links in the top right corner are broken.

https://github.com/hachyderm/community/tree/main/content/en/blog/_index.md

https://github.com/hachyderm/community/edit/main/content/en/blog/_index.md

**Comment by krisnova** [comment]
was this closed with #169 maybe?

**Comment by hazelweakly** [comment]
Yes, I checked the buttons for all the blog posts and they're all working for me now :)
