### ISSUE TITLE
Is Docker required to build community.hachyderm.com?

### ISSUE THREAD

**Issue by alanwsmith** [hachyderm/community#177]
I made some updates to the community.hachyderm.com README including noting that XCode might be required for a mac. 

I also noticed there's a docker-compose file. Is Docker required too? If so, do we know what needs to be installed (or which install page to link to)?

**Comment by quintessence** [comment]
You do not need to use Docker locally to build the site : )

**Comment by alanwsmith** [comment]
cool cool cool (I've got it installed, so I couldn't tell)

closing since there's nothing to do
