### ISSUE TITLE
Add local-only toots

### ISSUE THREAD

**Issue by mikejk8s** [hachyderm/community#18]
I was looking at the features of Mastodon Glitch (https://glitch-soc.github.io/docs/) which has a bunch of interesting addons. 

One I thought would be pretty nice is the Local-only toots https://glitch-soc.github.io/docs/features/local-only-toots/#:~:text=glitch%2Dsoc%20adds%20a%20feature,server%20announcements%20and%20meta%2Ddiscussion.

https://github.com/hometown-fork/hometown/wiki/Local-only-posting

**Comment by dmah42** [comment]
deduplicating with #3 :)
