### ISSUE TITLE
specify mods to tag about minor requests

### ISSUE THREAD

**Issue by fcevado** [hachyderm/community#183]
There are a few common hashtags that people usually tag instance mods/admins to address stuff directly from toots.
People use `#emojiRequest` to ask for specifics emoji and `#fediblock` is frequently used by instance admins when they identify bad behaved instances.
It would be cool to be able to know who to tag when some of those appears.

For example I think it would be cool to have interaction flags emoji, justa screenshot that I took from a brazilian instance that i participate:
![image](https://user-images.githubusercontent.com/9992984/206215493-54665f4d-bc14-4785-a3ab-3ad8e5384ff3.png)

one other cool thing would be classify custom emojis, to make it easier to find them.

**Comment by quintessence** [comment]
👋 Mod here

- The way to reach out to the mod team, for blocks, emoji, etc. is to use the GitHub issue tracker here. This is to allow us to be able to track requests of this nature, see that they're handled, etc.
- For some domain blocks, users might be requesting domain blocks based on behavior of users on other servers that goes against our server ethos and/or rules. In that case, the post(s) should be reported and the additional context should be provided in the report (note that when you report a post / user you receive a dialog box to include more information).

These decisions are based on a couple of factors, including the size of our userbase, size of our admin team, and the ability of the admin team to look through the issue / request history. The last one is especially important to requests that may need to be referenced later for any reason.

**Comment by quintessence** [comment]
Put this in our docs queue for our posts on hashtags / expectation setting. Closing for now :)
