### ISSUE TITLE
I didn't post that!

### ISSUE THREAD

**Issue by JesseLiberty** [hachyderm/community#185]
In looking through Home today I saw a post from me that I did not post!  https://hachyderm.io/@jesseliberty/109477850457896954

I will change my password immediately but there is no telling what else was posted in my name.

**Comment by dmah42** [comment]
that post has been deleted... did you look through your profile and check for other instances of posts you didn't make?

**Comment by JesseLiberty** [comment]
I deleted the post. I don't see any other problems.

Thanks.

Jesse Liberty
He / Him / His
Technical Blog <http://jesseliberty.com/>
Microsoft MVP
<https://mvp.microsoft.com/en-us/PublicProfile/5000326?fullName=Jesse%20Liberty>
Fiction Blog <https://jlauthor.me/>
Newsletter <https://substack.com/jesseliberty>
Book Store <https://bookshop.org/shop/jesseliberty>
Mastodon ***@***.***>
LinkedIn <https://linkedin.com/in/jesseliberty>
I have left Twitter


Currently Reading
<https://www.goodreads.com/user/email_signature_destination/22026795?utm_medium=reading_link&utm_source=email_signature>
[image: Book Cover]
<https://www.goodreads.com/user/email_signature_destination/22026795?utm_medium=cover&utm_source=email_signature>
[image: Goodreads Logo]
<https://www.goodreads.com/?utm_medium=gr_logo&utm_source=email_signature>Get
your own email signature
<https://www.goodreads.com/user/email_signature_instructions?utm_medium=gyo_link&utm_source=email_signature>

**Comment by quintessence** [comment]
Thank you for letting us know! I'm going to go ahead and close this issue for now. If your account is or has been compromised either now or in the future, please open a new ticket.

For this issue: I saw that you already changed your password - you might want to enable 2FA as well.
