### ISSUE TITLE
A list of all blocked domains with severity and options

### ISSUE THREAD

**Issue by dataCobra** [hachyderm/community#186]
Hello lovely hachyderm community,

I'm hosting a mastodon server for my company and want the same welcoming environment that you got.

For this I would like to have a readable list of all blocked domains with severity and options. If you could add the reason why a domain got blocked too this would be even better!

Could you provide such a list?

Sadly the list that mastodon itself provides uses asterisk to hide some domains.

Regards,
Ben

**Comment by dmah42** [comment]
are you planning on applying the list automatically to your instance using the new domain block APIs in 4.0.x?  i'm wondering what format you're looking for.

if you're just looking to see which ones are blocked, then i think the list on about/more is probably sufficient.  anything that's in the admin APIs that require admin::read permissions are not something i think we should be exposing as i imagine those permissions are in place for a reason (at the mastodon level).

**Comment by dmah42** [comment]
are you planning on applying the list automatically to your instance using the new domain block APIs in 4.0.x?  i'm wondering what format you're looking for.

if you're just looking to see which ones are blocked, then i think the list on about/more is probably sufficient.  anything that's in the admin APIs that require admin::read permissions are not something i think we should be exposing as i imagine those permissions are in place for a reason (at the mastodon level).

**Comment by dataCobra** [comment]
I'm not looking for a particular format. I want to add the block list manual.

I would like to have a good starting block list for my companies instance.

**Comment by dmah42** [comment]
what's missing from https://hachyderm.io/about/more ?  i think there's very few that are obscured so perhaps the ones that aren't are enough to get started?

**Comment by dmah42** [comment]
what's missing from https://hachyderm.io/about/more ?  i think there's very few that are obscured so perhaps the ones that aren't are enough to get started?

**Comment by dataCobra** [comment]
It's not fully visible which severity and options are used for each of this blocked domains.

Even with the censored domain names it's a pretty big list I can work with, but most of the time these are the really problematic ones. I would like to include them from the beginning.

**Comment by quintessence** [comment]
👋 Mod here

The list of domains on our About list is the source of truth for all blocked domains at this time. In the future we intend to have documentation about what goes into the blocklist so that users understand this process better. We don't currently have the bandwidth to break down the Blocklist into custom formats / etc.

**Comment by quintessence** [comment]
Update: here is our new docs page about Blocklists:

https://community.hachyderm.io/docs/blocklists/

**Comment by dataCobra** [comment]
Thank you for all the information. :slightly_smiling_face: 
That will do it for know. :+1:

I'll read the new docs for some inspiration regarding our blocklist.
