### ISSUE TITLE
Increase Posting Size from 500 chars to 2000?

### ISSUE THREAD

**Issue by DanielSmith** [hachyderm/community#187]
**Suggestion**

Is there interest in increasing posting size to some larger number of characters?  It is currently 500.  2000 may be a nice bump.

* increasing # of chars 4x does not mean total text traffic would increase 4x (witness infosec.exchange as one example)
* total storage needs not heavily impacted (as opposed to storing more images or other binary media)

Not much else to say.  It should be a tunable parameter.  Likely problem areas might be: DB Fields that have a hardwired expectation (varchar(512), etc), caching, etc... anything that is hardwired for post length.

**Comment by freiheit** [comment]
I think this duplicates #70

**Comment by DanielSmith** [comment]
Ah, I did not spot #70 before.  Yep, same idea.  I dont mind if the issue is closed or allowed to linger as a "future" item.  As a developer, it would not surprise me if there are hardwired assumptions in the DB/Code about post length - so it may not be a simple "tweak this one config field" change.

**Comment by dmah42** [comment]
it's quite an invasive change (https://www.draklyckan.se/2021/11/how-to-increase-the-character-limit-for-toots-in-mastodon/) .. i think given that we have the [internal issue](https://github.com/hachyderm/infrastructure/issues/97) open i will close this too.  thanks :)
