### ISSUE TITLE
Project Galileo

### ISSUE THREAD

**Issue by OneJaeAtATime** [hachyderm/community#189]
Cloudflare has opened up [Project Galileo](https://newsie.social/@jeff/109472272956314954) to Mastodon servers. Just wanted the team to be aware in case we might need their service.

**Comment by quintessence** [comment]
Ah! Thank you! I will make sure the rest of the team sees this as well :D

**Comment by alanwsmith** [comment]
I wasn't familiar with Project Galileo. Snagged this tl;dr from [the project page](https://www.cloudflare.com/galileo/) if anyone else needs it and wants to save the click:

> Founded in 2014, Project Galileo is our response to devastating cyber attacks launched against important yet vulnerable targets, like artistic groups, humanitarian organizations, and the voices of political dissent.

> Through Project Galileo, Cloudflare provides free, robust security to enterprises that are the targets of DDoS and other cyber attacks.

**Comment by quintessence** [comment]
Realized I didn't close this after I passed it along internally - closing now :)
