### ISSUE TITLE
Consider adding a status page?

### ISSUE THREAD

**Issue by nkcmr** [hachyderm/community#19]
Currently getting a 502 from hachyderm.io but not too sure if it is just me or not.

**Comment by krisnova** [comment]
We are working on it. The 502 was because of our maintenance this morning. Status page coming soon.

**Comment by jakesmolka** [comment]
There's
- https://status.hachyderm.io
- A public grafana dashboard, but it's not working anymore (temporary?)

Agreed, they should be added to the docs.

**Comment by quintessence** [comment]
Update: the public Grafana dashboard is now working post-maintenance and the link to it is in the community user doc (README)

**Comment by krisnova** [comment]
status.hachyderm.io
