### ISSUE TITLE
Broken About Links

### ISSUE THREAD

**Issue by michael-hawker** [hachyderm/community#193]
### Please let us know what you would like to add or change?

Found some links that aren't working.

From the [about page](https://hachyderm.io/about) this link doesn't work anymore: https://github.com/hachyderm/community/tree/main/accounts

[This md file in the root](https://github.com/hachyderm/community/blob/main/corporate-accounts.md) points to a page that also doesn't exist: https://github.com/hachyderm/community/blob/main/accounts/corporate-accounts.md

I would guess they want to point to somewhere here? https://github.com/hachyderm/community/tree/main/community.hachyderm.io/content/en/docs/account-types (or wherever this gets hosted)

**Comment by quintessence** [comment]
Ah! I'll fix those - they happened as part of our migration to our new docs site:

https://community.hachyderm.io/docs/

I'll update the broken links you found :)
