### ISSUE TITLE
Traffic and Demographic analytics  -- Community Discussion Thread

### ISSUE THREAD

**Issue by krisnova** [hachyderm/community#196]
### What is your suggestion?

As we move forward understanding hachydermians wants/needs and patterns should we offer a public set of analytics for our community website or the service itself?

**Comment by kashfshah** [comment]
Thanks for asking!

At this time, I am of the opinion that the fediverse would be well served by being open about basic demographics - accounts x account type x time, for example.  I want to give this some more thought, however.

This question has me thinking of picking up a copy of [Transparent Society by David Brin](https://www.davidbrin.com/transparentsociety.html).  There's a chapter in there called "Humility and Limits" which sounds like it may have some relevant insight to this question.

Similarly, I want to dig into what Mastodon, itself, [already provides](https://api.joinmastodon.org/statistics), and what existing consensus their might be about this topic in the overall fediverse or if anyone has discussed it in the context of the [Mastodon Server Covenant](https://joinmastodon.org/covenant) over in the [Mastodon GitHub](https://github.com/mastodon/mastodon/issues).

I am also currently of the opinion that any basic demographics about accounts ought to be paired with basic statistics about moderation and server safety (# of reports over time, # of bans, etc).

Still a fediverse newbie, so opinions may change over time, as I gain more experience and situational awareness, but I do intend to contribute further to this discussion.
