### ISSUE TITLE
Silencing is more disruptive than may be expected

### ISSUE THREAD

**Issue by richfelker** [hachyderm/community#198]
### What is your question?

I recently stumbled across conversations involving users on an instance still silenced as an outcome of https://github.com/hachyderm/community/issues/65, and was surprised to find that I could not see their posts, and moreover, that threads they had participated in were broken without following the involved account(s) from the silenced instance. This of course makes some sense in light of the model for how silencing an instance works, but it seems surprising and maybe beyond the level of silencing probably wanted - most likely, just avoiding having posts from that instance show up in federated feed, boosts, etc.

I'm not sure what the outcome of this should be. It probably suggests that silencing is a good short-term tool for instances where it's not yet clear whether there's a moderation problem and something needs to be done right away, but that for other issues a finer-grained or different instance-level moderation tool may actually be what's wanted.

**Comment by quintessence** [comment]
Thank you for making the separate issue for this! From what you included before it looks like Hachydermians cannot just open and view a profile of a Limited Server, is that correct?

**Comment by ambihelical** [comment]
It is also impossible for someone from a silenced server to follow anyone on hachyderm.io, at least as far as I can tell as a user on qoto.org, another silenced instance.

**Comment by quintessence** [comment]
👋 Some more updates:

We've started going through our silenced domains in particular and started refederating with some of them. I'm going to close this ticket for now, as we're still figuring out middle of the ground options. Please open new tickets if there are any specific domains that you'd like to see us review.
