### ISSUE TITLE
Android app crashes due to duplicate emoji

### ISSUE THREAD

**Issue by DanielThomas** [hachyderm/community#2]
I tried to access the `#Java` tag earlier, and can reliably crash the Android app. Feels like there could be a server issue contributing so figured I'd report here too in addition to the app report:

![Screenshot_20221107-190014](https://user-images.githubusercontent.com/1479220/200257237-05566f78-d679-4e3d-b68b-a4032ce52a08.png)

**Comment by DanielThomas** [comment]
For a minute there I could reproduce with the inline emoji picker, but can't seem to get it to crash now. Still crashing on content in the #java tag r/n though.

**Comment by davidshq** [comment]
Curious if this is still crashing? Also, assuming you are using the official Mastodon Android client?

**Comment by DanielThomas** [comment]
Yeah, the post that's crashing is further down now so I have to scroll the list a little, but can reliably crash. It's the official Android app. I don't see a custom emoji in the picker for this, so it's must be cached from another server.

**Comment by DanielThomas** [comment]
Nope, all the app! Sorry for the noise. https://github.com/mastodon/mastodon-android/pull/275
