### ISSUE TITLE
Open Source Project Accounts: Ian Coldwater example URL leads to 404 page (minor)

### ISSUE THREAD

**Issue by opalmirror** [hachyderm/community#201]
Minor documentation issue. The Ian Coldwater link on the documentation page https://community.hachyderm.io/docs/account-types/open-source-accounts/ goes to https://hachyderm.io/web/@ian which causes Mastdodon to display a 404. This should be corrected to https://hachyderm.io/@ian

BTW I am @opalmirror@hachyderm.io.

**Comment by quintessence** [comment]
👋 Mod here

Thank you for catching - fixed. I believe it was only on the Influencer Account page and not the OSS page as I can't find a reference to Ian on the latter. Can you confirm if this is the correct page? (Fixed it here.)

https://community.hachyderm.io/docs/account-types/influencer-accounts/

**Comment by opalmirror** [comment]
Sorry for the late response and for catching my error, it was definitely just the influencer page, so you got it.

**Comment by quintessence** [comment]
No worries just wanted to make sure it wasn't anywhere else :)
