### ISSUE TITLE
Additional Github Emoji

### ISSUE THREAD

**Issue by ElanHasson** [hachyderm/community#204]
### So what emoji are you looking for?

I know we already have :github_logo:, but it's purple and I'm not a fan of how it looks in dark mode:
![image](https://user-images.githubusercontent.com/234704/208011038-8c9bfdee-a72c-4ef5-aefc-840054a12e6f.png)

Could we replace it with this instead? This came from another mastodon server.
![b0feeccb7ac4c3f4](https://user-images.githubusercontent.com/234704/208011066-25593a6d-ccb2-4231-8c92-312ee241050b.png)

![image](https://user-images.githubusercontent.com/234704/208011106-98cf8bd1-5fd2-45f4-a7ff-cdfddf8b8292.png)

Thanks!

**Comment by quintessence** [comment]
No worries - copied it in :)
