### ISSUE TITLE
Minor CSS pedantry - head-shot inset border on website

### ISSUE THREAD

**Issue by richardbrockie** [hachyderm/community#205]
### What is your suggestion?

The inset head-shot pic on the web interface has no border on the left:

<img width="357" alt="Screenshot 2022-12-16 at 1 47 22 PM" src="https://user-images.githubusercontent.com/10185602/208194550-82e0ef9f-9ad3-4ee6-954f-23db4d1b4248.png">

The inset on the iOS app has the border all the way round:
![iOS](https://user-images.githubusercontent.com/10185602/208195092-365fecec-590e-4e36-8971-fce8ccba99ec.png)

I think having the border all the way round is nicer - could the website CSS be changed to follow the app?

**Comment by richardbrockie** [comment]
I see that it's not just #hachyderm that does this, but other instances also - this is probably the wrong place for this request?

**Comment by wlonkly** [comment]
Looks like an upstream bug, https://github.com/mastodon/mastodon, I don't see an open issue for it yet though! (But double-check!)

**Comment by quintessence** [comment]
👋 mod here.

You're both correct - this is definitely something that'd need to be requested on [Mastodon's Issue Tracker](https://github.com/mastodon/mastodon/issues)

**Comment by richardbrockie** [comment]
Ok - I'll submit it, but 3.2k open issues!!!? Wow!
