### ISSUE TITLE
Any plans to add elasticsearch?

### ISSUE THREAD

**Issue by fields** [hachyderm/community#206]
### What would you like to discuss with us or let us know?

I didn’t see anything about this in any of the architecture docs - any plans to add elasticsearch for local searching? I’m really missing the ability to search previous conversations.

Thanks!

**Comment by quintessence** [comment]
Yes we are! Right now we're working on an image caching issue, but it is in the backlog to do (and we will announce when we do) :)

**Comment by quintessence** [comment]
We ended up adding + enabling Elasticsearch after the image caching issues were fixed last week :) 

Happy holidays!
