### ISSUE TITLE
Clarify process around temporary moderation decisions.

### ISSUE THREAD

**Issue by timdmackey** [hachyderm/community#208]
I have no particular interest in this specific instance, but the discussion in #65 left me wondering about the permanence of moderation decisions when a server is "limited."

There doesn't seem to be any documentation about temporary moderation decisions—I may be misunderstanding, but it seems in this case that limiting the server in question was a temporary measure? If that is the case, and assuming a similar situation might occur in the future, it would make sense to clarify how that process will work when a server is being moderated on a "wait and see" basis. Is there a probationary period? Is the server limited indefinitely until someone creates a new issue about it?

I'm not sure the scope of questions that need to be asked here, but it's a point that could potentially use more clarity.

**Comment by quintessence** [comment]
👋 Mod here

When a decision is made that is temporary we do try to send out communications that are time-relevant to that decision. That said, decisions like this are "permanent" but subject to change when a user requests that we look into / change a server's moderation status (Limited, Suspended). This is outlined on our Blocklist doc here:

https://community.hachyderm.io/docs/blocklists/
