### ISSUE TITLE
WebAssembly/Wasm emoji request

### ISSUE THREAD

**Issue by nigelpoulton** [hachyderm/community#209]
### So what emoji are you looking for?

Please create an emoji for WebAssembly/Wasm. Cheers!

![1200px-WebAssembly_Logo svg](https://user-images.githubusercontent.com/10812787/208245353-19e30e6f-1f3b-4582-9d81-582cb5a933ef.png)

**Comment by quintessence** [comment]
👋 Mod here

You got it :)

**Comment by nigelpoulton** [comment]
> 👋 Mod here
> 
> You got it :)

Thanks @quintessence can I be cheeky and ask for a minor mod... can it be changed from `:WebAssembly_Logo:` to `:Wasm_Logo:` so it fits easier in the 30 char limit for Display Names :-D

**Comment by quintessence** [comment]
We have a few requests for shorter emoji name, but aside from the ones that are cloned in the emojis are named that way for screenreaders :)

**Comment by nigelpoulton** [comment]
> We have a few requests for shorter emoji name, but aside from the ones that are cloned in the emojis are named that way for screenreaders :)

Totally understand, and I'm not trying to be awkward here. But "Wasm" is used interchangeably with "WebAssembly" so should be cool for screenreaders.

I know you guys are super busy, so no stress. I've dropped my last name form my profile and am currently using `:WebAssembly_Logo:` :+1:
