### ISSUE TITLE
Announcement timestamps 

### ISSUE THREAD

**Issue by corneil** [hachyderm/community#210]
### What is your suggestion?

I love the announcements!
I noticed that Tusky shows announcements but they don't show any timestamp or date.

It would be great if you could add a timestamp with timezone info at the top of announcements.

Regards
Corneil

**Comment by quintessence** [comment]
This is a great suggestion! We'll review it moving forward. Since we're working on an issue today please be patient with us if we forget but we'll be aware moving forward.

**Comment by timdmackey** [comment]
It also doesn't show a timestamp in Metatext or in the Web UI. I was thinking about this the other day when there were two announcements visible simultaneously. I'm glad someone brought it up!

**Comment by corneil** [comment]
I just saw a new announcement with a timestap! 
Thanks. 🙏

**Comment by quintessence** [comment]
No problem!
