### ISSUE TITLE
Add donation links to docs

### ISSUE THREAD

**Issue by alanwsmith** [hachyderm/community#214]
### Please let us know what you would like to add or change?

> Are you requesting documentation that doesn't exist yet and what questions need to be addressed?

Yep, thinking about a new page and links.

Specifically, I'm not seeing links to donation pages. I'm not suggesting a wikipeida style half page take over. Just making some clear links. 

I think a top level nav link to a donations page would make sense. (Details of how that link would work would depend on if the first steps can be embedded, etc...) 

If a form can be embedded on the home page I'd suggest that's worth considering as well.

**Comment by quintessence** [comment]
Correct! We're going to be following up with this in our docs once ready :)
