### ISSUE TITLE
Consider combining About and Home page

### ISSUE THREAD

**Issue by alanwsmith** [hachyderm/community#215]
### Please let us know what you would like to add or change?

> Are you requesting to update or delete sections of existing documentation? If so, please provide

It feels like the content of the "About" page could be moved to the home page. It would make it more front and center. Folks would be likely to see it since they don't have to click. 

Some possible options for the About page would be:

1. Remove it?
2. Make it into something like "Hachyderm is brought to you by... with the admins" and like a two sentence mission statement type thing.

Here's a random sampling of other ones (from my open tabs) that might be a helpful reference:

- [GitHub](https://github.com/about)
- [PGA TOUR](https://www.pgatour.com/company/aboutus.html) (my old gig and this is the first time I actually looked at the about page lol)
- [MDN](https://developer.mozilla.org/en-US/about) 
- CSS Tricks doesn't have one that I can find, but they link to [this one from Digital Ocean](https://www.digitalocean.com/about)
- I don't see one on the [Rust site](https://www.rust-lang.org/)
- I don't see one on [Spritely Institute](https://spritely.institute/)

**Comment by quintessence** [comment]
I think that this is going to be solved by migrating the docs to the new Community Docs page but wanted to verify before closing?

**Comment by alanwsmith** [comment]
I'm so sorry, I haven't been in GitHub for a couple weeks and am just seeing this. I think closing it works great given the migration. 

Gonna go ahead and do that now to take it off the plate.

**Comment by quintessence** [comment]
❤️ 

Welcome back from the holidays :)
