### ISSUE TITLE
Media in toot not visible

### ISSUE THREAD

**Issue by arjenpdevries** [hachyderm/community#217]
### Please describe the issue you are seeing.

See https://idf.social/@arjen/109531896479545766

The post had media attached that would not open, but if you manually rewrite the URL, it is visible.

(The rewrite pattern was taken from a previous post of which the url is listed in my post.) 

### How long have you noticed this issue?

Only just now. 

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by arjenpdevries** [comment]
I just realized something that might help too.

When I open this toot by Nova at your site [A]:
https://hachyderm.io/@nova/109531826029090165

But when I open it at our instance [B]:
https://idf.social/@nova@hachyderm.io/109531829891148151

Somehow the image attachment is not there.

[A] uses https://media.hachyderm.io/media_attachments/files/109/531/824/199/705/980/original/8655c1d2b0a8d3aa.png
[B] refers to https://hachyderm.io/system/media_attachments/files/109/531/824/199/705/980/original/8655c1d2b0a8d3aa.png that does not exist

So it's not just the avatars on your own instance that seem to get assigned multiple URLs, it's also where media are (not) located for toots received at other instances.

**Comment by quintessence** [comment]
Closing as resolved as part of what we worked on earlier this week to resolve media issues :) Please open a new issue if this is persisting :)
