### ISSUE TITLE
Access denied when loading image 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#218]
The access denied problem when loading an image occurred again. It was posted 17min ago.

https://media.hachyderm.io/cache/media_attachments/files/109/533/625/055/149/737/original/d386ccf1b5abc0c1.jpg

https://mastodon.social/@AbandonedAmerica/109533624894089572

**Comment by blueturtleai** [comment]
https://media.hachyderm.io/cache/media_attachments/files/109/533/331/473/622/418/original/7437b87cafab387e.jpg

https://media.hachyderm.io/cache/media_attachments/files/109/533/331/584/825/161/original/c5cf0aa94ea8ac12.jpg

Another 4 images. Posted 1hour ago.

https://media.hachyderm.io/cache/media_attachments/files/109/533/331/708/158/474/original/a0a18cc3912c75cc.jpg

https://media.hachyderm.io/cache/media_attachments/files/109/533/331/805/957/113/original/997177e44daf560d.jpg

https://mstdn.jp/users/EiichiYoshioka/statuses/109533441253366107/activity

**Comment by timdmackey** [comment]
Also experiencing images being broken, in both web ui and in app.

![image](https://user-images.githubusercontent.com/182772/208291633-7ba6a2dc-693b-40ec-ab61-2c198dbdd164.png)

![image](https://user-images.githubusercontent.com/182772/208291637-a0677dd1-cf87-40df-9c5b-8e353b4de097.png)

**Comment by timdmackey** [comment]
Adding that I just experienced this with a 2-year old post from the admin of mastodon.lol

This link works:
https://mastodon.lol/@nathan/104289185227514319
This link doesn't: https://hachyderm.io/@nathan@mastodon.lol/104289185184551545

**Comment by blueturtleai** [comment]
Since I reported that issue, it don’t occur again. So, I would close the issue. What do you think @timdmackey?

**Comment by quintessence** [comment]
Thank you for the update and apologies for the delay over the holiday. I wasn't able to replicate on our end - if y'all can verify if we can close the issue that'd be great :)

**Comment by quintessence** [comment]
Hello!

Apologies for the delay over the holiday. These were aftershocks from the media outage that happened earlier in the month (it had to do with re-caching). 

Just to verify consensus - are we good with closing this one?

**Comment by blueturtleai** [comment]
For me it’s okay to close.

**Comment by timdmackey** [comment]
Yes, I haven’t had any issues in a few day. Thanks.

Happy Holidays!

**Comment by quintessence** [comment]
Right on :)
