### ISSUE TITLE
changing custom emoji names to screenreader friendly

### ISSUE THREAD

**Issue by deborahgu** [hachyderm/community#220]
### What is your suggestion?

Screen readers read the custom emoji `:foobar:` name, so would it be possible to make the names in out custom emoji list more screen reader friendly? If you're willing I could create a mapping, although I might want to reach out to someone who knows more about a few of them, so I get the right connotations. Many of them are already fine! And many just want to get switched to Camel Case, but a small number would really improve with a clarification that doesn't assume you can see the picture.

So something like:

```csv
ablobfoxbongo,FoxBongo
antiverified,AntiVerified
pusheenbake,PusheenBake
aws_logo,AWS_Logo
bigblobhajhug,BlåhajSharkHug
blobfoxfloof_w_,FoxSmilesWFace
blobfoxflower,FoxFlower
blobfoxgooglymlem,GooglyEyedFoxMlemTongue
blobhajhugsmall,CatHuggingBlåhajShark
trekbadgetng,TrekBadgeTNG
ShipIt,ShipItSquirrel
```

They need to be useful to both sighted people picking/typing them, and blind people hearing (and picking/typing!) them, which makes some of the decisions hard. I'm not sure if "blob" or "floof" are useful indicators to a screen reader user, but they may be useful to users choosing them?  Some, like "mlem" or `w` face, are hard to describe usefully.)

**Comment by quintessence** [comment]
This is something we're already looking into, actually! The main issue is that since many of the emoji were copied in we need to go through and make the edits without introducing a breaking change :)

**Comment by deborahgu** [comment]
awesome, thanks! Let me know if you do end up wanting a hand with any a11y stuff; my Ruby's almost non-existent and I don't have time for ops but I'm always happy to help with a11y.

**Comment by quintessence** [comment]
Thank you for the offer! There'll definitely be times we could use someone to bounce ideas off of :D

**Comment by quintessence** [comment]
Going to close this but would you be able to email me at quintessence @ hachyderm to discuss further? :)
