### ISSUE TITLE
Container emoji

### ISSUE THREAD

**Issue by nigelpoulton** [hachyderm/community#225]
### So what emoji are you looking for?

How about a container image emoji as `:container:`

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2Fixxximi_shipping-containers-icons-icon-transparent-icon-container-png%2F&psig=AOvVaw2hxi0SbNIuD3ruOkPfcOKA&ust=1671562288614000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCKCyjfWshvwCFQAAAAAdAAAAABAJ

**Comment by quintessence** [comment]
Added as shipping container :)
