### ISSUE TITLE
Access denied on some profile images (again)

### ISSUE THREAD

**Issue by durka** [hachyderm/community#226]
### Please describe the issue you are seeing.

I'm sorry to say it seems like #207 might have come back.

At this link: https://hachyderm.io/@Stoned_Deva_@mindly.social/109542572611611545

I am seeing this: 
![image](https://user-images.githubusercontent.com/47007/208550044-d5df5140-662f-4d1d-b26c-461fd0f14b43.png)

Here is the URL it's trying to load:
![image](https://user-images.githubusercontent.com/47007/208550083-46df63e3-bbde-4f26-8706-34246181fba3.png)

Trying to load that URL https://media.hachyderm.io/cache/accounts/avatars/109/377/995/751/472/858/original/060a3719fa3404a0.jpg I see this under view source:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>AccessDenied</Code>
	<BucketName>hachystore-1</BucketName>
	<RequestId>tx0000000000001f6711ca5-0063a0f957-5c85f102-fra1b</RequestId>
	<HostId>5c85f102-fra1b-fra1-zg02</HostId>
</Error>
```

### How long have you noticed this issue?

Just now... but I usually use an app, not the website, so I don't know

### What geographic region are you accessing Hachyderm from?

Pennsylvania

**Comment by quintessence** [comment]
A couple of follow up questions:

- Are you seeing the issue with any other avatars or only this account and/or domain?
- Are you only seeing the issue with avatars or also with other media in posts, e.g. custom emojis, uploaded files, etc.

**Comment by durka** [comment]
I think I saw it with another avatar, but I don't have a link, sorry. I'm usually mobile and I do get emoji issues occasionally (where it falls back to displaying :text:) but not sure if it's the same issue.

**Comment by durka** [comment]
Just went scrolling a bit and found another one: https://hachyderm.io/@CrazyMyra@mastodon.social/109538752648901807

Image: https://media.hachyderm.io/cache/accounts/avatars/109/529/224/708/056/693/original/b28ff37378a87011.jpg

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>AccessDenied</Code>
	<BucketName>hachystore-1</BucketName>
	<RequestId>tx0000000000000014a6662-0063a22273-7a82b356-fra1b</RequestId>
	<HostId>7a82b356-fra1b-fra1-zg02</HostId>
</Error>
```

**Comment by quintessence** [comment]
It looks like based on the dates of the two examples you gave that both are overlapping with the date of when we were working on the media issues on the 18/19th. Can you confirm if you see any that are coming through after that? I'm wondering if the servers are just not updating the image data for some reason.

**Comment by durka** [comment]
Is this the same issue?

https://hachyderm.io/@AkaSci@fosstodon.org/109552445214072745

The image overlay shows "not available" and clicking goes through to the original image hosted at Fosstodon. But I don't see any URL pointing to hachystore so maybe this is a separate thing.

**Comment by quintessence** [comment]
Hello!

Apologies for the delay over the holiday. These were aftershocks from the media outage that happened earlier in the month (it had to do with re-caching). Is the issue still happening?

**Comment by durka** [comment]
Haven't noticed anything recently, but I've really only been using the
mobile app. You're probably right about the aftershocks! Happy holidays!

**Comment by quintessence** [comment]
Going to go ahead and close this for now - if it happens again please open a new issue :D Happy Holidays / Happy New Year!
