### ISSUE TITLE
Consider linking rule to a doc site page

### ISSUE THREAD

**Issue by alanwsmith** [hachyderm/community#227]
### Please let us know what you would like to add or change?

> Are you requesting to update or delete sections of existing documentation? 

Yep. 

The [General Accounts](https://community.hachyderm.io/docs/account-types/general-accounts/) page has a link for the rules that points to [the hachyder.io page](https://hachyderm.io/about#rules). My suggestion is to make another copy of rules and put it directly on the community.hachyderm.io site. 

Reasoning:

I clicked on the rules to check them and got confused when I was taking to the mastodon interface. The column that showed the rules wasn't immediately visible. It was all the way to the right and my screen wasn't big enough to show it. My initial thought was that the link was bad. 

(I don't think I've got anything setup that would mess with the page navigation, but will own the fact that I may have done something weird.)

Alternative:

Another solution would be to use a link that shifts over to the column to make it visible. I'm guessing that's not currently possible with the Mastodon software otherwise it would already be setup. But, just in case there's another option, that would be a solid way to go too. Though, my personal preference would be to stay on the community site since I can keep clicking around.

**Comment by quintessence** [comment]
👋 Mod here

Part of that is because we're migrating the original Markdown files to the new docs pages, including [The Rule Explainer](https://github.com/hachyderm/community/tree/main/usage-docs) (which hasn't been migrated yet). :)

**Comment by quintessence** [comment]
Going to close this one as it's being handled as part of the migration :)
