### ISSUE TITLE
Fed feed glitch-scrolling - RESOLVED - PLS CLOSE

### ISSUE THREAD

**Issue by cosmicfire** [hachyderm/community#229]
### What would you like to discuss with us or let us know?

RESOLVED! PLEASE DELETE / CLOSE

UPDATE 12/21 10:38 CST: All the Queues are rejoicing! I still get minor visual glitches on Safari but the scrolling insanity has subsided. THANK YOU!

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Throughout the day, my federated feed kept glitching while scrolling the timeline.

When I'm trying to scroll down it keeps glitching up to the new toots. Glitching = screen images look jumbled while scrolling. When I'm reading a toot & it glitches up, I try to scroll back to what I was reading, but it keeps dragging me back up... you get the idea.  As of right now (9:14pm PST) it's not dragging me up to the latest, but it is flashing/glitching while I'm scrolling. 

IDK if it's my browser, a server-side issue, or just the massive 2nd wave of immigrants fleeing Twitter. Probably that... but I figured I'd give the admins a heads up. 

Just tried on Chrome & Firefox (9:25 PM PST), both seemed smoother (?)

Running a Macbook Air (pre-M) with Ventura 13.1 OS in Safari. 

Thanks, y'all.

**Comment by quintessence** [comment]
👋 Mod here

Thank you for filing / letting us know it resolved! Let us know if it recurs at any point :)
