### ISSUE TITLE
Add dates to incidents in sidebar

### ISSUE THREAD

**Issue by kouhaidev** [hachyderm/community#230]
it'd be neat to see the incident writeups in a chronological timeline! unfortunately, based on what we know of hugo, this is technically infeasible without fiddling around with the theme. (someone's welcome to prove this assertion wrong, of course!)

in lieu of that, would it be possible to adopt a convention of prefixing each incident's `title` (or `linkTitle`) with the relevant date? `linkTitle` does have the downside of changing *all* links, but maybe bracketing the dates will look acceptable in all contexts?

(these incidents are always fun to read :3)

**Comment by quintessence** [comment]
The way that it would work in the Hugo theme is by setting the "weight" to force an order other than alphabetical :) I can take a look and make sure that the posts are set to be in chronological order after the holidays (leaving this ticket open as a reminder).

**Comment by quintessence** [comment]
Verified that posts are appearing in chronological order :)
