### ISSUE TITLE
Would be nice to have state persistence while in a specific stream/feed

### ISSUE THREAD

**Issue by cosmicfire** [hachyderm/community#233]
### What is your suggestion?

Hello. I posted yesterday about weird feed scrolling glitches on Mac/Safari. Here's my related question/suggestion: 

I know that Masto does not have a stateful architecture in general, but would it be possible to anchor the current / open feed to the specific toot that the user is looking at? 'Cause right now when I'm reading a toot (in federated stream, the largest & most active) it keeps pushing me up to newer posts before I'm finished reading or taking any other action. Hard to stay focused and scroll back to where I was in the stream after being shoved up several entries to the top of newer toots. Persistence in the thread, based on where you started, would be super helpful, thank you!!!

**Comment by quintessence** [comment]
Mastodon actually has a checkbox to limit this behavior in your Profile Settings:

<img width="873" alt="Screen Shot 2022-12-23 at 14 02 15" src="https://user-images.githubusercontent.com/3387286/209409173-b908e95a-fcbe-4bad-a49e-47cddfd5ddd0.png">

So with this enabled you need to manually refresh / click to refresh the timeline :)

**Comment by cosmicfire** [comment]
Fantastic! Thank you!

**Comment by quintessence** [comment]
You're welcome!
