### ISSUE TITLE
Posts of other account not available 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#234]
### What is your question?

I‘m following an account on another server (@fofrAI@sigmoid.social). I can see that this account posted once, but I can’t see that post when I access that account via hachyderm. When I access the account via webinterface directly on sigmoid.social I can see the post.

I assume, that this is not an error, but I’d like to understand the behavior. Do I only see on hachyderm the posts they made after I followed them?

**Comment by ineffyble** [comment]
You'll only see the posts they made after _someone_ on Hachyderm started following them.

Up until that point, their server had no reason to send those posts to Hachyderm.

**Comment by quintessence** [comment]
ineffyble is correct - and this reminds me I should add this to a "Federation Intro" post to help with some confusion around the way the mechanics work. (I've added this to my notes to do so.)
