### ISSUE TITLE
Increase character limit for profile name

### ISSUE THREAD

**Issue by nigelpoulton** [hachyderm/community#235]
### What would you like to discuss with us or let us know?

I wanted to use an emoji in my profile name. However, due to the length of emoji names (e.g. `WebAssembly_Logo:` and `:shipping_container:` I'm exceeding the number of characters in my profile name.

It's not as simple as shortening emoji names as I agree they should be descriptive for screen readers etc.

**Comment by quintessence** [comment]
👋 Mod here

A cursory search showed there _might_ be inconsistent behaviors with the instances federating with us as they won't be expecting more than 30 characters. It's something we'd definitely need to test before rolling out.

**Comment by quintessence** [comment]
I actually put this on an internal tracker and neglected to close this - apologies :)
