### ISSUE TITLE
Visible posts when following hashtag

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#237]
### What is your question?

I‘d like to know, which posts I see on hachyderm, when I follow a hashtag. Are these only posts of accounts which anybody follows on hachyderm or all posts which used that hashtag?

**Comment by quintessence** [comment]
👋 Mod here

When you are viewing a hashtag it is a combination of the Local and Federated feed. That means you should see local users, anyone you're following, and anyone that is pulled into the Federated feed that used the hashtag :)

**Comment by blueturtleai** [comment]
Okay, thanks! Two question about federated feed:

1. Is this explanation what a federated feed is correct? „The federated feed shows all the public posts by all the accounts that people on your home instance follow, including accounts on other instances.“
2. Is it correct, that I can’t see the federated feed in the standard Mastodon iOS app?

**Comment by quintessence** [comment]
We're still migrating some of the docs we're writing about Mastodon, but a quick description for what you can see via Federated feed is on the infographic on our welcome Markdown page (this will be on our Community docs later):

https://github.com/hachyderm/community/tree/main/welcome

As for the Mastodon iOS app / deeper Mastodon-specific questions you'll need to ask the Mastodon team themselves over at:

https://github.com/mastodon/mastodon

Either via the Issues or Discussions (not sure which they'd prefer for this but they do have both set up).

**Comment by blueturtleai** [comment]
Thanks! So, visibility of hashtag posts works like I expected.
