### ISSUE TITLE
CORS error when trying to play audio hosted on media.hachyderm.io

### ISSUE THREAD

**Issue by tvandervossen** [hachyderm/community#238]
### What would you like to discuss with us or let us know?

After adding an MP3 (https://hachyderm.io/@tvdv/109574002737602560), I noticed that both Safari and Chrome refuse to load the media from media.hachyderm.io because the main hachyderm.io domain is not allowed by its Access-Control-Allow-Origin headers.

<img width="1470" alt="Screenshot 2022-12-25 at 12 11 50" src="https://user-images.githubusercontent.com/4490/209465891-ac62f276-afa5-4e9a-83da-299494fbfb41.png">
<img width="1361" alt="Screenshot 2022-12-25 at 12 12 52" src="https://user-images.githubusercontent.com/4490/209465894-339ae631-a271-4b42-8268-de31ceeb2539.png">

**Comment by quintessence** [comment]
👋 Mod here - we'll prioritize looking at this after Christmas (today) to see what we can do so the maintainers can rest and recover :) I will make sure we have it in our internal channel though.

**Comment by jamagin** [comment]
Oh, looks like it happens reliably, saw the same viewing https://hachyderm.io/@renice/109615741917632913

**Comment by dmah42** [comment]
https://docs.joinmastodon.org/admin/config/#cdn_host might be relevant, as is https://docs.joinmastodon.org/admin/config/#s3_alias_host

"You must serve the files with CORS headers, otherwise some functions of Mastodon’s web UI will not work. For example, Access-Control-Allow-Origin: *"

**Comment by dmah42** [comment]
https://docs.digitalocean.com/products/spaces/how-to/configure-cors/ is the other half of the equation i think.

**Comment by e-nomem** [comment]
We've updated the configuration in all of our edge nodes to include the appropriate CORS headers so this issue should be resolved now. I'm going to close this out but if you continue to observe any issues please open a new ticket to let us know.

Thanks for you're patience!
