### ISSUE TITLE
Automatic toot language translation (e.g. using DeepL)

### ISSUE THREAD

**Issue by CommanderMoto** [hachyderm/community#241]
We can look into DeepL thank you! Going to close this one for now [...]
_Originally posted by @quintessence in https://github.com/hachyderm/community/issues/36#issuecomment-1328331691_
      
------------------------------------

So, I hear there's a Mastodon 4.0 feature which allows an instance admin to set up this machine-driven "Translate" button: https://github.com/mastodon/mastodon/issues/21665

This sounds awesome, and I would love to see this feature on hachyderm! I also understand it's likely a non-trivial implementation on an instance of tens of thousands of users. Rather than just piling into Discord as a new user and making demands, I figured I'd try the software dev's way: passive-aggressively creating a github issue first ;-)

**Comment by quintessence** [comment]
👋 Mod here 

Also: 😂 

It is in our queue - we had a few things to handle first between the holidays (and the SSL certs as well). ❤️

**Comment by dmah42** [comment]
how to (untested): https://write.as/sweetmeat/how-to-activate-the-mastodon-v4-deepl-api-text-translation-service

**Comment by martinjuhasz** [comment]
https://github.com/mastodon/mastodon/pull/19218

**Comment by t-lo** [comment]
Hello hachyderm friends, fellow admin of a micro-instance here. I've added LibreTranslate to fromm.social a while ago and captured my experience in a brief thread: https://fromm.social/@thilo/109416083145670324

LibreTranslate can be self-hosted, so it has the advantage of not sending user data to a 3rd party service. Hope this helps!

**Comment by quintessence** [comment]
Put on our internal tracker, closing for now :)
