### ISSUE TITLE
Please add option to warn before posting or boosting media lacking alt-text 

### ISSUE THREAD

**Issue by drazisil** [hachyderm/community#242]
### What is your suggestion?

This is a feature provided by glitch-soc #3 , that I really like.

Especially on mobile where it's extra hard to tell if there is alt-text. I try to make an effort to not boost content lacking it, and having this optional warning would be very helpful.

**Comment by quintessence** [comment]
Evaluating glitch-soc is on our post holiday ToDo! I put this issue in there with the others we're looking at while checking it out. :heart:

**Comment by dmah42** [comment]
is there a way to link glitch-soc-related issues together under an umbrella? maybe a Project or something?

**Comment by drazisil** [comment]
I'd use a Label. Projects are ... something :D

**Comment by quintessence** [comment]
@dmah42 there are a couple of glitch-soc feature requests, we can group them with the `glitch-soc` label (I just made) :)

**Comment by quintessence** [comment]
This was added to our tracking for glitch-soc, closing :)
