### ISSUE TITLE
Consider block of anonymous-following-service mastinator.com

### ISSUE THREAD

**Issue by wlonkly** [hachyderm/community#243]
tl;dr mastinator.com allows anonymous following of followers-only posts and bypasses blocking.

[Quoth @msh@coales.co](https://coales.co/@msh/109595980918905804):

> PSA to all admins: I highly recommend a [#FediBlock](https://coales.co/tags/FediBlock) of [#mastinator](https://coales.co/tags/mastinator) (ie. the entire mastinator.com domain).
>
> Mastinator is a service that allows a person to anonymously follow people on the fediverse. No big deal you think? Your public posts are probably already anonymously viewable from your public profile anyways and all it is doing is aggregating public info? That is what its creator claims---it is just a convenience service!
>
> Well no, it is mode concerning than that. It does this aggregation by following any account a mastinator user types into its service then replicating *all* your non-DM posts into a sort of "proxy inbox" in the mastinator.com domain that is completely out of your control and viewable by everyone!
>
> In other words, if you are followed by mastinator.com it effectively turns your follower-only posts into public posts and lets people you have blocked keep following you by following the mastinator replica of your posts!
>
> Innocent intentions or not this violates user consent.

And unfortunately the creator is [unwilling to listen to the community](https://boyter.org/posts/mastinator-activitypub-breaking-assumptions/), too, but of _course_ he is.

**Comment by quintessence** [comment]
👋 Hello!

This domain is already blocked (someone filed in the Admin UI). Thank you for filing this report! :)
