### ISSUE TITLE
mis-cached profile picture from another instance

### ISSUE THREAD

**Issue by tupsut** [hachyderm/community#246]
### What would you like to discuss with us or let us know?

I've noticed that the profile picture of an user I'm following never shows up fully - only around 30% of the image is visible, with the rest being "not loaded in", i.e. transparent. The user does have a full profile picture appear on their home instance.

User's cached profile on Hachyderm: https://hachyderm.io/@im@mastodon.scot
User's profile picture as cached on Hachyderm: https://media.hachyderm.io/cache/accounts/avatars/109/302/259/414/757/871/original/45b3ad2db6403498.jpg

User's profile on his home instance: https://mastodon.scot/@im
User's profile picture on his home instance: https://media.mastodon.scot/mastodon-scot-public/accounts/avatars/109/302/243/551/374/155/original/312f658f3683e646.jpg

It looks to me like the original request timed out and the cache didn't realise the full image was never downloaded. I would guess that the issue is fixed just by forcibly updating the cached version or deleting the cached image and having it re-cache, but if there's a way to force a re-cache myself, I at least haven't found it.

Same issue does persist in the Tusky app and across all of the devices that I own, so I'm pretty sure this isn't just my browser's cache doing something weird.

**Comment by quintessence** [comment]
👋 Mod here - I've passed this along to our infra people for when they get back from holiday next week or so :)

**Comment by dmah42** [comment]
running `tootctl accounts refresh --domain=mastodon.scot im`

**Comment by dmah42** [comment]
i'm getting 404 and timeouts for URLs like https://media.mastodon.scot/mastodon-scot-public/accounts/avatars/109/275/134/446/985/018/original/3f386e093815f797.jpg

**Comment by dmah42** [comment]
it's still running, but the user's profile page on hachyderm is now showing the complete profile picture.
