### ISSUE TITLE
Mastodon Mobile App Login Failure - Blocking Cookies?

### ISSUE THREAD

**Issue by ntrav** [hachyderm/community#247]
### What would you like to discuss with us or let us know?

When I attempt to use the official Mastodon app to login to Hachyderm, I'm prompted to enter my email and password in a web portal that the app brings up. When I enter those fields (correctly) I get an error message stating that login has failed and asking if I'm blocking cookies.

I'm not sure how to whitelist Hachyderm or even which web browser the Mastodon app is attempting to use as the web portal. I would like to access Hachyderm via mobile but am at a loss. Can someone help me figure this out?

**Comment by quintessence** [comment]
👋 Mod here:

What we'd need to figure out is if the issue is confined to the Mastodon app or not (if so, it'd need to be filed with the app). Please let us know the results of the following:

- Can you log in normally via the web UI?
- Can you log in normally using any other iOS client?

**Comment by ntrav** [comment]
1. I can login via the web UI (my web browser is Brave)
2. I can login via the mobile Chrome app, though my iPhone (so iOS) default's browser is DuckDuckGo

**Comment by dmah42** [comment]
to confirm: you see this issue when using the Mastodon app on your iPhone where the default browser is DuckDuckGo?

* can you try an alternative Mastodon mobile app?
* can you try setting the default browser to Chrome (temporarily) and attempt to log in using the official app?

**Comment by ntrav** [comment]
1. I tried downloading and logging in via Toot and received the same message. After that attempted failed I cancelled the login screen popup that came up in the app, and the app displayed an error message that reads:
`The operation couldn't be completed. (come.apple.AuthenticateServices.WebAuthenticationSession error 1.`

2. I switched to Chrome as the default browser for both the official app and Toot, and both verification attempts failed.

**Comment by ntrav** [comment]
I also checked and I had my Settings configured to not allow apps to request to track. I enabled that permission (so they can request to track) and tried logging in via the official app. It still failed with the same message.

**Comment by eklipse2k8** [comment]
I am also experiencing this. I cannot log in to hackyderm.io via the official Mastodon iOS app or the new Ivory iOS app.

**Comment by Preskton** [comment]
Hi, @eklipse2k8 -- are you using hachyderm.io or hackyderm.io? Generally, you'll interact with hachyderm.io, so just wanted to be sure.

**Comment by Preskton** [comment]
> I also checked and I had my Settings configured to not allow apps to request to track. I enabled that permission (so they can request to track) and tried logging in via the official app. It still failed with the same message.

@ntrav, I know it's been a bit, but are you still seeing this behavior?

**Comment by jasonpeterson** [comment]
Hi. I am experiencing this same issue. I am using iOS 26 and Safari. I get the “security verification failed. Are you blocking cookies?”

I can log into the website in safari. I also tried turning off content blockers. 

I vaguely remember a setting in safari to block third party cookies but I don’t see that as an option anymore?
