### ISSUE TITLE
Please increase FALLOFF setting

### ISSUE THREAD

**Issue by lak** [hachyderm/community#251]
### What is your suggestion?

As described in [this thread](https://woodland.cafe/@untitaker/109599324562934187), there is apparently a variable in Mastodon that can be used to reduce the number of duplicate posts we see in our timeline as a result of boosts. It must be set at the admin level

I assume there's some performance cost for increasing this, but the default (40) seems uselessly low. It would be nice to get this increased. The thread recommends 400 instead of 40.

There's a [github issue](https://github.com/mastodon/mastodon/issues/18693) about making the variable user-configurable, but not obvious sign it's going to change. I was hoping to find discussion of possible downsides.

I have researched this a reasonable amount, but am not really able to learn more. It appears this might be set at compile time rather than config time for the service? I honestly can't tell. I am hoping the admins can figure it out easily.

I will not be miffed in the slightest if you close as willnotfix, given it might involve compile-time settings. But I figured I'd ask. :)

Thanks.

**Comment by dmah42** [comment]
the variable is `REBLOG_FALLOFF` and it's set in `app/lib/feed_manager.rb`.  the upper bound is `MAX_ITEMS` which is set in the same class and is default `400`.

if it is increased, the cost is going to be in the size of a set stored in redis.  the relevant function is [zrevrank](https://redis.io/commands/zrevrank/) which has `O(log(N))` performance so a 10x increase in set size (worst case) would be a relatively small decrease in performance.

the maintenance cost is trickier as we would have to maintain this patch through every release we do going forward.  _if_ we stored our own fork of mastodon _then_ it would be easier to maintain these patches.  similarly, _if_ we had an image that we used for server provisioning _then_ it would be easier to maintain (similar to a fork).

we have neither.

**Comment by justbaileym** [comment]
Is it worth having a separate issue to discuss options around forking and dealing with the maintenance of the fork and figuring out which patches would be accepted, maintained, upstreamed, removed?

**Comment by dmah42** [comment]
i think that's the linked infrastructure issue above.  we're collecting examples of issues there that would require or suggest a fork/upstream change.  that's where the discussion of the impact of a fork would happen, and the trade-offs against feature benefits.

**Comment by Preskton** [comment]
Howdy, folks - we are tracking these types of requests against the issue @quintessence and @dmah42 linked.

At current, we aren't planning on running our own fork/patched instance because we're a small volunteer team. We're focused on general system resilience and the "image we use for server provisioning" that dma mentioned above.

@lak, thank you for submitting the original issue - I am going to close it for now, but we still have it on our tracking list.
