### ISSUE TITLE
Verified Bisexual Emoji

### ISSUE THREAD

**Issue by tedivm** [hachyderm/community#254]
### So what emoji are you looking for?

I'd love to see a "Verified Bi" emoji-

![verifiedBi](https://user-images.githubusercontent.com/121709/210678574-f5be2d0c-66d5-4bbb-a79e-d58b6c114d03.png)

Bonus Bi Pride Cat Emoji - https://www.emojipng.com/preview/8717784

Thank you!

**Comment by quintessence** [comment]
Done!

**Comment by tedivm** [comment]
Thank you!
