### ISSUE TITLE
Original posts not appearing in Profile

### ISSUE THREAD

**Issue by gnarlygeek** [hachyderm/community#255]
None of my original posts are appearing in my Profile. They're not under Posts nor Posts and Replies. I see only those were I have replied or boosted, but not any Posts that I initiated myself.

I did search the issues and didn't see anything relevant.

@gnarlygeek@hachyderm.io

**Comment by anubhav-x61** [comment]
I have the issues of OP not appearing in "Home" feed/timeline in the web client. I can find them on "Profile" (```@anubhav```) or by going through the reply-chain.

"Missing" post: https://hachyderm.io/@anubhav/109604281245516289

OTOH, the post does appear as expected in "Mastodon" iOS application in "Home"feed.

Images- 
- In "missing-toot-web-client", image the "missing" toot should exist between mine & the one by ```@ltning@anduin.net```.

- In "toot-where-expected-1", top portion of the toot (missing from the web client) is displayed below the one with ```#mastodon_UX``` tag; bottom portion of the toot is shown in "toot-where-expected-2" image, above the one by ```@ltning```.


![missing-toot-web-client](https://user-images.githubusercontent.com/92665218/211170111-beabd485-4287-4b13-98f4-80b6cd9c0dc4.png)

![toot-where-expected-1](https://user-images.githubusercontent.com/92665218/211170170-73723c6e-f48a-4130-bcb6-709b03117dbe.PNG)
![toot-where-expected-2](https://user-images.githubusercontent.com/92665218/211170171-7ebfc34e-bfca-4033-8133-8f1bab02c4ed.PNG)

**Comment by Preskton** [comment]
Hi, @gnarlygeek -- I know it's been a bit since you've opened this issue, but are you still seeing this behavior? Could you please link/screenshot any occurrences you've seen recently?

**Comment by dmah42** [comment]
i'm going to optimistically close this then.  thanks so much for following up.
