### ISSUE TITLE
Mod Report: Too Many Requests / Rate Limiting

### ISSUE THREAD

**Issue by quintessence** [hachyderm/community#259]
### Please describe the issue you are seeing.

Seeing Rate Limiting errors on and off in the web UI (screenshot) . Screenshot is with the Brave browser, but is happens on different browsers and different machines in the house.

### How long have you noticed this issue?

About a week

### What geographic region are you accessing Hachyderm from?

United States

### Is there anything else that we should know?

:: blobfox emoji ::

<img width="1359" alt="Screen Shot 2023-01-07 at 21 04" src="https://user-images.githubusercontent.com/3387286/211181420-da4b8a26-eeaf-4acf-923f-cf24b8843fc5.png">

**Comment by quintessence** [comment]
No other reports of this - closing for now

**Comment by cvennevik** [comment]
I've experienced the same issue now for the last week, usually one or more times a day, lasting until the given time to wait for. It has started while browsing the main timeline and while composing messages.

Norway, Firefox 121 for Android.

![Screenshot_20231230-074001](https://github.com/hachyderm/community/assets/90956290/6eea7605-2b6d-4cd8-af14-b71107a1c9a7)

**Comment by hachyderm-admin** [comment]
Hello! Can you please open a new issue for this?
