### ISSUE TITLE
Introduce CLA and License Audit

### ISSUE THREAD

**Issue by quintessence** [hachyderm/community#260]
### What would you like to discuss with us or let us know?

Integrate CLA bot and roll out legal / licensing from our attorney.

(To be handled by @krisnova )

**Comment by hachyderm-admin** [comment]
Writing a test comment with this account

**Comment by jonm** [comment]
The [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license) have a default “inbound = outbound” for contributions to a public repository; i.e. in the absence of a CLA, contributions to a repository are made under the license of that repository, which is what most open source projects basically want.

IANAL, but it seems plausible that’s enough not to require additional CLA signing if the right core license is chosen. Mostly just wanted to make sure you and your lawyer knew about it. :)

**Comment by quintessence** [comment]
We do - thank you!

**Comment by quintessence** [comment]
This is now complete 😎
