### ISSUE TITLE
Hachyderm Community Resources Website requires SSH to be configured in GitHub to build docsy submodule

### ISSUE THREAD

**Issue by aowendev** [hachyderm/community#261]
### Please let us know what you would like to add or change?

To help you get started:
1. Are you requesting documentation that doesn't exist yet and what questions need to be addressed?
2. Are you requesting to update or delete sections of existing documentation? If so, please provide
   the URL as part of your description.

**Comment by aowendev** [comment]
`make submodule`

response:

```
git submodule update --init --recursive
Cloning into '/Users/aowen/Development/community/community.hachyderm.io/themes/docsy'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Requires an SSH key to be configured on GitHub. Probably obvious to most devs, but perhaps worth a note in the README.md?

**Comment by quintessence** [comment]
We'll put an update / clarification in there, thank you! Leaving this open for now as we get ready to roll out or license / CLA to limit the number of additional edits in advance :)

**Comment by quintessence** [comment]
Forgot to close when updated the Community site README :)
