### ISSUE TITLE
Warnings for images posted without alt text

### ISSUE THREAD

**Issue by LauraLangdon** [hachyderm/community#262]
### What is your suggestion?

Hi! I understand from [this post](https://post.lurk.org/@acousticmirror/109647355042311032) that the Hometown fork has enabled a feature that puts a warning on images posted without alt text, and I wonder if that's something that might be appropriate to build into Hachyderm sometime? Or maybe because Hachyderm is Mastodon—not Hometown—it would require a CSS change? Either way, I'd love for this be considered whenever there's time. 😊

Cheers!

**Comment by quintessence** [comment]
Closing this and moving to our tracking for Glitch-Soc
