### ISSUE TITLE
Consider suspension of soc.ua-fediland.de follow spam

### ISSUE THREAD

**Issue by bencurrandev** [hachyderm/community#268]
### What domain(s) need to be added or removed from our blocklist?

soc.ua-fediland.de As in the last hour I have had 6 random accounts from there follow me with no posts but high follow counts. This seems like malicious behaviour across the instance.

**Comment by quintessence** [comment]
Thank you for the report! After looking into it, it seems this one is a Ukrainian server that is getting maliciously overrun by bots. We're going to limit them for now and can review if there are issues that persist.
