### ISSUE TITLE
Updated Azure logo emoji

### ISSUE THREAD

**Issue by bencurrandev** [hachyderm/community#271]
### So what emoji are you looking for?

Could we update the :azure_logo: to be the current fluent blue A logo? It’s currently the old Windows Cloud logo and which has been replaced a few years ago.

**Comment by bencurrandev** [comment]
![Azure](https://user-images.githubusercontent.com/75711425/214989319-5bf87303-a67b-4642-848f-f6671ba54a16.png)
Added better transparent PNG version of image, did not work from mobile for original post.

**Comment by quintessence** [comment]
Updated!
