### ISSUE TITLE
Relay with Universeodon.com

### ISSUE THREAD

**Issue by supernovae** [hachyderm/community#274]
### What would you like to discuss with us or let us know?

I've set up a relay at https://relay.universeodon.com/inbox and would like to invite Hachyderm to join.  Happy to add you to the allow list if you're interested.

Thank you! ❤️

**Comment by quintessence** [comment]
Hello! Apologies I thought I had answered this back when you posted: the main thing I remember researching at the time was trying to see if we'd incur a risk from firehosing the content. So if we have an instance that's not mutually blocked / etc. on our two instances, would the relay basically re-create the "quote boost" problem where people who were blocked on the source instance can now see a post they wouldn't've without the relay? if that's not the case, then please feel free :)
