### ISSUE TITLE
Full outage

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#275]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

### How long have you noticed this issue?

10 minutes

### What geographic region are you accessing Hachyderm from?

US south central (Dallas TX)

### Is there anything else that we should know?

Status dashboard and Discord bot show full outage status.

**Comment by brorhb** [comment]
Unable to access hachyderm as well. Trying to access from Norway

**Comment by blueturtleai** [comment]
Same. 

@mjf-pro which status page do you use? I’m using this one which doesn’t load either https://grafana.hachyderm.io/

**Comment by mjfisher-bbllp** [comment]
https://status.hachyderm.io

**Comment by blueturtleai** [comment]
Seems to work again

**Comment by mjfisher-bbllp** [comment]
Fixed!  #HugOps
