### ISSUE TITLE
Not receiving email confirmation.

### ISSUE THREAD

**Issue by davidmoore512** [hachyderm/community#277]
Hi,

I signed up for an account on hachyderm but I am not receiving the confirmation email.

I have triple checked that my email address is correct in the account and checked my spam folder.

My email address ends in .cc 

Is there a way you can check if it's being blocked from actually being sent from the server?

**Comment by quintessence** [comment]
👋 Apologies for delay - I was wondering if you are still experiencing this issue?

**Comment by davidmoore512** [comment]
Hello, 

Thanks for your time. I was able to change my email address to a gmail address instead and get it confirmed. But I have been trying to change the email to my actual email that ends in .cc and I am not getting any errors but it just doesnt change.

**Comment by Preskton** [comment]
@davidmoore512 could you please share the domain you're using to try to register? This would help us track logs or identify any configuration-related items that might be in play here.

**Comment by davidmoore512** [comment]
Yes. The domain is mooremail.cc

**Comment by Preskton** [comment]
Howdy, @davidmoore512 - apologies for the late response. Unfortunately, I tried searching our logs for mentions of failures/issues sending email to your domain, but had no luck -- possibly because the logs had expired/rotated out. If you wanted to try again, I'd be happy to look at fresh logs.

**Comment by Preskton** [comment]
Closing this as `won't fix` but please feel free to reopen if you want to try it again.
