### ISSUE TITLE
hachyderm seems to be down 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#279]
### Please describe the issue you are seeing.

Just no response, no error. Checked grafana. CPU of fritz is at 100%.

### How long have you noticed this issue?

15 min

### What geographic region are you accessing Hachyderm from?

West Europe

**Comment by blueturtleai** [comment]
![389A55C0-69AE-478B-A93D-D5ECA8140818](https://user-images.githubusercontent.com/113246030/216823569-0707cc58-9d23-427b-a17b-471f46084af8.jpeg)

**Comment by arjunrbery** [comment]
hello hachydermians!

if you are experiencing any slowdown on the site, please excuse us.  [@krisnova](https://hachyderm.io/@krisnova) decided to ask [#FOSDEM23](https://hachyderm.io/tags/FOSDEM23) to DoS our service and the audience have taken the challenge.

we should recover shortly.

[https://fosdem.org/2023/schedule/event](https://fosdem.org/2023/schedule/event/hachyderm/)

**Comment by blueturtleai** [comment]
Okay. DoS successful 😀.

**Comment by blueturtleai** [comment]
DoS test seems to be over and everything goes back to normal.
