### ISSUE TITLE
Please update Fedora logo

### ISSUE THREAD

**Issue by mattdm** [hachyderm/community#280]
### So what emoji are you looking for?

Please update `:fedora_logo:`  to this:

![fedora-logo-sprite](https://user-images.githubusercontent.com/123367/216840367-d7935e93-584d-4e42-8be3-f94c423705cb.svg)

Perhaps what is currently there could be made `:fedora_classic_logo:`?

Thank you!

**Comment by quintessence** [comment]
Any way you can convert this to a PNG? I don't have something to read the SVG file :)

**Comment by quintessence** [comment]
Actually I was able to copy one in - this is set :)
