### ISSUE TITLE
Call For Volunteers

### ISSUE THREAD

**Issue by mikeblum** [hachyderm/community#281]
### What is your suggestion?

Hi @quintessence,

@dma sent me your way. I was wondering if there is still a need for infra volunteers or has the need been met? 

I noticed the interest form is closed otherwise:

 https://discord.com/channels/858148454953254943/1042272843175567361/1049783450070175744

Sorry if @ing isn't proper protocol 🥺

**Comment by quintessence** [comment]
Ah apologies I thought I had hit "send" on this the other day but apparently only answered in my brain. :)

The formal Call for Volunteers _is_ closed while we review the applicants in there. We're only accepting some right now, as we have more volunteers than space for volunteers (a good problem to have). That said: we are keeping the applicants stored to keep reaching out as our needs grow, so letting us know of your intent / want to volunteer is great.

If you'd like to switch to email we can discuss and I can add you to the Volunteer Applicant list.  :) My email is just my Hachyderm handle, domain and all.
