### ISSUE TITLE
Hachyderm loads very slow

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#283]
### Please describe the issue you are seeing.

All posts and images are loading very slow. 
![9A638746-EDAA-4076-96DC-E3ABB5BC9BD0](https://user-images.githubusercontent.com/113246030/217068279-7f5e9f15-a2fb-4285-bfd9-7ccfae513a91.jpeg)

### How long have you noticed this issue?

15 min

### What geographic region are you accessing Hachyderm from?

West Europe

**Comment by freiheit** [comment]
Looks like issue resolved about half an hour ago
![image](https://user-images.githubusercontent.com/19813/217096747-fc77324a-604a-4b26-82bc-c3b1208c878a.png)

Looks like over an hour of service degradation, so I've tagged this to @hachyderm-infra team in case they want to investigate further.

**Comment by lauravarga** [comment]
We an initial investigation on the issue reported here and it aligns with the time when a member of the infra team stopped one of our CDN servers, believing that it's not in use. The team noticed immediately and the server was turned back on. 
The performance degradation described here is in line with what we would expect when one of the active CND nodes becomes unavailable and the timeline aligns.
We plan to look into how to make this type of scenario less likely in the future.
