### ISSUE TITLE
Specialized Accounts: Tailscale

### ISSUE THREAD

**Issue by jeremytanner** [hachyderm/community#289]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

We want to be an example of what a positive and mutually beneficial corporate presence on the Fediverse should look like. 

We agree to the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant)

### How will you ensure the community is protected?

We agree to follow the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant)

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A (no automated posts)

**Comment by quintessence** [comment]
Account added to approval list :D
