### ISSUE TITLE
Convert to Trade Association / Governance Model

### ISSUE THREAD

**Issue by krisnova** [hachyderm/community#29]
The more I work on the Hachyderm community documentation and ponder the possibilities of the fediverse the more I have to stop and ask myself, why not just form a 501(c)6 trade association and become another viable non-profit in the space?

We are very close to forming what resembles a social-media first governance policy? Why not take it to the next level and also include open source software (Maybe Aurae can be our flagship?) and community building in the same place?

Operating as a formal governing body with Hachyderm as our "sun" would flip the relationship with social media around and move to a de-centralized governing (and potentially funding) model for open source projects around the globe?

This is a huge topic but figured I would get it out there for folks to begin pondering.

**Comment by justinabrahms** [comment]
What are the benefits of being a trade organization? Would other governance models (like a co-op) be a better fit?

**Comment by BlueHatbRit** [comment]
Intriguing idea for sure, especially when related to pulling in OSS projects. I'm curious what you'd see as the likely life cycle of an OSS that comes completely out of this sort of association? How are they likely to start, come together, and what would they hold in common (licenses, CoC, governance structure)?

On the 501(c)6 trade association bit in particular, would there be any pitfalls for non US individuals getting involved at different levels of the association? I must admit being from the UK I have very little understanding of that structure in particular and while I'm sure it accomodates non-US members and leadership, I wonder if there's anything that would become difficult. Could non US residents sit in official leadership positions recognised legally as part of the association?

Generally I think it's an interesting idea and could unlock some new avenues. Would like to hear more in general about your vision for it to help inform a well rounded opinion though!

**Comment by mxplusb** [comment]
A 501c6 license also means there will need to be formalized compliance, accounting, and other aspects of maintaining the formal organization. There are already dozens of different individual-focused 501s that focus on different aspects, and then you have the LF overlord. Aside from being able to say hachyderm is a 501c6, what are the tangible benefits that make the formal organization overhead valuable enough to pursue it?

**Comment by helmingstay** [comment]
Random user with keen interest in federal tax code here. I just did some light research and I admit I'm a bit unclear on the tax benefits (IANAL and have zero understanding of legal implications here). Thinking into the future, some obvious models include LLC, 501.c3, and 501.c6. In the case of employee pay, I don't see any tax differences between these if nothing comes out as "profit". And most donations to 501.c6 are not deductible (whereas 501.c3 comes with a lot of restrictions). Am I missing anything re tax exempt *income* (not wages)?

Two places official designation could matter:
* 501.c6 member fees are deductible as business expenses 
  - options include solicitation of member fees from for-profits for services, e.g. community outreach, jobs board, technical advice, OSS advocacy, lobbying, training.
  - Implement member standards/compliance and offer official Hachyderm "We're Not Dicks" seal of approval (only half-joking)
* Grants. Per OP, "de-centralized governing (and potentially funding) model for open source projects around the globe"

@mxplusb In some sense I see compliance and accounting as a net positive for long-term stability (discounting for a moment the setup cost).

Some refs:
* LLC income tax: https://www.nerdwallet.com/article/small-business/small-business-llc-taxes
* Nice 501.c6 primer, permitted activities & tax consequences: https://donorbox.org/nonprofit-blog/501c3-vs-501c6
* IRS 501.c6 megapage / HOWTO: https://www.irs.gov/charities-non-profits/other-non-profits/life-cycle-of-a-business-league-trade-association

**Comment by krisnova** [comment]
Updating the issue: No decisions have been made yet, however I am considering all socioeconomical, tax, sustainability, profit, well being of me, my life's work with open source, sustainability of our family, sustainability of hachyderm, the broader impact on our species, our children, and our planet in my decision.

I will relay more information as I come to conviction. My intention is to have this settled by January 2023.

**Comment by justinabrahms** [comment]
https://wiki.sunbeam.city/doku.php?id=governance_policy - Sharing this governing policy. I think it's a fantastic idea of a sustaining mechanism for projects like this. I was a dues paying member for a while (maybe still am?)

**Comment by quintessence** [comment]
We're approaching the final stages for this - closing. Please keep an eye on [nivenly.org](https://nivenly.org) for updates.
