### ISSUE TITLE
Specialized Accounts: @ConfBuddy

### ISSUE THREAD

**Issue by programmiri** [hachyderm/community#296]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Conference Buddy is a private project that I started in 2018 and do in my free time. It wants to provide a platform where people that are uncomfortable going to a conference alone can connect to other people. 

- [website](http://conferencebuddy.io/)
- [twitter](https://twitter.com/confbuddy)
- [github](https://github.com/conference-buddy)

Conference Buddy "works" mostly through social networks (people find each other through the hashtag #ConfBuddy) at the moment. 

### How will you ensure the community is protected?
I agree to follow the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant/) 

That means for example:
- I promise that with Conference Buddy I want to create and foster a community of people that help support each other (and others!) to have a more welcoming experience at tech events (mainly conferences). 
- I also want to share awareness on how we as tech community can make others feel more welcome and included in our communities. 
- Conference Buddy will not be used for marketing purpose outside of this idea. E.g. I won't advertise random conferences other than the ones where an active effort to "establish" a Conference Buddy program is happening. Which means: people are looking for Conference Buddies for the event OR the organisers will have Conference Buddy at the venue, which means it's agreed upon and planned together with me & their orga team (which at the moment mostly means I'm at the event with a booth 😅 ) 

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

I don't use bot accounts. Currently, there is no plan to do automated posting. Dependent on how Conference Buddy develops, I may want to add a kind of automation in a way where people can share posts directly to through Mastodon, but in that case I would check in with the admin team first to see how that could be done in a good way.

**Comment by quintessence** [comment]
Excellent! Thank you for going through our process to be a verified OSS project on Hachyderm :tada: 

For "how will you ensure the community is protected": we're asking this question around the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant/). Essentially, an acknowledgement that you'll uphold the expectations there in perhaps a sentence or two. An example for the "Posting Automation" one might be "I'll verify my autoposting tool does not post more than 5 posts per day". An example for the Expectations could be something like "I promise to foster genuine engagement with the community and not use Hachyderm for purely marketing purposes" (if marketing applies). Examples of two of our accounts that have great community engagement are: [Oxide Computer Company](https://hachyderm.io/@oxidecomputer) and [TailScale](https://hachyderm.io/@tailscale), to see what we're looking for with that example.

Once we have this, I'll go ahead and add you to the Approved page and go to the next steps in the process :)

**Comment by programmiri** [comment]
Hi @quintessence thanks for clarifying! 

I'll edit my first post so it's all together!

**Comment by quintessence** [comment]
Awesome! Your Hachyderm account has been added to the Approved list for you to link in your profile to show "APPROVED". Once that's successful, please close the ticket. If there are issues, please let us know here. :)

**Comment by freiheit** [comment]
@programmiri Specifically, please add a link to https://community.hachyderm.io/approved/ on the https://hachyderm.io/@ConfBuddy profile (and update us when that's done and shows a green checkmark)

**Comment by programmiri** [comment]
@quintessence @freiheit  done! Let me know if there's something missing, but I think (hope!) I've got everything now. 

Thanks so much for your fast replies, I really appreciate you taking the time ❤️

**Comment by quintessence** [comment]
You got it @programmiri ! I'll close the ticket :)
