### ISSUE TITLE
Specialized Accounts: coveragepy

### ISSUE THREAD

**Issue by nedbat** [hachyderm/community#299]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

I'm @nedbat@hachyderm.io.  I solo-maintain https://github.com/nedbat/coveragepy.  I've used a Twitter account to speak as the project: https://twitter.com/coveragepy/

Coverage.py is a developer's tool, the code coverage tool for Python.  It meets all of the criteria of the Open Source Projects for hachyderm.io: https://github.com/hachyderm/community/blob/main/accounts/open-source-accounts.md

### How will you ensure the community is protected?

I post as coveragepy infrequently, generally:
- to announce new features or releases
- to get attention on issues I need help with
- to re-post topics of interest to my users

You can see my posts at https://twitter.com/coveragepy/

I am a nice person, and take community safety seriously.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 We have added your projects to our approval page. Please update your bio with the approval link ( per [our verification doc](https://community.hachyderm.io/docs/account-types/verification/) ). If the link checks green, please close this ticket. If something goes wrong in the verification process, please let us know.

**Comment by nedbat** [comment]
Thanks, I now have the verified APPROVED link on my profile!
