### ISSUE TITLE
Consider glitch-soc

### ISSUE THREAD

**Issue by chx** [hachyderm/community#3]
I would cautiously recommend [glitch-soc.github.io/docs/](https://glitch-soc.github.io/docs/)

Compare https://hachyderm.io/web/@win8linux@treehouse.systems/109301007662017632 to https://social.treehouse.systems/@win8linux/109300985500664162

**Comment by davidshq** [comment]
Are there particular features in the glitch fork you would like to see on hachyderm? Personally, I'd generally prefer stable over cutting edge.

**Comment by april** [comment]
octodon.social uses glitch and I've been pretty happy with the extra features it offers.

Having visual themes to easily allow me to identify which of my many accounts I'm using is, on its own, super handy. 😅

That said, it's not _super_ common yet. You can see what the big instances are using here:
https://instances.social/list/advanced#lang=&allowed=&prohibited=&min-users=10000&max-users=

**Comment by chx** [comment]
Markdown <3

**Comment by dmah42** [comment]
see also #18

**Comment by dmah42** [comment]
my preference would be to see which of these features can go upstream.  as great as markdown would be for, say, code content, i'm not sure i want to see a feed full of all the formatting options markdown offers.

the recent 4.0 upgrade is another reason to be shy of glitch: any mastodon update also has to then wait to go through glitch for them to apply whatever patches they need to apply.  ie, any security hotfixes to mastodon can't be trivially applied until glitch has applied them.

this makes me nervous.

**Comment by quintessence** [comment]
I think that dma meant to close it, so closing :)

**Comment by ineffyble** [comment]
>  any mastodon update also has to then wait to go through glitch for them to apply whatever patches they need to apply

From what I've seen, that's generally not the case. The core maintainer of Glitch, Claire, is also one of the paid core Mastodon devs. Generally security updates are dropped about the same time for both, and can actually be available sooner on Glitch since they don't do versioned releases.
