### ISSUE TITLE
Search appears to be down

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#300]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.

No errors or timeouts, just no search results being returned at all when searching for @ users or # hashtags.

2. When are you seeing the issue? When you are submitting posts? Uploading media?

Search returns no results for known users and hashtags on the web client  “Explore” search field and in multiple iOS mobile clients including Toot!

### How long have you noticed this issue?

30-60 minutes

### What geographic region are you accessing Hachyderm from?

Dallas, Texas, USA

### Is there anything else that we should know?

Grafana dashboard shows high HTTP response times for Esme Q_0.9.  Can’t speculate as to whether that’s either related or irrelevant.

**Comment by mjfisher-bbllp** [comment]
Appears to be working properly again, many thanks to whoever or whatever fixed it.

**Comment by mjf-pro** [comment]
Appears to be working again...many thanks to whoever/whatever fixed it.
