### ISSUE TITLE
Science Tusky Emojis from Kelly Stanford

### ISSUE THREAD

**Issue by ProfFerrous** [hachyderm/community#301]
### So what emoji are you looking for?

I request adding these 6 emojis from Kelly Stanford. Attached here as separate images: 

![Tusky1](https://user-images.githubusercontent.com/118073800/218826402-b5da71f4-d379-4b29-a0ae-5c7dd710fad6.png)
![Tusky2](https://user-images.githubusercontent.com/118073800/218826428-29de6297-ff48-4b24-a3ae-044f0e95b8aa.png)
![Tusky3](https://user-images.githubusercontent.com/118073800/218826439-1692a65f-aef1-4156-a7f5-ec5a7f61eddf.png)
![Tusky4](https://user-images.githubusercontent.com/118073800/218826
![Tusky6](https://user-images.githubusercontent.com/118073800/218826504-6a6297c1-c9d2-4c46-bc1c-9519e5caac06.png)
447-a68671f5-9258-43a5-97c8-e413919ae7e1.png)
![Tusky5](https://user-images.githubusercontent.com/118073800/218826471-30a941d4-82de-4204-bb0a-6366d4870280.png)

And as a zip file which is how the artist emailed them to me: 
[Science Tusky.zip](https://github.com/hachyderm/community/files/10735741/Science.Tusky.zip)

Thank you! 
Rebecca  (@DrFerrous@hachyderm.io)

**Comment by slamp** [comment]
I contacted the author to have his/her approval and a name for each icon. Otherwise it will be :tusky1: , :tusky2: , etc

**Comment by slamp** [comment]
Discussion thread https://hachyderm.io/@kellystanford@mastodon.social/109817691298850607

**Comment by slamp** [comment]
names could be
:tusky-chemistry-1:
:tusky-chemistry-2:
:tusky-Geneticist:
:tusky-physicist:
:tusky-computer-scientist:

**Comment by slamp** [comment]
![Tusky4](https://user-images.githubusercontent.com/714910/218874751-fe5c7f73-794c-46ab-8670-938896cf4181.png)
and this one :tusky-starry-eyed-scientist:

**Comment by slamp** [comment]
the 6 emojis have been added with the following name:
:tusky_chemist_1: :tusky_chemist_2: :tusky_geneticist: :tusky_scientist: :tusky_computer_scientist: :tusky_physicist:
(I aligned the name with existing emojis from others mastodon server

**Comment by slamp** [comment]
Communication done: https://hachyderm.io/@slamp/109868478595685276
