### ISSUE TITLE
Specialized Accounts: @devopsdaysbham

### ISSUE THREAD

**Issue by thecrazyrussian** [hachyderm/community#305]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

We represent the DevOpsDays Birmingham, AL event and the talks around it. Will use this for engaging with speakers, sponsors, and attendees.

Our Hackyderm link is posted on latest event website: https://devopsdays.org/events/2023-birmingham-al/

### How will you ensure the community is protected?

Only posting things related to the conference, notifying admin if we see a breach of community guidelines.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Thank you so much! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
Looks like you're all good to go! Closing :)
