### ISSUE TITLE
Specialized Accounts: anysoftkeyboard

### ISSUE THREAD

**Issue by menny** [hachyderm/community#306]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Providing updates on the progress of AnySoftKeyboard open-source project and announcements. 

### How will you ensure the community is protected?

We have clear rules for code-of-conduct: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/CODE_OF_CONDUCT.md

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Thank you so much! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by menny** [comment]
Thank you. Works!
