### ISSUE TITLE
If possible, would like to set up a relay with my personal instance

### ISSUE THREAD

**Issue by taupehat** [hachyderm/community#31]
I've got a small instance for family and very close friends only (nobody I would allow in would violate the "don't be a dick" policy or any others at hachyderm) and was hoping to be allowed to relay from hachyderm, at least until my own instance can get enough momentum to fly on its own. The instance is social.taupehat.com - feel free to reply with any follow-up questions you might have, and thank you for your consideration.

**Comment by ghuntley** [comment]
I'm running my own self-hosted instance @ghuntley@ghuntley.com aka https://fediverse.ghuntley.com/@ghuntley and would love to relay with hachyderm. It's only me. No other users. Ever.

**Comment by dmah42** [comment]
deduplicating with #32
