### ISSUE TITLE
Specialized Accounts: omnios

### ISSUE THREAD

**Issue by citrus-it** [hachyderm/community#310]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

OmniOS is a community-developed open source operating system based on illumos. 
The account is used to provide updates about the project including release announcements and links to blog posts etc.

### How will you ensure the community is protected?

OmniOS is part of the wider illumos community which has a code of conduct that includes clear expectations for representing that community in public spaces - https://github.com/illumos/illumos-gate/blob/master/CODE_OF_CONDUCT.md

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 I'm trying to figure out if Illumos would fall under the "corporate" umbrella (as a "company or company-like" entity). Can you email us at admin@hachyderm.io to help us clarify?

Thank you!

**Comment by quintessence** [comment]
Thank you so much for following up via email. We're all set.

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by citrus-it** [comment]
That looks to have worked, thank you!
