### ISSUE TITLE
Specialized Accounts: CommitChange

### ISSUE THREAD

**Issue by wendylbolm** [hachyderm/community#311]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

We created the official CommitChange, LLC Mastodon account on Hachyderm on January 18. We’re hoping to connect with other technology for good and open source folks and projects and create a social media presence that showcases the best of what we do. We are a project of Software for Good and founded The Houdini Project when we licensed our codebase under a combination of the LGPL and AGPL in 2018; Houdini is currently a member of the Software Freedom Conservancy. While Software for Good is a Minnesota Public Benefit Corporation, we envision a world where all communities can use the power of data and technology to cultivate shared abundance and liberation. To bring this world into being, we build software with love.

### How will you ensure the community is protected?

We didn’t create a Hachyderm account to spam community members or hustle sales; our leadership at CommitChange and Software for Good are focused on creating positive impact through our work. We post to social media when we have something to say or want to boost other organizations who are doing good in the world of technology. Software for Good is also a diverse company, and we have a feedback process on the posts we send out to do our best in making sure our communications put our best foot forward. We will protect the community by continuing to work by these standards and by focusing on sharing helpful and educational information and fostering conversations over gaming the system to promote sales. 

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋  hello, I'm the Lead Mod and Executive Director of Nivenly.

Corporate accounts are invite-only at this time. Please email me at info@nivenly.org so we can go through that process prior to approving this request. 

Please note that, since corporate account sign ups are restricted on this server, unauthorized corporate accounts will be suspended / asked to migrate to a different server.

**Comment by quintessence** [comment]
Since we're still communicating via email - I'm going to close this for now. We can always re-open it when ready :)
