### ISSUE TITLE
Specialized Accounts: @comocamp@hachyderm.io

### ISSUE THREAD

**Issue by hschwentner** [hachyderm/community#314]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

We are an event to bring together the community of Collaborative Modelers to build better software.

BTW: thanks for the awesome work you're doing at Hachyderm! :-)

### How will you ensure the community is protected?

We follow our code of conduct “Be open, be honest, be respectful.“ If you like please have a look at our website comocamp.org

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by hschwentner** [comment]
Looks good (and green :-). Thank you!
