### ISSUE TITLE
Specialized Accounts: devopsdaysdc

### ISSUE THREAD

**Issue by djtstanley** [hachyderm/community#315]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

We're DevOps Days Washington DC. We run a yearly two day DevOps community event,

### How will you ensure the community is protected?

Posting only respectful content and refusing to shitpost/respond to inflammatory posts.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Hello and welcome to Hachyderm! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
Closing for now :)
