### ISSUE TITLE
homeassistant emoji

### ISSUE THREAD

**Issue by slamp** [hachyderm/community#316]
### So what emoji are you looking for?

I request to add the emoji for home assistant. https://www.home-assistant.io/
It's already available on few other servers (fosstodon.org, mastodon.nl, masto.lema.org, tech.lgbt, etc...)

![homeassistant](https://user-images.githubusercontent.com/714910/219865084-ec0c0d2f-d067-4596-b5d2-8ac2e0efae35.png)

name: :homeassistant:

**Comment by quintessence** [comment]
Closing as duplicate

**Comment by slamp** [comment]
icon have been uploaded
https://media.hachyderm.io/custom_emojis/images/000/115/098/original/86b581ad47196c3c.png
