### ISSUE TITLE
add access control allow origin asterisk header to /nodeinfo

### ISSUE THREAD

**Issue by Aranjedeath** [hachyderm/community#318]
### What is your suggestion?

Hi! I use [Elk](https://elk.zone/) to access Hachyderm. I checked my (Firefox 110, KDE NEON Linux) browser console and Elk is trying to look at Hachyderm's [nodeinfo](https://hachyderm.io/nodeinfo/2.0) and fails CORS checks ("CORS Missing Allow Origin"). Can this header be added? 

Thank you!

**Comment by slamp** [comment]
I'm using Elk from time to time, I didn't notice a problem.
@Aranjedeath Could you describe the issue, how to reproduce it and explain why CORS will solve it ?
nodeinfo is serve from https://hachyderm.io/nodeinfo/2.0 
Why should we access it from a different domain ?

**Comment by Aranjedeath** [comment]
Hi @slamp I did describe my issue in the original post, the issue is there is a request Elk is making to hachyderm that is failing CORS checks. I cannot know what this nodeinfo is used for in Elk, I guess I could go try and read the source code to find the answer. nodeinfo is broader than elk, all mastodon servers have it and many other distributed or decentralized softwares as well. The purpose of nodeinfo is cross-domain access to basic statistics about the running software application.

**Comment by slamp** [comment]
How to reproduce:
In a browser start developer tools, go to the Network tab, hit ctrl-r
![image](https://user-images.githubusercontent.com/714910/221285059-145d74c0-0142-43fe-8389-c8759d769425.png)

Note: The error is also present on elk.zone with the default domain m.webtoo.ls https://elk.zone/m.webtoo.ls/public/local 

I reproduced it also with infosec.exchange and mastodon.online

**Comment by Aranjedeath** [comment]
Looks like this was reported against Mastodon already: [See Here](https://github.com/mastodon/mastodon/issues/23135)

Elk won't have anything to do, the browser is dumping the data on the floor because it downloaded nodeinfo from hachyderm but the response headers failed (post retrieval) CORS check. 

Thank you for looking at this.

**Comment by slamp** [comment]
Thanks for finding the issue. 
I think we can close this one.

**Comment by slamp** [comment]
Follow up will be on the link pasted above.
