### ISSUE TITLE
Relays and Hachyderm -- Community Discussion Thread

### ISSUE THREAD

**Issue by ghuntley** [hachyderm/community#32]
I'm running my own self-hosted instance `@ghuntley@ghuntley.com` aka `https://fediverse.ghuntley.com/@ghuntley` and would love to relay with hachyderm. It's only me. No other users. Ever.

**Comment by dmah42** [comment]
@krisnova spent some time on stream trying to find a relay software to run and i don't think was happy with any of them.

i think it would be great to offer a relay to individuals that want to host their own instances but want to be part of the hachyderm community.

**Comment by jclulow** [comment]
I'm running a personal instance as well, https://m.unix.house/@jmc, and am definitely keen to test out relay functionality if it emerges!

**Comment by jippi** [comment]
I'v been using https://github.com/yukimochi/Activity-Relay for a Danish mastodon relay I manage - it's been working pretty smooth so far. The CLI is a bit quirky regarding how things are named, but functionality is great and uses fairly minimum amount of resources

**Comment by ineffyble** [comment]
I'm running a personal instance and would be keen to link in with the hachyderm firehose if possible.

**Comment by waffle2k** [comment]
Precisely. I would very much love the opportunity to relay with hackyderm 😊

**Comment by dmah42** [comment]
this is my opinion, not the opinion of the mods/admin/whatever: i think it should be a matter of _how_ and _when_ not _if_.  i see no issues having a relay up and subscribing to it, but i do think we want to be careful about which relay based on both what features it offers and how maintainable it is.

as the comment above suggests, so far i don't think we've identified one that works smoothly out-of-the-box.

**Comment by dmachaj** [comment]
I'd like to add an upvote for this.  I am running a just-me Mastodon server and hachyderm is my first choice of server that I would want to relay.  If and when this becomes available I'd be happy to try it out.  Thank you.

**Comment by ineffyble** [comment]
FWIW I run https://relay.gay using https://git.asonix.dog/asonix/relay and it's been easy to set up and working great.

**Comment by dmah42** [comment]
> FWIW I run https://relay.gay using https://git.asonix.dog/asonix/relay and it's been easy to set up and working great.

thanks for the recommendation.  what's the size of the sled db? and do you have any other metrics around network traffic, CPU, ram, etc?

**Comment by lucascantor** [comment]
I'd definitely be interested in this as well, with my personal instance at cantor.cloud

**Comment by quintessence** [comment]
Since relays are still an ongoing Discussion I'm going to update the label type :)

**Comment by looprock** [comment]
I've been thinking about this a lot lately. I'm on hachyderm but also interested in running my own instance, however don't want to be cut off from the opportunity to find new content. Relays seem like a good solution but the overhead seems significant. I've been working on an alternate scheme, but after this post: https://coales.co/@msh/109595980918905804 I have concerns about how it would be received... I've been working on some go code that would periodically ping the public timeline on hachyderm.io (haven't messed with the streaming yet) via the API and collect the names of the posters who appear there. I was going to then follow them from a dedicated account on my GotoSocial instance. My understanding is that once I do this, the content from those being followed by the dedicated account would become available as part of the Federated timeline (I haven't completed the script yet, so I haven't verified this). An evolution of this pattern would be to offer an API endpoint with maybe the latest 1000 people who have posted and just create a client to read that list and populate a local instance. I'd appreciate your thoughts on this. Would I be abusing hachyderm.io by doing this, or breaking some guarantees around ownership? Thanks in advance.

**Comment by looprock** [comment]
Thanks to @jerry@infosec.exchange I was made aware that apparently what I built is a rather old concept called a follow bot and they were controversial as much as 2-3 years ago when they were somewhat common before relays. It seems they were deemed 'relatively ok' provided they were used to populate small instances and honored the tag '#nobot' in someone's profile. My aversion to relays currently stems from 1) they are not widely supported/native as a part of at least mastodon, which seems to be the most widely adopted platform at the moment 2) because of 1, there are few of them and the ones that exist don't reflect the diversity of instances, so choices are limited to a fairly limited pool of popular instances 3) the server I decided to run (GotoSocial) doesn't support them at all. So given all of that my views don't probably reflect the larger community; thought the fact that the people running hachyderm are apprehensive about deploying a relay the it's complexity does make me question the overall approach and wonder if something like what I described above wouldn't be simpler to adopt and deploy.

**Comment by ripienaar** [comment]
Mastodon does support consuming relays natively. Is that what you mean?

infosec exchange recently launched one. Given their size you could probably ask them for info on the cost (bandwidth etc) and get more relevant answers

**Comment by looprock** [comment]
@ripienaar sorry for the confusion, mastodon does support consuming relays but GotoSocial currently doesn't: https://github.com/superseriousbusiness/gotosocial/issues/1123 Jerry very kindly offered to add me to their relay but I cannot currently make use of it.

**Comment by looprock** [comment]
@ripienaar RE: "they are not widely supported/native as a part of at least mastodon". Mastodon supports consuming relays but I don't believe it supports providing them natively, unless I'm mistaken which is entirely possible.

**Comment by quintessence** [comment]
Since this discussion hasn't been active in a while I'm going to go ahead and close it. So far we don't have any relays that we're going to set up but other instances are welcome to submit requests if they wish.

**Comment by hazelweakly** [comment]
I'm going to add in here that there's been a request from macaw.social for a relay (and Reid has actually been gently requesting one since November... Sorry for not posting this on github earlier, Reid!)

**Comment by quintessence** [comment]
Pinging @Preskton as relays fall under infra's purview :)
