### ISSUE TITLE
Specialized Accounts: ietf_wg_dnsop

### ISSUE THREAD

**Issue by moonshiner** [hachyderm/community#327]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

The bot is run by the working group chairs of the DNS Operations Working Group of the IETF
https://datatracker.ietf.org/wg/dnsop/

We only post updates to adopted IETF Working Group documents as they work to become RFCs. 

### How will you ensure the community is protected?

Only posting updates on updates to documents working to become Internet RFCs on DNS. 

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

The bot only posts a special subset updates which come through the IETF Datatracker API
https://datatracker.ietf.org/api/
This is the code we're currently using 

https://github.com/ietf-wg-dnsop/datatracker-toots

we appreciate all feedback

**Comment by moonshiner** [comment]
https://hachyderm.io/@ietf_wg_dnsop has 20 posts 
https://twitter.com/ietf_wg_dnsop has more

We (DNSOP Chairs) have in the post posted about Working Group meetings with links to info
Here is an example:  https://twitter.com/ietf_wg_dnsop/status/1528762810049744896

**Comment by moonshiner** [comment]
Yes, I've added the text, now to wait for an update to confirm. 

I missed that in reading the automation bits previously.  sigh

**Comment by quintessence** [comment]
Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
Reminder ping that you can add the approval page to your bio :)

**Comment by moonshiner** [comment]
Apologies, I'm waiting for the workflow to push an event, which happens in spurts to confirm I did this correctly.  It also doesn't help that I lamely forgot to push my change.  We should see some action next week, and my apologies.

**Comment by moonshiner** [comment]
#hachybots tag appears, metadata added. closing and thanks
