### ISSUE TITLE
Specialized Accounts: zellij

### ISSUE THREAD

**Issue by giyany** [hachyderm/community#329]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Zellij is a terminal workspace aimed at developers, ops-oriented people and anyone who loves the terminal. It's a terminal multiplexer first, but has much more to offer (like a plugin system and a layout system). The account exists to communicate with the OSS community, users and contributes alike, focusing on positive and open communication. We think that exciting things are happening in OSS and want to be a part of the conversation.

### How will you ensure the community is protected?

Zellij upholds a [code of conduct](https://github.com/zellij-org/zellij/blob/main/CODE_OF_CONDUCT.md) which extends to social network accounts. We aim to create a safe, welcoming and open environment and foster the sort of communities that we'd like to be a part of. We also take wholesomeness seriously.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by slamp** [comment]
https://github.com/zellij-org/zellij

**Comment by quintessence** [comment]
Hello! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by giyany** [comment]
Thank you. BTW, the link to https://community.hachyderm.io/docs/verification/ is broken on my side.

**Comment by quintessence** [comment]
Ah I changed the path with a docs refactor, thank you for catching that :) 

Full / updated link:

https://community.hachyderm.io/docs/mastodon/user/verification/
