### ISSUE TITLE
Specialized Accounts: rOpenSci

### ISSUE THREAD

**Issue by yabellini** [hachyderm/community#336]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

rOpenSci fosters a culture that values open and reproducible research using shared data and reusable software.  We are a welcoming and diverse community of research software developers and users.  

We create technical infrastructure in the form of carefully vetted, staff and community-contributed R software tools that lower barriers to working with scientific data sources on the web and to make the right data, tools and best practices more discoverable. We have a federated suite of R packages.  

Furthermore, we also promote advocacy for a culture of data sharing and reusable software and build capacity of software users and developers and fostering a sense of pride in their work.

We actively seek to give space, voice and support to people who are historically and systematically excluded from software and open science environments.

We believe that Hachyderm is an instance where we (our community) will feel comfortable, and we will reach the people we want to reach in the best way for them. We also share the values of this space regarding participation and we want to contribute to build that safe and friendly space where we can share and co-create what we build with the network. 

### How will you ensure the community is protected?

Following the rules, generating correct, quality content, engaging with the community and reporting if we detect incidents.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

We have some schedule post, mostly because of timezones/languages. We don't repeat content and the post are always created by humans. We use an R package to access mastodon API.  Post are issues on a repo. A GitHub action check the issues and the content (like if the message has media then have alt-text) and publish if the day and time are correct.

**Comment by quintessence** [comment]
👋  hello, I'm the Lead Mod and Executive Director of the [Nivenly Foundation](https://nivenly.org/).

Your account looks like it would be a great fit for our server! It also looks like it is a company / company-like account. We call these accounts [corporate accounts](https://community.hachyderm.io/docs/account-types/corporate-accounts/) and they are limited on our server. For corporate accounts please note:

* Corporate accounts are invite-only, and can be invited by emailing us at [admin@hachyderm.io](mailto:admin@hachyderm.io] (note: I'll be responding to the email in this case)
* Must [verify with their domain](https://community.hachyderm.io/docs/mastodon/user/verification/) (which it looks like you have done)
* Agree to the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant/)
* Pay the tier-based fee associated with their size. These are outlined on our [corporate account page](https://community.hachyderm.io/docs/account-types/corporate-accounts/). For smaller businesses where the tier may be a burden, we ask that prospective corporate accounts still work with us as we can work with you :)

If that all works for you, please email us at the admin address and we'll get everything sorted for your account approval. :)

**Comment by quintessence** [comment]
👋 I was able to reconcile our emails on the backend.

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
Closing this one :)

**Comment by yabellini** [comment]
Thank you so much! Everything is fine and working :-)
