### ISSUE TITLE
Specialized Accounts: cowsay

### ISSUE THREAD

**Issue by jakehamilton** [hachyderm/community#339]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

[@cowsay@hachyderm.io](https://hachyderm.io/@cowsay) is a fun little bot that posts the output of `fortune | cowsay` once a day at 10am PST. I liked having silly little messages printed out when I opened terminals as a part of my shell prompt and others seemed to as well. It also serves as reference for creating custom packages with Nix and running services with NixOS:

- The Nix (cow2img) package: https://github.com/snowfallorg/cowsay
- The NixOS service: https://github.com/jakehamilton/config/blob/e3cc18afb4f4611a60447e9dad74a6ace4fdcfe3/modules/services/cowsay-mastodon-poster/default.nix

I think that this account could fit into Hachyderm due to its often tech-related subject matter, availability as an open source project that others can run, and is a bit quirky!

---

Here are a few posts that I've enjoyed:

<details>
  <summary>View Examples</summary>

![Squirtle saying "On the Internet, nobody knows you're a dog. -- Cartoon caption"](https://user-images.githubusercontent.com/7005773/222720433-49d96aad-9baf-4018-971e-51abe00a3610.png)
![Lara Croft saying "Brain fried -- Core dumped"](https://user-images.githubusercontent.com/7005773/222720644-52e53981-b544-4ffe-8eb3-6321f875a8c5.png)
![GLaDOS saying "Play Rogue, visit exotic locations, meet strange creatures and kill them."](https://user-images.githubusercontent.com/7005773/222720753-07e434d3-5730-4a06-b591-828c7395a1bd.png)

</details>

### How will you ensure the community is protected?

I check the posts each day (since I want to see them too) and have no qualms about removing problematic content. I would sooner take the bot offline than have it posting a bunch of harmful things.

From my perspective there are two possible issues that could crop up:

1. A harmful/unwanted image is used.
2. A harmful/unwanted fortune is used.

For the first issue, I have locked down the archive of images that are available and [have filtered out one image](https://github.com/snowfallorg/cowsay/blob/00bcc91fecba0743c1eae453ee83b8292cdae145/overlays/cowfiles/default.nix#L9). I tried to check manually, but the [list is quite long](https://github.com/paulkaefer/cowsay-files/tree/main/cows) and I may have missed one. If there are any more, I'll gladly filter them out as well.

For the second issue, I will remove any post that is problematic. The `fortune` command is generally quite tame and I am explicitly **not** using the "offensive" fortune dictionary (not sure why that's even a thing).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

The bot's service configuration is publicly available [here](https://github.com/jakehamilton/config/blob/e3cc18afb4f4611a60447e9dad74a6ace4fdcfe3/modules/services/cowsay-mastodon-poster/default.nix). It's quite plain, relying on a single systemd timer that triggers a script to call `tootctl` once a day. The service runs on my NAS and I don't foresee any large complications with posting this way. I don't intend to increase the number of posts or change the event from which the bot triggers a post. I appreciate the low noise that it creates with a single image in the morning and wouldn't want to clutter up everyone's feeds with a bunch of images.

**Comment by quintessence** [comment]
Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/mastodon/user/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by jakehamilton** [comment]
Thanks @quintessence!

It looks like the docs site hasn't been re-deployed (and thus doesn't contain this recent change), is that right?

**Comment by freiheit** [comment]
@jakehamilton It's there now 😄 

@quintessence I swear it looks like you ran the job after the merge, but https://github.com/hachyderm/community/actions/runs/4320939735 shows an older commit...  I ran the job again and it pulled the right commit this time.

**Comment by jakehamilton** [comment]
That did it! Account metadata updated and it all looks like it is working. Thank you!
