### ISSUE TITLE
Add emojo for Python, other popular languages

### ISSUE THREAD

**Issue by pmbrent** [hachyderm/community#34]
As discussed [in this thread](https://hachyderm.io/web/@nova/109334738046868704), and elsewhere, I and other users would be happy to see additional custom emojos for other popular programming languages. This will make the server more welcoming to a broader variety of programmers.

Based on searching lists of popular programming languages, I will suggest adding emojo for the following:
Python
Go
JavaScript
HTML/CSS
Scala
Ruby

Thank you for your time in maintaining Hachyderm.

**Comment by krisnova** [comment]
Can we start uploading the images we want to use here and I will add them as folks identify which logo they want? We need to make sure they are legal and safe to use. Also we should probably upload the current officially branded ones. I know Go, for example, has changed logos a few times.

**Comment by pmbrent** [comment]
If we have a reasonable place to link to the license, Wikipedia's Scala logo is CC 4.0 licensed. I'll keep looking in case that's too restrictive. https://en.wikipedia.org/wiki/Scala_(programming_language)#/media/File:Scala-full-color.svg

**Comment by pmbrent** [comment]
I believe we're OK to (even encouraged to) use the Python logo, but admins will want to review the terms of use: https://www.python.org/community/logos/

**Comment by pmbrent** [comment]
[The Ruby Logo](https://www.ruby-lang.org/en/about/logo/) is licensed under the terms of the [Creative Commons Attribution-ShareAlike 2.5](http://creativecommons.org/licenses/by-sa/2.5/) License agreement, so would also need to be credited and have the license linked to somewhere.

**Comment by ioveracker** [comment]
The [TypeScript Logo asset pack](https://github.com/microsoft/TypeScript-Website/blob/f407e1ae19e5e990d9901ac8064a32a8cc60edf0/packages/typescriptlang-org/static/branding/typescript-design-assets.zip) with png and svg assets in various sizes is available in the linked TypeScript-Website repository on GitHub. However, the license is a bit unclear to me.

The [README](https://github.com/microsoft/TypeScript-Website/blob/v2/README.md#legal-notices) indicates that documentation and ***"other content"*** is CCA 4.0, but then the second paragraph there mentions:

> The licenses for this project do not grant you rights to use any Microsoft names, logos, or trademarks.

It's unclear if that means "Microsoft logos" (e.g. the four-color Windows looking thing) or "logos provided by Microsoft" (e.g. the TypeScript logo in this instance).

They offer the same zip of branding assets on their public [branding page](https://www.typescriptlang.org/branding/).

🤷

**Comment by rossyoung5** [comment]
[Elixir logo](https://github.com/elixir-lang/elixir-lang.github.com/tree/main/downloads/logos) is good to go as part of an icon pack, per [their trademark rules](https://elixir-lang.org/trademarks.html#examples-of-permitted-use). There's a [Wikimedia link ](https://commons.wikimedia.org/wiki/File:Official_Elixir_logo.png) with different sizes too.

**Comment by quintessence** [comment]
Closing as these have been added :)
