### ISSUE TITLE
Feature Request: Periodic missing reply sync

### ISSUE THREAD

**Issue by OneJaeAtATime** [hachyderm/community#346]
### What is your suggestion?

This is a python script that works to ensure all replies to a toot are cached.

https://notes.abhinavsarkar.net/2023/mastodon-context?mtm_campaign=mastodon

**Comment by Preskton** [comment]
Howdy, @OneJaeAtATime - looks like I missed this issue when I did my review last week. What's the goal of running this script?

**Comment by OneJaeAtATime** [comment]
Sorry for the late reply (ADHD brain kept forgetting to reply), @Preskton Maybe it isn't as big of a deal for us due to server size, but was bringing it to the attention that this tries to pull in missing replies for posts.

**Comment by Preskton** [comment]
Ah, interesting - TIL about this "feature" of Masto - namely, not pulling in remote replies. I'll add this to our infra backlog for someone to take a look at and possibly implement.

**Comment by Preskton** [comment]
Created https://github.com/hachyderm/infrastructure/issues/407 (private repo).

**Comment by dmah42** [comment]
Hello! This post has been closed due to N months or more of inactivity. If this situation still needs to be handled, please open a new Issue. Thank you!

The internal issue was closed 2 weeks ago.
