### ISSUE TITLE
Specialized Accounts: tremolo

### ISSUE THREAD

**Issue by mlbiam** [hachyderm/community#351]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

Tremolo Security has been a member of the Kubernetes community since 2015.  In addition to being 100% open source (no open core or "enterprise" products that are closed source), we're active in the community both with code contributions (Kubernetes Dashboard, Java Client SDK, Kiali Dashboard, kube-oidc-proxy) our CTO is often answering questions on Kubernetes' slack about OIDC, RBAC, and Security.  In 2016 when users were using our documentation for Kubernetes' OIDC instead of the official docs, we donated them to the Kubernetes project.

### How will you ensure the community is protected?

1. Listen to our fellow community members
2. Follow the rules
3. Make sure any content we create or boost is respectful of the community

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Hello! Per our email thread you're now an official corporate account at Hachyderm. Thank you!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/mastodon/user/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by mlbiam** [comment]
Thanks again!
