### ISSUE TITLE
Broken link to "verified with your official domain" on a community docs page 

### ISSUE THREAD

**Issue by smurthys** [hachyderm/community#352]
### Please let us know what you would like to add or change?

On the page titled [Specialized Account Verification with Hachyderm](https://community.hachyderm.io/docs/account-types/verification/), the link anchored to the text "[verified with your official domain](https://community.hachyderm.io/docs/verification/)" is broken: returns a 404 error.

The broken link is presently in the first item in the numbered list at the start of the section titled "Part 2: Finishing account setup"

**Comment by quintessence** [comment]
Ah I thought I caught all the dependent links when I moved the source page to our mastodon/user section. I'll update it and close this tomorrow - thank you!

**Comment by quintessence** [comment]
These changes are now live :) 

Thank you for catching these!
