### ISSUE TITLE
Specialized Accounts: @vecka

### ISSUE THREAD

**Issue by sebastian-claesson** [hachyderm/community#356]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

I am a developer that loves technology.

### How will you ensure the community is protected?

I always practice the "Don't Be A Dick" policy :)

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

It is a very simple bot that only posts once a week. But I have strict logging and alerts that warns me if it would post more often.

I agree to the Specialized Account Expectations.

**Comment by quintessence** [comment]
👋 Hello! Your bot account isn't currently following the bot rules. Once it does, we can approve the verification. The changes that need to be made:

* The bot account needs to be tagged "bot" in your profile
* Bot posts need to have the hachybots hashtag
* Bot should state what it is / be clearly understood in the bio area.

For an example bot with all of these applied, please see:

https://hachyderm.io/@cowsay

For our bot rules, please see:

https://community.hachyderm.io/docs/account-types/bot-accounts/

**Comment by quintessence** [comment]
Once you have made the above changes, please update this ticket and we'll re-review. Thank you!

**Comment by sebastian-claesson** [comment]
Hi, thanks for your clear notes. I have made these changes now. 

The bot posts every Monday so the first toot that has the hashtag will be tomorrow.

**Comment by quintessence** [comment]
Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
It looks like your account is updated! I'll go ahead and close this ticket.
