### ISSUE TITLE
Specialized Accounts: @compiler_explorer@hachyderm.io

### ISSUE THREAD

**Issue by mattgodbolt** [hachyderm/community#358]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Provides a open source tool for the open source compiler/hacking community. I emailed/DMed the mod team before creating the account and they said it was ok!

https://godbolt.org/ is the main site, happy to talk more about why I think it's a great fit for hachyderm!

### How will you ensure the community is protected?

This account is limited to a few very highly trusted members of the CE administration team. The team has time and time again proved itself capable of handling moderation on our Discord and birdsite accounts, and I have no doubt we'll continue to have no issues on hachyderm.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
I'm going to go ahead and close this one. Please let us know if there are any issues.

**Comment by mattgodbolt** [comment]
Thanks! Sorry I missed the response: we are all done on our side too!
