### ISSUE TITLE
Specialized Accounts: @twoscomplement

### ISSUE THREAD

**Issue by mattgodbolt** [hachyderm/community#359]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event (I guess?)

### How do you fit in with the community?

We're a tech podcast talking about all things techie, from compilers and security to testing and deployment.

### How will you ensure the community is protected?

Only @benrady and @mattgodbolt post and we like to think we're both pretty lovely, thoughtful, kind people.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by mattgodbolt** [comment]
Our site: https://www.twoscomplement.org/

**Comment by quintessence** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by quintessence** [comment]
I'm going to go ahead and close this one, please let us know if there are any issues.
