### ISSUE TITLE
PROPOSED RULE: Hachyderm Content Use  a Supported Language

### ISSUE THREAD

**Issue by benwis** [hachyderm/community#36]
Because our moderators do not speak all languages, we'd like to ask Hachyderm users to write their public content in one of our supported languages.

This is being driven by a number of bots and users posting in other languages that are tiresome to moderate. It is likely we are losing plenty of context that way. Due to the distributed nature of the Fediverse, I feel this is a reasonable expectation.

Rule Text: "Our current supported languages are: [English]. We ask that content posted here use one of our supported languages. "

Addition of moderators in other languages may allow us to expand the list of our supported languages in the future

**Comment by j3j5** [comment]
Would this include replies to other people or only public content (individual posts)? I try to post content in Spanish on another account, but sometimes reply to people posting in Spanish in the same language. Would this be a problem under this rule?

**Comment by benwis** [comment]
I would say no, we used ask instead of require to give us some leeway

**Comment by j3j5** [comment]
Then I'm all for helping alleviate moderators load :+1:

**Comment by benwis** [comment]
> I've read that the new version of Mastodon (v4) will support translating. This being the case and working well, would this rule still be a need for moderators?

I'd still say yes. Machine translation isn't subtle enough to effectively cover all the nuances of a language

**Comment by quintessence** [comment]
Thought / experience with multiple languages: rather than enforce a language (since we like it'll likely be English), we can rely on Google Translate for the gist and rely on our users to report malicious activity in a language that they are familiar with. This seemed to be successful for me in another situation, where most users either spoke or choose to interact in English but when they wanted to interact in non-English first languages they would let us know if there was nuance appearing that wasn't easily catchable by reasonable "moderation by those who may not speak their language as a second or even third language". We might need to finesse the wording a bit, but I think users who speak more than English would be happy enough to help alleviate moderation burden (by reporting / explaining) to be able to not have English limitations on the platform. 

Something else to consider: we have non-English speakers here already and since this is a federated environment, how do we enforce when and where they are using English "here"? Only with other Hachyderm users, or can they speak their other / native language(s) when interacting with non-Hachyderm accounts using that / those language(s)?

**Comment by untitaker** [comment]
I'd like to communicate in German in addition to English, because my private life is in German and is subject to Austrian politics (about which the press is reporting in German). I have specifically avoided fosstodon.org because of similar rules, because I don't want to split up my person over multiple servers so that hachyderm.io is for my "tech professional" persona and my political posts end up on some other instance with German-speaking moderators.

Keep in mind that language is not cultural context anyway. I would argue that just because something is in english it doesn't mean you automatically get to understand all the context. I can take, for example, some wordplay, phrase or even a Nazi dogwhistle exclusively used in German-speaking circles, literally translate it to english to pass this server's prospective rules, and it loses its meaning for moderators yet continues to make perfect sense for German-speaking users.

**Comment by benwis** [comment]
> Disclaimer: I don't moderate, so this is the opinion of a user of the platform.
> 
> I understand the difficulty for moderators to moderate foreign languages.
> 
> Here is my issue with this though: I can communicate with people in Portuguese, English, and Spanish. This kind of rule would be so limiting to me because sometimes you want to reach people that do not speak/write English.
> 
> What I would like to propose/suggest in this case is to assume a more passive moderation: unless someone is reported for what they are saying moderators don't have to be actively monitoring everything. In case someone is reported for a post in a foreign language, I think online translators can give a context of what is being said. If the meaning of the text is too nuanced to understand/judge, then maybe moderators can look for someone else who understands it to help translate.
> 
> If nothing above works, then this can be revised and more stricter posture be taken.

We do not and I am not planning on acting without reports. That's not something any of us have time for, we do not want to be the content police. I think the addition of the word primary could help here. 

I was considering this rule us allow us to limit/warn what are probably bot accounts. Today we had four or five users sign up, and then make 1 junk post in Arabic/Persian/Turkish. Then they get reported as spam by (what I'm assuming) are English speakers.

TBH this is the rule today I'm least sure about. It does make our life easier, but I am not sold on the idea.

**Comment by moke-dev** [comment]
There's a filter for posts in different languages. Maybe it could be up to people to decide what languages they want or do not want to see?

Maybe the rule could be: "if you are going to post (without replying) in a language different than English, mark your post with the language you are using".

![image](https://user-images.githubusercontent.com/8547156/202019140-40b96266-1548-4035-8da1-b304542385fa.png)

**Comment by beardandbag** [comment]
I'm a fan of the "Declare the language of your post if it is not English" approach, for three reasons:
1. It allows users to filter messages (and likely lots of spam) in languages they don't speak (or wish to translate/...), 
2. It reduces the cognitive load of evaluating reports.  If it's not English and it's not tagged, it's a foul.
3. Spammer/Bots are unlikely to follow the rule and so should be much easier to tag and bag.

**Comment by mkantzer** [comment]
I don't want to become language police, and I'm not really in favor of even defining a "default" language.

Specifying "server business happens in English, and our mod team is primarily english speakers" is a good start. I like the google translate first pass, and if we're missing anything obvious in a report, we can ask the user who flagged for clarification. 

If we end up with a particularly large group of people posting in non-english, we could reach out to the community for additional moderators?

**Comment by quintessence** [comment]
If the use case is "bots that are using non-English so we can't verify intent" (paraphrasing mine) then I think we should more focus on limiting bots, like corp accounts et al, than limiting the used languages of the platform. 

Insofar as sneaky things that have already arisen, I've already had to moderate out Nazi flags in the emoji set as "pinwheel of friendship" so dog whistles that you can't easily search for, even in the in-use language, are definitely a thing as well.

**Comment by jyasskin** [comment]
Might there be a way for hachyderm members to "sponsor" a language? So, for example, if a moderator gets a report for a post in Spanish or Portuguese, they could go to @moke-dev to translate it for them? Unsponsored languages could still be off-limits, but then we could allow a wider linguistic community without needing a full moderator from each language.

**Comment by wlonkly** [comment]
Ugh, this is a tough one. There's definitely a material difference between "User engaged with the community posting in both English and German" and "New account with default avatar who only posts in Thai and doesn't engage with anyone here", but where precisely to draw the line is hard to determine (and is fraught with geopolitics, too). 

It's true that automated translation is more reliable for European and/or Latin-alphabet languages than for not, which is probably itself tied into industry bias, but English-_only_ feels restrictive too (and I'd hate to not be able to chat with Canadian friends on other instances in French, and I know there's people I enjoy following on here that occasionally write German, and so on).

Perhaps some careful phrasing around "primarily English"?

**Comment by missingcharacter** [comment]
I can help moderating in Spanish

**Comment by LGUG2Z** [comment]
> I am considering this rule to allow us to limit/warn what are probably bot accounts. Today we had four or five users sign up, and then make 1 junk post in Arabic/Persian/Turkish. Then they get reported as spam by (what I'm assuming) are English speakers. And they're hard to decipher in Google Translate.

I am happy to look over posts in Dari, Pashto, Persian and Tajik. ✋

**Comment by benwis** [comment]
> > I am considering this rule to allow us to limit/warn what are probably bot accounts. Today we had four or five users sign up, and then make 1 junk post in Arabic/Persian/Turkish. Then they get reported as spam by (what I'm assuming) are English speakers. And they're hard to decipher in Google Translate.
> 
> I am happy to look over posts in Dari, Pashto, Persian and Tajik. ✋
> 
> Also, I like welcoming new users who speak those languages by replying "Welcome, friend!" to their introduction posts. I like to think it helps to make non-white users feel at home.

I love that! @quintessence is compiling a list of volunteer moderators for specific languages. Whether this rule becomes a thing or not, it'd be great to have someone that speaks the languages

**Comment by jakesmolka** [comment]
What's the current state of this proposal though, after numerous posts discussing it? I'm having a hard time compiling "the result".

Just my 2 cent: I totally get the motivation and I would even offer my help (as for all moderation work). Despite everything else discussed already, having supported languages based on volunteer contribution is not a very solid foundation to build rules upon. Imagine having 2 people each for like 7 languages. Let's say those 7 languages will make it in the rule text.
I bet it is highly likely that after some time - at least for one language - the translation volunteers aren't available anymore. Should the rules be changed then (and what about imposing changes to existing accounts, as discussed already somewhere above)? You get the idea.

PS: Love the team spirit here and how everyone is contributing!

**Comment by benwis** [comment]
@quintessence is compiling a list of volunteer moderators for specific languages. Whether this rule becomes a thing or not, it'd be great to have people that speak the other languages when moderators get reports of them

Some of you have already seen it, but they should be posting the link shortly

**Comment by quintessence** [comment]
The stance, that we're effectively introducing language around, is this: the only _moderated_ language will be English and all other languages on the honor system. We're still compiling a list of translation volunteers in case something comes up.

For people interested in volunteering if you could PR and add yourself that'd be really great! Note that when pulled into a moderation discussion you'd be bound by the same rules as full time mods :) 

The document with mods and translation volunteers is here:

https://github.com/hachyderm/community/tree/main/mods

**Comment by Saruya** [comment]
I used the DeepL translation option on mastodon.online a lot before moving to Hachyderm, and I have to say it did an amazing job at translating into natural sounding English.

Surely having mods who speak the language in question should be like a second-line support option, for reporting only?

Should DeepL translation be installed on Hachyderm?

**Comment by quintessence** [comment]
We can look into DeepL thank you! Going to close this one for now as the current position is English is the primary moderated language, the mods do use Google Translate (currently), and we are getting a list of volunteers for other languages in case we need assistance beyond that.

Thank you all for the discussion :)
