### ISSUE TITLE
Specialized Accounts: @techdeals

### ISSUE THREAD

**Issue by patridge** [hachyderm/community#360]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Account with some, or all, automated and/or scheduled posts

### How do you fit in with the community?

This account is just a collection point for various freebies and deals that I used to share out with friends and families manually, all covering things that tend to interest tech folks or be related to popular hobbies, with a heavy focus on video games.

This account posts about free and discounted video game offers and other nerd-adjacent interests to help folks make the most of their entertainment budget.

I've been running an [identical account on the bird site since 2019](https://twitter.com/CrazyNerdDeals) that I hope to replace here entirely.

### How will you ensure the community is protected?

I created this tech deals awareness account on Hachyderm because I've already enjoyed being a part of this community myself for my personal account. (So, thank you for making it a welcoming place!) I wasn't totally sure this type of account required special approval, but figured it was best to be sure.

I agree to comply with all special account expectations required of an account like this, following the general server rules everyone should follow as well as any extra content and behavior requirements that may come should I be able to automate or schedule any posts in the future.

The links are sometimes affiliate based, as mentioned in the account profile, if that is a factor.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

I haven't actually scheduled or automated any of the posts on this account yet, but I would like to at some point in the future to simplify sharing and reduce the chance for typos.

In the short term, I will only automate on my system, with content generated from relevant fields that I would manually copy-paste into the compose field to post. For example, on a new game download freebie, I would generate content from the game's title, store platform, and game URL in a way that is easy to skim and evaluate for anyone interested in it.

When I do figure out how to simplify posts with direct automation or scheduling, everything will still be manually created, but going directly from the relevant fields direct to a post about freebies and discounts formatted so they are easy for people to mentally parse. I don't currently want to post any new content without my interaction since I also claim all the freebies and consider the deals I share for my own use.

Regardless, I would ensure that all posts will be unique without repeating any identical content.

**Comment by quintessence** [comment]
👋 Hello and thank you for applying to be verified!

I'm so happy you find Hachyderm to be a good home for your primary account! Looking at specialized account posts, however, this account type is actually not permitted for being ad (or ad-like) in nature. Essentially, by curating links to sales ads, the account would be disallowed for ad / ad-like behavior. 

https://community.hachyderm.io/docs/account-types/

Please migrate techdeals to a server that is more suited for its content in 7-10 days.
