### ISSUE TITLE
SSL certificate expired on `hackyderm.io`

### ISSUE THREAD

**Issue by jbott** [hachyderm/community#367]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.

Chrome reported hackyderm.io SSL certificate had expired, confirmed via openssl (note `notAfter`):
```
❯ openssl s_client -connect hackyderm.io:443 -showcerts -servername hackyderm.io
CONNECTED(00000005)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = hackyderm.io
verify error:num=10:certificate has expired
notAfter=Mar 16 06:05:48 2023 GMT
verify return:1
depth=0 CN = hackyderm.io
notAfter=Mar 16 06:05:48 2023 GMT
verify return:1
write W BLOCK
---
Certificate chain
 0 s:/CN=hackyderm.io
   i:/C=US/O=Let's Encrypt/CN=R3
-----BEGIN CERTIFICATE-----
... snip ...
---
Server certificate
subject=/CN=hackyderm.io
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 4606 bytes and written 372 bytes
---
New, TLSv1/SSLv3, Cipher is AEAD-CHACHA20-POLY1305-SHA256
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : AEAD-CHACHA20-POLY1305-SHA256
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1678980214
    Timeout   : 7200 (sec)
    Verify return code: 10 (certificate has expired)
---
DONE
```

2. When are you seeing the issue? When you are submitting posts? Uploading media?

When accessing hackyderm.io

4. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

### How long have you noticed this issue?

1h

### What geographic region are you accessing Hachyderm from?

CA, US

**Comment by Preskton** [comment]
Thanks for reporting this, @jbott - I've added it to our short-term backlog! :)

**Comment by Preskton** [comment]
Cert renewed. We should be good to go:

```
-> % openssl s_client -servername hackyderm.io -connect hackyderm.io:443 | openssl x509 -noout -dates
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = hackyderm.io
verify return:1
notBefore=Mar 16 14:47:49 2023 GMT
notAfter=Jun 14 14:47:48 2023 GMT
```
