### ISSUE TITLE
PROPOSED RULE: Spam Content is Not Allowed

### ISSUE THREAD

**Issue by benwis** [hachyderm/community#37]
I am open to suggestions for this one, but ideally I'd like to have a rule against spam. But what defines spam?

Something like "Repetitive off topic content is prohibited" maybe. Thoughts?

**Comment by rossyoung5** [comment]
😄  Ha beat me to it

**Comment by rossyoung5** [comment]
> Something like "Repetitive off topic content is prohibited" maybe. Thoughts?

"Repetitive" is key I think.

Found this in the corporate accounts doc: https://github.com/hachyderm/community/blob/main/accounts/corporate-accounts.md#3-say-it-once-the-wikipedia-policy

Could we frame something around those lines?

**Comment by rossyoung5** [comment]
"Off topic" becomes harder to define and doesn't really do anything to offset the "repetitive" aspect.

I could post "JavaScript is bad" every 5 minutes, and it's technically on-topic but not adding any value to the instance.

**Comment by benwis** [comment]
Yeah. I'd agree off-topic is tricky. I definitely do not want have an allow list

**Comment by quintessence** [comment]
(I see someone mentioned this / I forgot to hit send, but sending now anyway)

Chiming in: do we have a set of guidelines for what "on topic" is? Otherwise we might need to just call it what it is: "we know it when we see it, and in general it looks like ...".

**Comment by rossyoung5** [comment]
> do we have a set of guidelines for what "on topic" is?

I figured it meant pertaining to the topics of the instance (ie [the About section](https://hachyderm.io/about/more#about) on the server info page).

I think saying explicitly "No spam" as the rule and then having a definition of spam as something to the effect of "Repetitive content with the same inherent message" could work. Is there a need for covering posting inordinate amounts of content regardless of the message? Or is that covered well enough with "Don't be a dick"?

**Comment by MatthaeusHarris** [comment]
An obviously commercial post from a new account without first posting an #intro toot is unlikely to be a positive contributor.  Perhaps this could be a metric to lean on for a moderation justification when spam pops up.

**Comment by mkantzer** [comment]
I'm hesitant to include "on/off topic", as it may accidentally capture some _quality_ shitposts that we DO want to allow. 

Repetitive is a good place to start, but also I think we should cover solicitation. There's a line between 'request for mutual aid' and 'buy my MLM pills'.

**Comment by quintessence** [comment]
We might just want to call out account types - there are types of accounts on Twitter et al that only post their GoFundMes and similar and we can just make a "no fundraising" rule for that. That will remove the need to figure out what's legit and what's spam, and we won't need to redirect people to appropriate services either.

**Comment by rossyoung5** [comment]
@quintessence 💯 on account types, as that would cover the solicitation component, as well as some concerns about [cryptobros in another issue](https://github.com/hachyderm/community/issues/40).

So how about this as a draft:

---

**_No spam accounts_**

### Spam accounts
Accounts which post repetitive content with the same inherent message or which fall in to the following account types:
- Cryptocoin/NFT promotion
- Personal fundraising
- [_y'all fill in the blanks_]

---

Thoughts on that or on what other account types need to be listed?

**Comment by adenner** [comment]
as an addition "Or other behavior that would qualify you as a corp account"?

I am somewhat of a fan of the "don't act in ways that will make me have to make a rule about it" rule

**Comment by quintessence** [comment]
I am also a fan of that rule

**Comment by quintessence** [comment]
We applied these updates in our Community docs - closing ticket.
