### ISSUE TITLE
Feature Request: Ivory universal links for iOS

### ISSUE THREAD

**Issue by OneJaeAtATime** [hachyderm/community#373]
### What would you like to discuss with us or let us know?

Ivory is launching a feature to add in universal link support. The process is pretty straightforward, at least from my perspective.

https://tapbots.social/@paul/110040513397938244

**Comment by Preskton** [comment]
Howdy, @OneJaeAtATime - if I follow this correctly (I'm not super familiar with the iOS ecosystem), this would instruct a user's iOS device to open links for the domain (in our case hachyderm.io) with Ivory? 

What's the behavior if the user doesn't use Ivory -- are they sent to the App Store and prompted to download it?

**Comment by Preskton** [comment]
Answering my own question:

> What's the behavior if the user doesn't use Ivory -- are they sent to the App Store and prompted to download it?

It's possible to add multiple apps and I think it will pop a menu to allow the user to choose, but since the example file only lists Ivory right now, Ivory would be the only choice.

Without testing, I'm not clear on what happens if you don't have Ivory, though.

**Comment by e-nomem** [comment]
My research seems to indicate that the link is simply opened in Safari if the app is not installed.
> Universal links work even when your app is not installed. When your app isn’t installed, tapping a link to your website opens the content in Safari, as users expect.

[link](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html), see the bullet point `Flexible`

Technically this seems pretty straightforward. It needs support from the app too though so it's not going to be easy to try out in our staging environment.

**Comment by dmah42** [comment]
Hello! This post has been closed due to 9 months or more of inactivity. If this situation still needs to be handled, please open a new Issue. Thank you!

If the upstream issue is resolved then this will be by proxy.
