### ISSUE TITLE
Cannot find posts by #hashtag and a timeline viewed via Hachyderm differs from the OG timeline

### ISSUE THREAD

**Issue by tomasodehnal** [hachyderm/community#375]
### What would you like to discuss with us or let us know?

Dear Hachyderm team,

I'm not sure this is issue or my misunderstanding of how Mastodon works, I'm kindly asking for an explanation of the following behavior:

1. When searching for a hashtag `#kruband` on Hachyderm, I found no posts. I still don't find them even if a day ago I followed the user posting with these hashtags.
2. This brought me to check the person's timeline at `https://mastodon.online/@rebolek` and I found out I don't see the same posts on his profile when viewing the profile via Hachyderm.
![image](https://user-images.githubusercontent.com/62995026/226837831-bdef6f0a-4718-47d8-8a78-f25643d14e92.png)
![image](https://user-images.githubusercontent.com/62995026/226837961-52c48797-1dfb-4b57-904a-9f64b3b45b7b.png)

Could you please help me understand? Thanks in advance!

**Comment by quintessence** [comment]
Hello! Can you verify if you see the below when you search the hashtag? Also, what happens if you use `tags` in the URL: `https://hachyderm.io/tags/kruband` ?

![Screenshot 2023-03-23 at 10 25 30 AM](https://user-images.githubusercontent.com/3387286/227287632-41ea2ce0-0c2b-4f93-8667-6ee8be540887.png)

There are some limitations for search on the Fediverse. For word search, you're limited to the posts you've interacted with specifically already IIRC. Hashtags do search the Fediverse, so you should be able to search with hashtags even if you're not following the user (note: I'm not following this particular user for the test screenshot).

**Comment by quintessence** [comment]
(Accidentally clicked close, apologies.)

Here is an article with a bit more about searching on Mastodon: can you verify if this matches what you see?

https://allthings.how/how-to-search-on-mastodon/

**Comment by tomasodehnal** [comment]
Thank you for the response.

Searching for the hashtag finds nothing. Does it show results for you?
Using the URL `https://hachyderm.io/tags/kruband` I can see the same (two only) posts as on your screenshot. Looking at `https://mastodon.social/tags/kruband` I can see more of them.

Also thanks for the article, it summarizes the searching pretty well. And actually, it confirms what I thought I knew about searching on Mastodon. Now the question is why I cannot use _some_ hashtags to search content, neither in browser nor in Megalodon app on Android, while other works fine (like `#kubernetes`).

Random example, `#dailymagcovers`, search shows 0 results, manually browsing the hashtags displays the content:
![image](https://user-images.githubusercontent.com/62995026/227466645-8bf7c9f3-b2fa-4302-91c4-ae4767773acf.png)

The call to `/api/v2/search` (as observed in the browser tools) simply returns empty json `{"accounts":[],"statuses":[],"hashtags":[]}`.

**Comment by quintessence** [comment]
Based on the behavior, it seems as though the hashtag search has some of the same limitations as general word search - if the post with the text / hashtag is either on the home server or has been interacted with by anyone on the home server, it becomes searchable. I'll ask around to confirm.

**Comment by Preskton** [comment]
I have a hypothesis: if a hashtag has been used by a local user, it will show up in the search results; if it hasn't, it won't show up in the search results.

## Example

![image](https://user-images.githubusercontent.com/6252405/228047942-b1b3851a-2430-4898-a399-a85db892bebb.png)

If I search for `#musicproduction`, I get results:

![image](https://user-images.githubusercontent.com/6252405/228048061-964c3ad7-00e4-4654-a5e4-0d9d91be5f17.png)

If I search instead for `#PsychedelicGhostStories` (less common), I **don't** get any results:

![image](https://user-images.githubusercontent.com/6252405/228048855-a669161a-6132-4ffa-8ad4-d074f0b2546a.png)

## Further hypothesis

I tried posting https://hachyderm.io/@esk/110096944083935721 against `#PsychedelicGhostStories` thinking that might cause the hashtag to show up, but it didn't. I suspect there is some background process that chews through tags and then adds them to our tags table.

## Conclusion

It's probably working "as designed," but I'll/the team will take some time to understand it better.

**Comment by dmah42** [comment]
i believe searching for hashtags now works (i tested with #kruband) .. can you please check and confirm?

**Comment by tomasodehnal** [comment]
Thank you for the explanation. The Mastodon hashtag search then works a bit differently than one would expect, but that's just based on assumptions brought with experience from other technologies :)
