### ISSUE TITLE
Specialized Accounts: K8sContributors

### ISSUE THREAD

**Issue by chris-short** [hachyderm/community#376]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

A number of Kubernetes users and maintainers are on Hachyderm. The Kubernetes Contributor Comms team maintains a K8sContributors Twitter account but, we want to be able to reach the community on Mastodon. Our choice of Hachyderm was a natural one given the large presence of Kubernetes community folks. This account is not managed or controlled by the CNCF. It is maintained by an all volunteer team organizing under a SIG Contributor Experience Subproject, Contributor Comms.

Historically, this account has been vital in communicating upstream changes in the Kubernetes project that will impact maintainers, contributors, and Kubernetes users. Past historic events include the [dockershim deprecation](https://twitter.com/K8sContributors/status/1521572524508688384) and the [recent registry changes](https://twitter.com/K8sContributors/status/1634251894649389058).

Given our complete lack of CNCF engagement, we would appreciate being classified as an Open Source Project at https://hachyderm.io/@K8sContributors. But, we also understand that this is a unique request given the adjacency to a foundation.

### How will you ensure the community is protected?

We know that Hachyderm is a unique place full of a diverse group of people that trust Hachyderm as their connection to  Mastodon and fediverse experience. K8sContributors is managed by a diverse set of volunteer open source contributors that also see Hachyderm as a unique place. We also see Hachyderm as the place that our community has flocked to when leaving other social networks behind. As one of many accounts on Hachyderm, we understand our place in maintaining balance and peace here.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

We don't utilize bots per se. But, we do make use of a Zapier job to share posts via Buffer from the [kubernetes.dev/blog](https://www.kubernetes.dev/blog/) and [kubernetes.io/blog](https://kubernetes.io/blog/) as these are posts worked on by or with our team or community members. We rely on Buffer's checks for existing, matching content to prevent multiple posts with the same content.

**Comment by quintessence** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by chris-short** [comment]
Thank you, @quintessence. I've added the APPROVED metadata accordingly to the account.
