### ISSUE TITLE
Specialized Accounts: nottinghack

### ISSUE THREAD

**Issue by AaronJackson** [hachyderm/community#377]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

We are a community run and owned, not for profit, hackspace based in Nottingham UK. Hachyderm felt like a good fit for us - we aim to post interesting content about what we are up to at the hackspace. The posts are not automated and they are made by individuals at the hackspace (mainly me at the moment)

I'm unsure if 'Community Event' is the correct thing to set this as. We do run events for our local community, such as Arduino workshops and metalwork training. Apologies if this is the wrong category.

### How will you ensure the community is protected?

We are a group of hackers (it's in the name! :smile:) - just like hachyderm, we operate as a safe space and aim to make people feel welcome regardless of their background. We do not (and will not) ask for donations via hachyderm, but we do encourage potential members to come for a tour. Our membership model is "pay what it's worth to you" and have concessions for those who are struggling financially. We mostly just want to post about what we're up to at the hackspace.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
Hello! I'm the Executive Director of Nivenly, Hachyderm's parent org. I think you'd make an excellent addition to Hachyderm! Would you mind emailing me at admin@hachyderm.io so I can check your account type before we proceed? Thank you!

**Comment by quintessence** [comment]
👋 Thank you for emailing us!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by AaronJackson** [comment]
Thanks quintessence ! Is it necessary to run the github action first? I don't see us listed on https://community.hachyderm.io/approved/

**Comment by quintessence** [comment]
Weird, I actually ran the event trigger after but I wonder if it grabbed the wrong commit. Running again now - try again in 5 min (or later)?

**Comment by AaronJackson** [comment]
No worries! Thanks, everything is working :-)
