### ISSUE TITLE
Specialized Accounts: @mariyadelano

### ISSUE THREAD

**Issue by mariyadelano** [hachyderm/community#379]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?
I agree to follow the rules for Specialized Account Expectations.

I am a professional in the tech industry. 

I run a content marketing agency and work exclusively with tech clients, usually B2B. Clients are typically software businesses or service providers within some tech specialization. Verticals of clients we've worked with have included: cybersecurity, DevOps, AI, data analytics, MarTech, authentication, payment APIs, etc. 

I am also a passionate tech geek and have been so since I got my first laptop at 8 years old :) I love software, geeky discussions, and while I still can't properly code (despite taking multiple CS classes back in college), I am constantly doing code-adjacent things (automation, light coding for specific tasks, techy no-code tools, or reading about programming for no particular reason). 

On Mastodon I've spent most of my time interacting with other tech professionals, I am constantly reading, posting, and reblogging posts related to tech, and in the marketing world I am exclusively familiar with the tech industry. My niche is also marketing for technical / developer audiences, and I've run workshops on that and continue to talk about it. 

I see myself as a bridge between the marketing industry and tech professionals, as I'm a lot more technical than most marketers and a lot more marketing-oriented than most tech professionals :) My husband likes to call me a "developer-to-human translator".

As for political and ideological alignment with Hachyderm - I value and continue to talk about human rights, democracy, and true freedom and safety for marginalized groups. While I am myself white and cis (and hetero-passing), I recognize that privilege and fight against bigotry when I can + try to remain educated and uplift marginalized voices. Supporting trans and wider LGBTQ+ rights is one of my core value, as is fighting against racism, fascism, and classicism. I'm a critic of capitalism and imperialism, but I wouldn't necessarily align myself with a particular political label beyond "left", as due to my origins and family history I cannot align myself with communism or certain branches of socialism. I value diverse perspectives (EXCEPT when "diversity" or "free speech" are used as a dogwhistle for harassment, bigotry, or fascist propaganda. Not okay with that and will happily report and call it out).

I am bisexual, an immigrant from Ukraine, and proudly neurodivergent. Hachyderm has been a safe haven for me too, where I can talk about my social difficulties or struggling in homogenous American and cis-male-dominated spaces. 

While I'm not perfect and I've definitely gotten things wrong in the past, I value making everyone feel welcome, safe, and respected and if I ever post or say anything problematic, please let me know and I will immediately delete and apologize.

### How will you ensure the community is protected?

As I've said in my previous answer, I do not tolerate or accept bigotry, hatred, or discrimination of others based on their race, gender identity, sexuality, disabilities, age, nationality, class, or other such characteristics. 

I try to be welcoming, kind, and accepting in everything I ever say or do. 

I will call out (when reasonable) or block and report if I encounter any such behavior or other activity against Hachyderm's community rules on Mastodon. 

I also regularly review your community page and rules to make sure I remember and understand them. 

Admittedly, because I am neurodivergent and have a track record of not always correctly interpreting instructions, expectations, or social cues I may make mistakes. I will try to catch myself when I can and delete / edit anything problematic and if I do make a mistake and your moderators inform me, I will immediately delete and do whatever actions are necessary to rectify any harm I may have caused. 

As far as I know, I have done okay so far and I've already been on Hachyderm since early February. If I have violated any rules, please let me know and I will clarify the relevant rule with you to ensure I correctly understand it and don't violate it again. 

As for overly promotional / marketing-heavy posts, as we've discussed via email, I don't believe I've posted anything like that (except I did one post around a month ago about a talk that I was doing, and that post may have been borderline. I have already decided for myself to avoid further posts that are promotional to that extent, and if I am ever in the gray area please let me know!). 

I will post about marketing but in an educational manner, as I have been doing so far. Once again, happy to discuss the types of posts I do with your team in further detail to figure out what is / isn't allowed and adjust my content / tone accordingly. I mostly post on Hachyderm the way I talk with other tech & marketing professionals in person, on calls, or in communities / comment sections, so I hope that's been a decent guiding principle to align with your expectations. 

I am happy to email your team whenever I have questions about something I am intending to post and clarify what is / isn't okay. 

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 Thank you!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by mariyadelano** [comment]
Verified! Thank you. 
<img width="840" alt="Screenshot 2023-03-30 at 4 08 32 PM" src="https://user-images.githubusercontent.com/129340321/228952652-15e21a6e-e1fa-469b-a71d-1f4c4a5041a1.png">
