### ISSUE TITLE
Should we stick with Toot?

### ISSUE THREAD

**Issue by martinjt** [hachyderm/community#38]
As many of you, I spend a lot of my time in the Web UI (the advanced one, you should try it). There is a beloved button named "Toot!" which has origins I won't go into (but you should research it as it's a fun story). We all love Tooting (and some of us Poop Tooting), and I will always call it tooting. I'm willing to explain the origins to my grandchildren.

In the v4 release of Mastodon, they've removed this awesome feature in favour of the word "Publish". (relevant PR here https://github.com/mastodon/mastodon/pull/18583).

I wonder if we should add a patch on upgrade to revert it back to a Toot.

I'll caveat this with a) I don't know how to do it, I'm not a ruby dev, and b) I don't have the time to learn to help out I'm afraid.  I just thought it was worth the discussion

**Comment by austinlparker** [comment]
I like 'Publish' but I'm a horrible stick in the mud like that.

**Comment by ioveracker** [comment]
As an alternative, you might be able to use a browser extension like [Tampermonkey](https://www.tampermonkey.net/), a custom browser extension for your favorite browser, or [Boosts in the Arc browser](https://arcboost-marketplace.vercel.app/) to modify this element for yourself regardless of the outcome here. 😁

**Comment by Paycho** [comment]
(disclaimer: not the person who'd be paying the development costs regardless)

I don't know what the general approach/principles on Hachyderm to customizing the instance are, but coming at this from a vacuum, I would usually argue that any customization should be compellingly justified - it's something you have to maintain in perpetuity, and unless there's a straightforward NAME_FOR_ERSTWHILE_FLATULENCE_BUTTON sort of variable you can pass in to customize things, it's potentially something that needs conflict resolution each time Hachyderm pulls a new version of the code.

Given that, it's hard for me to feel like it's worth doing, especially since there are workarounds (e.g. a browser extension that modifies things) that allow everyone to get what they want.

Admittedly, this particular thing probably wouldn't be the cause of major ongoing friction or development work, but little things do add up, and it's easy to justify a lot of small exceptions to a principle that end up eroding the value of having the principle at all.

**Comment by martinjt** [comment]
I can understand the reticence to put that in. My counter is that it's iconic, and part of the fun of the community.

Now, is it worth it from a "maintaining your own fork" perspective? I don't know. I'm sure there will be more customisations coming soon, especially now Mastodon is getting a lot of scrutiny from security professionals. I can see there being interim patches needing to be applied quickly, small hacks for scaling issues, etc.

I think maintaining a fork is inevitably going to happen. Is the reason to start? maybe?

I'd also say it's worth PR'ing the `NAME_FOR_ERSTWHILE_FLATULENCE_BUTTON` variable back in, so others can share it.

**Comment by martinjt** [comment]
One thought that could make it easier.. not sure if the language packages are hierarchal in Ruby? creating an `en-hachyderm.json` with a single overridden value for the form button might work.

**Comment by DorianListens** [comment]
While I also will forever refer to mastodon posts as "toots", I would definitely advocate against maintaining a fork for this. Seems like something that would potentially increase the operational costs of maintaining and upgrading hachyderm, for something that can already be achieved through browser extensions.

If it's something that's configurable per-instance without changing code, that would be one thing, but as is I would vote against.

**Comment by pudquick** [comment]
If you want to fork the code to support a custom string - let's go whole hog and make it end user configurable! Then people could publish or toot or trumpet or blat or even shitpost if they like 😄

That being said - right now, given the immense growth going on, rapid infra changes (hi slappy! welcome to the family!), recent security issues, etc - I, too, feel a little safer sticking as close to mainline branch as possible just for the time being.

But I'll still stick around even if we do decide to fork in the end. Community is made from multiple voices, all different. If at some point I stop feeling like part of this one, the joy of this platform is I can always shift to some place else.

**Comment by taupehat** [comment]
While I too find "toot" somewhat charming, it does seem like a potentially significant amount of tech debt just for the sake of nostalgia. Then again, I'm not the one who'd be maintaining the fork.

**Comment by rtprio** [comment]
I can't find it now, but I saw mention that it can easily be overridden in the CSS overrides.

**Comment by plgonzalezrx8** [comment]
Post, or Publish.

"Toot" doesn't sound right IMO.

**Comment by mkantzer** [comment]
I'm a big fan of "toot", it's more fun, and feels right. 

That being said, I'm _also_ in favor of easy maintenance. If keeping "toot" is trivial with no/minimum ongoing reqs (like just a config setting), i say we do it. If it means we need a fork, i say we just stick with publish.

**Comment by k3rn3l3rr0r** [comment]
Just for reference - it is easy to replace just by inserting CSS override in the Custom CSS settings dialog. More here: [Custom CSS to return Toot!](https://ram.k3rn3l3rr0r.net/uncategorized/custom-css-to-return-toot-button-instead-of-publish-in-mastodon-v4-web-ui/)

**Comment by OneJaeAtATime** [comment]
One balance that might be important to consider is since we are looking at professionals, we might want to think about the balance of fun and professionalism. Toot is fun, but it might end up turning off some professionals in the industry.

**Comment by campey** [comment]
Late to the discussion, but personally I like the verb/noun toot, it makes a good new domain concept for a slightly nebulous concept.

It is similar enough to "tweet" to be familiar, and that has largely been adopted by the audience on the bird site.

It also is a onomatopoeic like the sound of a hooter. This has the bonus of multilingual / multicultural accessibility, e. g. https://en.m.wiktionary.org/wiki/toet#Dutch

That there are some slang meanings for alcohol and drugs related to it hardly seems strong enough reason to abandon such a cute iconic word.

(making the case for it, while still respecting the maintainers authority to decide here)

**Comment by untitaker** [comment]
I would prefer if hachyderm.io did not attempt to bikeshed random UI choices and as a result become much more than a vanilla instance.

I see a similar discussion around adding codeblocks, which I can get behind a little bit more since it has a practical use particularly for tech workers, but even there I am not sure that it is worth deviating from vanilla.

I'm sure all of you at some point had to reinstall Windows on a stock laptop because the vendor added too many well-intentioned tweaks for no strong reason. This feels the same to me.

**Comment by adenner** [comment]
I agree with @mkantzer that it feels like just the right amount of irreverent fun while not being overly non professional if the amount of work it takes to do and support is as close to zero as possible (as it appears with the custom css)

**Comment by RazielKanos** [comment]
Every professional that wouldn't change because "toot" sounds "childish" is no professional - we're IT guys, since when are any of us a grown-up? O.o

I want at least my buddies on my instance to "toot" again :D

**Comment by quintessence** [comment]
Going to go ahead and close this, but to re-cap:

* Calling them toots is fine, regardless of the change in the official version
* We're all Questionably Adulting in the Real World :tm: anyway :) 
* We won't fork the repo over the change to "Publish" though :)
