### ISSUE TITLE
@WomeninAIethics

### ISSUE THREAD

**Issue by Mddand** [hachyderm/community#382]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Curated Content Account

### How do you fit in with the community?

Women in AI Ethics is a global initiative to increase diversity and ethics in AI. It is a fiscally sponsored project of Social Good Fund. As part of our mission, we promote the work of women and non-binary folks working hard to keep humanity safe from the harms of reckless AI. 

### How will you ensure the community is protected?

We are a small volunteer-run, donations-funded initiative so we have limited moderation resources but here's how we keep our community safe: We block any user anyone who is disruptive, dangerous, and/or poses a threat or harasses our community members in any manner. Harassment includes but is not limited to heckling the members or speakers, purposeful misgendering, mansplaining, using any kind of slur, bullying, racist comments, or any other attempt to intimidate other members or disrupt our community. There is no place in our group for hate or harassment.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by Mddand** [comment]
Thank you!
