### ISSUE TITLE
Specialized Accounts: ThingsDrawnByTextModels

### ISSUE THREAD

**Issue by AndrewFeeney** [hachyderm/community#383]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Curated Account

### How do you fit in with the community?

So-called "AI" is rising quickly and is bringing with it the expected amounts of anxiety, and controversy. I am a software developer and I created this account to provide an alternative, hopefully lighthearted and amusing, way to evaluate LLMs. Sure they might revolutionise work and/or destroy the fabric of society, but can they draw a penguin?

My aim is not to champion LLMs or to criticise them (though I'm personally plenty critical of them) but to provide some light entertainment by seeing what weird stuff they come up with.

### How will you ensure the community is protected?

This account posts some original content, and reposts other people's posts along the same lines. We don't post or repost anything that doesn't follow the guidelines, and we explicitly call out that submissions must be SFW only.

Everything we post or repost is written by or curated by a human (me).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A

**Comment by AndrewFeeney** [comment]
By the way if you feel for whatever reason that this account is not suitable for hachyderm.io, that's no problem at all. I'd be happy to find another home for it, no offence taken.

**Comment by quintessence** [comment]
This looks like a lovely account, thank you for bringing it here. ❤️

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by AndrewFeeney** [comment]
Thank you for your response, efforts and kind words! I have added the link and it now shows green.
