### ISSUE TITLE
Specialized Accounts: OpenCost

### ISSUE THREAD

**Issue by mattray** [hachyderm/community#384]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

OpenCost is a CNCF Sandbox project, this account will be used to share the latest community news and direct folks back to other community resources if they need assistance.

### How will you ensure the community is protected?

This will not be an automated account, it will be used by project maintainers to share information.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋  Hello! Can you email us at admin@hachyderm.io so we can quickly verify your account type? We have a couple clarifying questions to ask.

**Comment by quintessence** [comment]
Thank you for following up with us!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by mattray** [comment]
Thanks!
