### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by durka** [hachyderm/community#385]
### Please describe the issue you are seeing.

I'm trying to locate an account by searching, but it just spins for a very long time and comes up with no results. Tried my own username as well and saw the same.

I searched for the URL of a toot that I copied right off of the home feed and it was able to find that.

![Screenshot_20230405-022356](https://user-images.githubusercontent.com/47007/229998533-f3e88aed-0e00-4307-950a-b99437ecdef4.png)

### How long have you noticed this issue?

Just tonight? I don't know?

### What geographic region are you accessing Hachyderm from?

us-east-1

### Is there anything else that we should know?

At one point (I think while I was typing a search query) I saw a toast that said 504 Gateway Timeout.

**Comment by llimllib** [comment]
Just experienced it several more times

**Comment by smurthys** [comment]
Today's observation: Search is slow, but the first search after loading the PWA works. Later searches don't do anything. Perhaps it is just super slow and I'm not waiting long enough, but 2-3 minutes ought to be enough to conclude, I think.

**Comment by prohr** [comment]
I've been seeing similar issues over the past two days (slowness, the occasional timeouts, etc.).  Today, the problematic behaviors seem to have shifted as follows:

  - users + hashtags seem to work
  - posts don't 

For example, searching for "convex" doesn't find the following recent reply from me (under posts): 

https://hachyderm.io/@pevohr/110148035744467337

However, searching for "latent manifold" does find a subsequent reply (via hashtags):

https://hachyderm.io/@pevohr/110152556374871849

Whereas searching for the same post via the word "fantastic" generates nothing.

**Comment by prohr** [comment]
Side Q for the infra team.  If we wanted to watch grafana for search-related performance issues, which metrics/machines would be most likely to be affected?

**Comment by Preskton** [comment]
Howdy, folks - for now, we have disabled full-text search - you should be able to search for users and hashtags. We'll plan to revisit rebuilding our elasticsearch cluster (the engine that powers full text) after we've finished the 4.1.2 upgrade later this month.

**Comment by Preskton** [comment]
> Side Q for the infra team. If we wanted to watch grafana for search-related performance issues, which metrics/machines would be most likely to be affected?

Right now, we don't have any specific guidance, but this is good feedback for when we rebuild our ES cluster.

**Comment by Preskton** [comment]
Marking this as closed - we have an internal infra ticket in the backlog (not scheduled atm) to rebuild our full-text search cluster.

**Comment by prohr** [comment]
Thx for the update!  A quick note on process, though.

I get that the infra team has two workload queues to monitor (this
community-facing one + your internal one).  From your perspective, it may
make total sense to proactively close issues here + continue tracking them
to eventual closure there.

But as a community member, that seems backwards.  For us, this issue
tracker is our best communication tool for both reporting problems +
understanding the current, actual status of the service.  Thus, we'd only
expect this issue to close when either:

- search works again, or
- you decide to stop supporting it

As long as this feature remains in limbo (search cluster needs to be
rebuilt, but unclear when), wouldn't it be more accurate to leave the issue
open?

**Comment by smurthys** [comment]
Thanks @Preskton for the update, and many thanks to all the volunteers who make this service possible.

I agree with @prohr. The issue should remain open until it is actually fixed or the maintainers decide it won't be fixed.

**Comment by Preskton** [comment]
howdy, folks. thanks for the feedback. i'd planned to consolidate these under a new feature request issue, but i got distracted and didn't. i'll link these issues when i create it tomorrow.

**Comment by Preskton** [comment]
Please see #410 as the consolidated issue.
