### ISSUE TITLE
Mastodon upgrades

### ISSUE THREAD

**Issue by ryanmichaelsmith** [hachyderm/community#39]
I didn't find any info on upgrading to v4.0 so I'm creating an issue to discuss upgrades in general. If there's a better place or if this has already been hashed out, feel free to close.

Questions on upgrades:
Is there a timeline for Mastodon upgrades?
Should there be a waiting period before taking a new release?
How should upgrades be communicated to the community?

**Comment by howbazaar** [comment]
Also see #48

**Comment by slamp** [comment]
See comments from @krisnova in https://github.com/hachyderm/community/issues/48
