### ISSUE TITLE
Specialized Accounts: oxidecomputer

### ISSUE THREAD

**Issue by bcantrill** [hachyderm/community#391]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

We are a values-driven computer company, developing a new kind of server: integrated hardware and software, built from first principles.  More on our approach:

  https://oxide.computer/principles

We have a lot of overlap with the Hachyderm demographic -- and we went looking for a Mastodon instance, it was a natural fit!  We were the first company on Hachyderm, and proud to be a model for others in that regard.

### How will you ensure the community is protected?

We participate in many open source communities: community protection is very important to us!  In our social engagement on Discord, we aim for an environment very consistent with Hachyderm's mission:  open, inclusive, and professional.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by quintessence** [comment]
👋  Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by bcantrill** [comment]
Thank you so much! Now showing as Hachyderm approved -- and thank you for all you've done for the broader tech community!
