### ISSUE TITLE
Specialized Accounts: barcampbangalore

### ISSUE THREAD

**Issue by SathyaBhat** [hachyderm/community#397]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

Barcamp Bangalore is an free, open to public, participatory, workshop-event focused around people, ideas and collaboration. There’s no speaker list or fixed schedule until the actual event. All content comes from the attendees. Anyone can host a session, take part in discussions, demo a project, talk about code, discuss at lengths about anything that interests them. If you have an interesting topic to share or want to collaborate with folks with a variety of experience, Barcamp is the place for you. 

Bangalore had its first Barcamp back in the year 2006. Since then, Barcamp Bangalore has been organizing Barcamps in Bangalore at a regular cadency (yearly in the past few years) and has been a free event for everyone to take part in.

### How will you ensure the community is protected?

This account posts occasional toots regarding the announcement of the event, call for participants, sponsors and some toots related to the session proposals have been posted by our attendees. No other content will be posted.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

No automated posts will be pushed.

**Comment by quintessence** [comment]
👋  You've been added to the approval page ❤️  Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by SathyaBhat** [comment]
Thanks @quintessence! Added the label and the link it doesn't come up as green. I don't see it listed under the approved page either https://community.hachyderm.io/approved/ (though I see your change)

Can you take a look, please?

**Comment by quintessence** [comment]
Took a look - I re-ran the hook and it should be there now. Can you try again?

**Comment by SathyaBhat** [comment]
yep that works. Thanks!
