### ISSUE TITLE
Suggestion: Group custom emojis by category

### ISSUE THREAD

**Issue by imsofi** [hachyderm/community#402]
### What is your suggestion?

Mastodon has the ability to group emojis by category. This is very helpful with large sets of custom emojis to simplify the use of the custom emoji picker UI. This would not change the shortcode for any emojis.

Suggestion would be to group together Hachyderm's emoji-sets such as: Blob Fox, Blob Haj, Applications, Plusheen, etc. This is compared to today of having it all in the global "Custom Emoji" scope.

<details>
<summary>Example pictures for how it looks when used</summary>

![image](https://user-images.githubusercontent.com/20756843/234521338-7a852389-18dc-4492-b760-32dcb3103e2b.png)
![image](https://user-images.githubusercontent.com/20756843/234521408-6ec22584-8ec0-4d64-acab-d517354559bc.png)
</details>

**Comment by hachyderm-admin** [comment]
Hey @imsofi,

We appreciate the feedback and are working on upgrading the categories. We will provide an update once that is complete

Thank you,
The Hachyderm Mods

**Comment by hachyderm-admin** [comment]
Update! We were able to do this last week! All emojis grouped and federating correctly! Please let us know if you have any questions or issues, we're here to help :)
