### ISSUE TITLE
Suggestion: Defederate broken and shut-down twitter mirrors to improve search results

### ISSUE THREAD

**Issue by imsofi** [hachyderm/community#403]
### What is your suggestion?

Twitter recently changed their API pricing to require you to pay 100$ per month per 10 000 tweets you fetch. BirdsiteLive, a popular federating twitter bridge, was heavily affected by this change due to its use of the API to fetch twitter posts. This has lead to a lot of the twitter bridges being shut down or abandoned in a dysfunctional state. 

This is a problem for Hachyderm, as our search still indexes these accounts from the now broken or shut-off birdsitelive bridges. This is hugely detrimental to the fediverses discoverability, since these the accounts that were mirrored can now have created their own mastodon accounts that are hard to discover trough search.

<details>
<summary>For example: Try to find the real Hank Green from searching <code>@hankgreen</code> on hachyderm.io</summary>

![Screenshot from 2023-04-24 14-14-50](https://user-images.githubusercontent.com/20756843/234007089-fc77537c-b242-4e3f-a3c1-ed7486d3d3a1.png)
</details>

(if you dont want to look, its [@hankgreen@mas.to](https://hachyderm.io/@hankgreen@mas.to) ([src](https://twitter.com/hankgreen/status/1605092272025964544))

### Suggested action.

There currently exists a short list of birdsitelive mirrors [here](https://birdsite.wilde.cloud/), if they have been shut down or left in an abandoned (4xx, 5xx) state. Use this to de-federate instances that are shut off and broken. Birdsitelive does not allow you to migrate follows to when moving instances, and the servers are already offline as well, so defederating servers in this fashion should have minimal impact.

<details>
<summary>A brief list of birdsitelive mirrors i found from a quick search.</summary>

Broken:
```
birdsite.wilde.cloud
twtr.plus
beta.birdsite.live
twitterbridge.jannis.rocks
twitter.doesnotexist.club
birdsitelive.treffler.cloud
```

Responds to HTTP, but could not find posts on hachyderm. May be functional.
```
birdsite.lakedrops.com
birdsite.blazelight.dev
birdsite.slashdev.space
t.l3r.me
```
</details>

**Comment by quintessence** [comment]
Moderator team update: we had our meeting this week and we'll be taking care of these! Thank you for bringing this to our attention <3

**Comment by ThisIsMissEm** [comment]
An incomplete list of ones I've seen:
```
twitterbridge.ja...
bird.makeup
birdsitelive.treff...
birdsite.blazelig...
t.I3r.me
news.twtr.olus
beta.birdsite.live
tweets.icu
birdsite.tcjc.uk
birb.elfenban.de
birdsite.wilde.cl...
```

Sorry the domains are truncated, lifted these from a screenshot of search results, but you could likely do a prefix based search to find them all

**Comment by hachyderm-admin** [comment]
We researched the above and also found some others. Here's the list of Twitter bridges we suspended:

* beta.birdsite.live
* birb.elfenban.de
* bird.evilcyberhacker.net
* bird.froth.zone
* birdbots.leptonics.com
* birdsite.blazelights.dev -> no longer up to de-federate
* birdsite.frog.fashion
* birdsite.james.moody.name
* birdsite.lakedrops.com
* birdsite.link
* birdsite.oliviaappleton.com
* birdsite.slashdev.space
* birdsite.tcjc.uk
* birdsite.thorlaksson.com
* birdsite.wilde.cloud
* birdsitelive.ffvo.dev
* birdsitelive.peanutlasko.com
* birdsitelive.treffler.cloud
* bridge.birb.space
* respublicae.eu
* servernerds.net
* tweetbridge.kogasa.de
* tweets.icu
* twitterbridge.jannis.rocks
* twtr.plus + subdomains
* zwezo.o-k-i.net

To allow users to still follow Twitter accounts, we're leaving bird.makeup available.
