### ISSUE TITLE
Use FOSS alternative to Uptime Robot

### ISSUE THREAD

**Issue by makkes** [hachyderm/community#41]
From what I understand https://status.hachyderm.io/ is served by https://uptimerobot.com/. Please correct me if I'm wrong. If I'm not it'd be great to replace that dashboard with one served from a self-hosted open source alternative.

**Comment by slamp** [comment]
@makkes do you have open source alternatives to propose ?

**Comment by duthils** [comment]
FWIW, there is a public Grafana dashboard linked at the end of the README:

https://grafana.hachyderm.io/public-dashboards/bc9e340202c1495888d8fd849112a813?orgId=0&refresh=1m

**Comment by quintessence** [comment]
👋 Mod here

We're still looking at our infra and needs post migration, including the status page :)

Closing for now :)
