### ISSUE TITLE
Full-text search does not appear to update, ever

### ISSUE THREAD

**Issue by Preskton** [hachyderm/community#410]
## Background

From the mastodon website:

> Mastodon supports full-text search when Elasticsearch is available. Mastodon’s full-text search allows logged in users to find results from their own statuses, their mentions, their favourites, and their bookmarks. It deliberately does not allow searching for arbitrary strings in the entire database.

Previously, we offered [full-text search](https://docs.joinmastodon.org/admin/optional/elasticsearch/) against Hachyderm. Hachydermians have asked if we will reintroduce it. To do so, the infrastructure team will:

- identify an infrastructure implementation
- perform a cost analysis
- make a final decision as to whether or not to re-launch this feature

should we choose to reintroduce search, Hachydermians should be able to search for any keyword in toots per the Mastodon manual.

## Related Issues

#385 
#387 
#300 
#386

**Comment by Preskton** [comment]
Mini-update here - we are working on establishing some base OS images & pipeline that make it easier for us to spin up new services (like ElasticSearch) -- but more importantly -- maintain and keep them secure in a sustainable way. Thanks for your patience, all, as we keep things rolling.

**Comment by prohr** [comment]
It's been a few months.  Any updates?

**Comment by prohr** [comment]
Lovely.  And just in time for the latest surge of new users.  Thx!

**Comment by Preskton** [comment]
fyi the full text indices are building now. looks like it will take somewhere between 12-16 hours (best guess) for them to process through the backlog.

**Comment by Preskton** [comment]
Looks like the index built way faster than expected. Full text search for historical and new toots should be good to go. We'll watch for a few days and then announce if everything continues to look good.

**Comment by prohr** [comment]
I can confirm that searching for bulk-loaded content (> 5 days old) works great, but am having trouble searching for more recent posts.

How long a built-in delay should we expect between when posts are created vs. when they become searchable?  

The fact that I can't search for content as much as 3 days old suggests that something may be stalled along the content ingestion pipeline.

**Comment by Preskton** [comment]
Hrm, I would expect "somewhat immediate", e.g. like maybe 10-15 minutes max. I'll poke and see if we can see what's up.

**Comment by joelanman** [comment]
I'm a bit confused about how text search is currently supposed to work, I'm currently only finding my starred posts, nothing else

**Comment by prohr** [comment]
> I'm a bit confused about how text search is currently supposed to work, I'm currently only finding my starred posts, nothing else

How it's supposed to work is described accurately in the OP.   

The bug I've been asking Preston to chase is that it currently only seems to work for posts before they backfilled the index in early July.  AFAICT, new activity since then isn't getting indexed at all.

**Comment by prohr** [comment]
Does that fit what you're seeing too?  Then it's not just me.  😉

**Comment by joelanman** [comment]
After a bit of debugging, thats right, nothing after July 2

**Comment by Preskton** [comment]
Full-text search continues to be subject to some gremlin in our system that prevents updates. I'll be looking at this today to double-check configs & firewalls.

**Comment by Preskton** [comment]
Cross-linking this to https://github.com/mastodon/mastodon/issues/20230, as this seems to be hitting us as well. Although it seems to be *all* indexing activity.

**Comment by Preskton** [comment]
Re-running `tootctl search deploy` - will take ~17 hours from current estimate.

**Comment by Preskton** [comment]
This seems to have worked and refreshed the indices - but I'm not sure if real-time updates are happening.

<img width="217" alt="image" src="https://github.com/hachyderm/community/assets/6252405/2c066d1c-6e2a-4e4c-8a73-34083eded7ca">

**Comment by prohr** [comment]
I can confirm that content since the last bulk load in early July (including the the linked test post above) up through yesterday is all available:

https://hachyderm.io/@pevohr/110985396128335885

However, real-time updates are still broken:

https://hachyderm.io/@pevohr/110996075411410901

Replaying my "teeny" test search now gets me three posts instead of two, but todays fourth post doesn't appear.

**Comment by prohr** [comment]
Sigh.  Sometime recently all the bulk-loaded posts stopped being searchable too.

Possibly an unintended side effect of the upgrade from 4.1.4 to 4.1.7?

**Comment by Preskton** [comment]
Hiya, @prohr - we had to disable FT search the other day as it was affecting sidekiq performance pretty badly. We are going to revisit after 4.2.0 which drops next week, as there are some significant changes there.

**Comment by prohr** [comment]
Gotcha.  Figured it was something like that.  Have the core devs given you any guidance on how to tune this feature so it actually has a chance of ... working?

**Comment by mariyadelano** [comment]
Hi, wondering if there are any updates to this given that Mastodon 4.2.0 has been implemented now?

**Comment by Preskton** [comment]
The saga continues - we are attempting to re-enable it today. :)

/cc https://github.com/hachyderm/infrastructure/issues/518

**Comment by Preskton** [comment]
We've finished re-indexing -- took about 8 hours. I'm cautiously saying that we've re-enabled full-text search, but we'll watch it over the next week or so to judge impact on sidekiq queues.

**Comment by prohr** [comment]
Confirmed that the old behavior seems to be be working well (including dynamic updates) if you add the in:library qualifier.

Thanks!

**Comment by joelanman** [comment]
@Preskton thanks to everyone who worked on it, I really find search very useful!
