### ISSUE TITLE
Missing profile image from other server - cache problem?

### ISSUE THREAD

**Issue by jknlsn** [hachyderm/community#412]
### What would you like to discuss with us or let us know?

Hi team,

An account I follow has a broken profile image, despite it appearing on their server.

The domain is on mastodon.social, and I saw the announcement that the instance has been limited today but the issue has persisted for at least a month, and only this one user not all mastodon.social users.

Profile image link:
https://media.hachyderm.io/cache/accounts/avatars/109/422/020/645/791/877/original/0d1f3d305a84e04c.jpeg

Please let me know if I can provide more details. I haven't mentioned the account unless it's necessary.

This seems to be the exact same root cause as [265](https://github.com/hachyderm/community/issues/265)

**Comment by Preskton** [comment]
@jknlsn - could you please DM the Hachyderm account -- https://hachyderm.io/@hachyinfra -- with the handle of the account that's showing this behavior? There's a media refresh command we can run that *should* clear this up.

**Comment by Preskton** [comment]
Ran `tootctl refresh` for the account provided by @jknlsn and assets were refreshed as expected.
