### ISSUE TITLE
Consider suspension of gegenstimme.tv

### ISSUE THREAD

**Issue by alxndr42** [hachyderm/community#416]
### What domain(s) need to be added or removed from our blocklist?

I've just been made aware of `gegenstimme.tv`, which describes itself as a "censorship free" video platform. One look at the homepage shows that they're about anti-vaccination, racism and queerphobia.

**Comment by quintessence** [comment]
Head moderator here. Thank you for this report! I will add this to our research queue and send an update to the mod team to update the blocklist. Thank you again :)

**Comment by hachyderm-admin** [comment]
We just realized we left this one open - apologies! We ended up looking into the instance and suspending it. Thank you for bringing this to our attention :D
