### ISSUE TITLE
Poor response times reported in NL

### ISSUE THREAD

**Issue by LGUG2Z** [hachyderm/community#42]
I have been sending a friend in NL some links to posts on Hachyderm recently and they shared this feedback with me:

```
them: hachyderm.io server seems SO slow so often
me: Really? I'm using it all the time and I'm not noticing anything on the west coast, but I know they were doing something about an EU instance in the last few days
them: hmmm it takes me about 2 or 3 mins to load any URL on that domain
them: or to even connect
them: I can't see that message, e.g.
```

**Comment by mitsuhiko** [comment]
From Austria at last hachyderm is full down multiple times a day. I'm not entirely sure what is going on, but when it comes back it feels reasonably responsive.

**Comment by quintessence** [comment]
I wanted to circle back on this and see if the service has improved?

**Comment by mitsuhiko** [comment]
Seems significantly better as of late.

**Comment by quintessence** [comment]
Excellent - I'll close this for now but please let us know if it happens again.
