### ISSUE TITLE
Expired certificate for media.hachyderm.io

### ISSUE THREAD

**Issue by jeffska** [hachyderm/community#424]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

Certificate for media.hachyderm.io has expired

> Issued On	Monday, February 27, 2023 at 7:40:21 PM
> Expires On	Sunday, May 28, 2023 at 8:40:20 PM

### How long have you noticed this issue?

Past 10 minutes

### What geographic region are you accessing Hachyderm from?

US

**Comment by durka** [comment]
Btw, the cert for omg.hachyderm.io (the redirect to here) is also out

**Comment by Preskton** [comment]
infra folks taking a look now, thanks for the report. 👋🏽

**Comment by Preskton** [comment]
Cert renewed & distributed. Thanks for your patience, folks!
