### ISSUE TITLE
Wrong certificate served for omg.hachyderm.io

### ISSUE THREAD

**Issue by durka** [hachyderm/community#425]
### Please describe the issue you are seeing.

omg.hachyderm.io used to redirect to github.com/hachyderm/community/issues, but now it results in SSL_ERROR_BAD_CERT_DOMAIN. FIrefox won't allow adding an exception because HSTS is enabled (good!).

The certificate being served is for hachyderm.io, www.hachyderm.io and southbound.hachyderm.io.

### How long have you noticed this issue?

¯\\_(ツ)\_/¯    Potentially since the media cert was renewed yesterday. I commented in #424 saying omg's was also expired, which I think was correct, but it could have been the bad domain error then already, and I misread it?

### What geographic region are you accessing Hachyderm from?

us-east

**Comment by e-nomem** [comment]
Thanks for the report. It _was_ expired, but has now been renewed.
