### ISSUE TITLE
Consider Lemmy

### ISSUE THREAD

**Issue by dmah42** [hachyderm/community#428]
### What is your suggestion?

Consider hosting a hachyderm-related Lemmy instance, or similar.  The linked infrastructure issue will contain the assessment but a conclusion will be posted here.

**Comment by hachyderm-admin** [comment]
👋 We ended up deciding Lemmy / kbin should be a Nivenly project, and they will be following up!

**Comment by hachyderm-admin** [comment]
Reference to the decision in [July Moderator Minutes](https://community.hachyderm.io/blog/2023/07/07/a-minute-from-the-moderators/).
