### ISSUE TITLE
Add illumos emoji

### ISSUE THREAD

**Issue by papertigers** [hachyderm/community#43]
It would be nice to have an illumos emoji on hachyderm as a number of us from the community are interacting there.

![illumos Logo](https://illumos.org/docs/images/logo/PhoenixRGB.png)

Example from @jperkin on a different mastodon instance:
https://federate.me.uk/@jperkin/109354735824423426

Logo docs:
https://illumos.org/docs/about/logo/

Suitable size for an emoji:
https://illumos.org/docs/images/logo/Phoenix64x64-RGB.png

**Comment by quintessence** [comment]
Done :)

**Comment by papertigers** [comment]
Thanks!!
