### ISSUE TITLE
Specialized Accounts: fluiddyn

### ISSUE THREAD

**Issue by ashwinvis** [hachyderm/community#430]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

It is an academic free and open source project aimed at creating efficient Python applications for Fluid Dynamics (see PyPI for fluiddyn, fluidsim, fluidlab, fluidimage etc) and also other general tools for scientific Python stack (see transonic).

### How will you ensure the community is protected?

We always abide by a code of conduct which aligns witj Hachyderm's equivalent.

https://fluiddyn.readthedocs.io/en/latest/code-of-conduct.html

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
Thank you! You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add https://community.hachyderm.io/approved/ to your profile meta data with the name/label APPROVED. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by ashwinvis** [comment]
Done, thanks!
