### ISSUE TITLE
Please reinstate t.l3r.me federation

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#432]
### What domain(s) need to be added or removed from our blocklist?

t.l3r.me bridged accounts pulling from Twitter seemed to be working alright for most of today even after Elmo’s “accounts only” wall went up. Stopped working after the admin team said we’d begun reviewing the status of these bridges.  Can you please take another look at that one?  Thx

**Comment by hachyderm-admin** [comment]
Sure! We saw some failures when we de-federated. We have removed the block now - let us know if there's anything else.

**Comment by mjf-pro** [comment]
Just saw them start coming through again, we'll see how well that holds now that Musk is rate-limiting. 🤞

**Comment by ThisIsMissEm** [comment]
Related to https://github.com/hachyderm/community/issues/403

**Comment by hachyderm-admin** [comment]
Closing :)
