### ISSUE TITLE
document server specs

### ISSUE THREAD

**Issue by unusualevent** [hachyderm/community#433]
### Please let us know what you would like to add or change?

The infrastructure docs don't yet list how beefy the instances are.

https://community.hachyderm.io/docs/infrastructure/

it is possible to see a live percentage, but not the specs: https://grafana.hachyderm.io/public-dashboards/445bbb0e169f4e86b1d1eeee7e50c92a

**Comment by Preskton** [comment]
Seems we need to update that community page quite a bit. As a quick update:

3x CDN nodes @ Linode - 2x CPU, 4 GB dedicated
1x Prometheus node @ Linode - 4x CPU, 8 GB shared

... and Hetzner doesn't make it terribly obvious what the hw specs are for its dedicated offerings. I'll have to poke and see what I can find.

**Comment by soupglasses** [comment]
To add on to this, the Hetzner side is currently as follows:

- 4 x Dedicated Hetzner with: 16x CPU, 128GB RAM.
- 1 x Dedicated Hetzner with: 64x CPU, 128GB RAM.

These machines are subject to change depending on use and demand, so do not take this as the definitive layout.
