### ISSUE TITLE
birdsitelive.kevinyank.com

### ISSUE THREAD

**Issue by sentience** [hachyderm/community#434]
### What domain(s) need to be added or removed from our blocklist?

Per [your post](https://hachyderm.io/@hachyderm/110635461971628991), please reinstate birdsitelive.kevinyank.com, my personal Twitter relay server. It is still operational.

**Comment by sentience** [comment]
This is now resolved. Thank you!

**Comment by ThisIsMissEm** [comment]
Related to https://github.com/hachyderm/community/issues/403
