### ISSUE TITLE
Specialized Accounts: humaneguild

### ISSUE THREAD

**Issue by davekonopka** [hachyderm/community#435]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Curated Content Account

### How do you fit in with the community?

The account represents a newsletter about people-centered content related to the tech industry.

### How will you ensure the community is protected?

 I understand the special account rules. I'll be interacting mostly like a person with little reposted content. I agree to adhere to [Hachyderm's Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant/).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

I won't be doing automated posting.

**Comment by slamp** [comment]
Account is https://hachyderm.io/@humaneguild

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by davekonopka** [comment]
Thanks for reviewing! The verification link worked as described.
