### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by durka** [hachyderm/community#436]
### Please describe the issue you are seeing.

This toot's media doesn't load for me when viewing on hachyderm, but it works on the original site: https://hachyderm.io/@elkraneo@mastodon.social/110649506583620707

When I click the play button, the Firefox dev tools show this error:

```
Uncaught (in promise): DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.
```

### How long have you noticed this issue?

I saw it on another toot earlier but I don't have the link

### What geographic region are you accessing Hachyderm from?

us-east

**Comment by Preskton** [comment]
Hi, there, @durka - have you seen this behavior recently? We recently upgraded to `v4.2.0` and it's possible this might have improved with that release.

**Comment by durka** [comment]
I can't remember seeing it recently. Also, the original linked toot works for me now. It's possible what I was seeing was just that the video hadn't federated *yet*

**Comment by Preskton** [comment]
I know it's been a bit, but I think we've found the cause of this -- I think.
