### ISSUE TITLE
The new web page preview is causing backscrolling weirdness

### ISSUE THREAD

**Issue by chx** [hachyderm/community#439]
### What would you like to discuss with us or let us know?

This has gone online a few weeks (? time is weird, these days) ago and when I try to backscroll, it jumps weird. Surely I can't be the only one to experience this...?

This is Chrome on Windows.

**Comment by chx** [comment]
I _know_ making screenshots with my phone is a horrible idea but it's so hard to reproduce this and Win+G refused to make a recording so I didn't have a better idea than to make this real quick https://photos.app.goo.gl/MWeKQfTx81ekiKAe7

**Comment by chx** [comment]
https://photos.app.goo.gl/K9FwvJfApzwZhHfv9 Here I keep the up arrow pressed.

**Comment by soupglasses** [comment]
This is likely an issue with Mastodon. As Hachyderm does not modify source code in a way that such an issue would prop up uniquely here.

One lead i found to this issue could be this (mastodon/mastodon#25837), but video's of its jitter seems different to the one you have shared here. You may try to share these videos as well as your setup in there as a 2nd example.

Hope this helps! :smile:

**Comment by Preskton** [comment]
Hi, @chx, we'll be upgrading to 4.2.0 once it's generally available, and it's possible this might have some changes that could improve this behavior. I'm going to close this issue for now, but if you feel inclined to open a ticket on `mastodon`, you can refer to this ticket as context.
