### ISSUE TITLE
Unicycle emoji

### ISSUE THREAD

**Issue by sporksmith** [hachyderm/community#44]
This is my best guess as where to start this conversation; LMK if something else is more appropriate :)

As a unicyclist, I'd enjoy having a unicycle emoji.

Someone with a self-hosted masto instance offered up theirs: https://velocipederider.com/@ruari/109355234519904508

I might take a stab at cleaning that up a bit (e.g. with a higher contrast outline) if you're amenable to adding one, but first, are you amenable to adding one?

**Comment by quintessence** [comment]
Added! :)
