### ISSUE TITLE
Favorites toots not shown as favorites in feed

### ISSUE THREAD

**Issue by Indeedornot** [hachyderm/community#440]
### Please describe the issue you are seeing.

Hi!
While using a Mastodon official app I've encountered an issue of toots appearing unfavorited on a second seeing when they were previously favorites and I still appear in the favorites list

A video of a bug has been sent to admin@hachyderm.io

### How long have you noticed this issue?

3 days

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by Indeedornot** [comment]
![IMG_20230709_001750.jpg](https://github.com/hachyderm/community/assets/49447848/86de1c3f-f4ab-468b-8722-c862e9b1c375)

Issue also affects polls

**Comment by soupglasses** [comment]
We have completed some work on the back-end to get the services up to speed again. So, this should likely be addressed as part of this work. May i ask you to verify if this issue is still occurring, or if it has been resolved?

**Comment by blueturtleai** [comment]
Are they also unfavorited when you open the detail view of the posts? Are they also unfavorited, if you use the web client?

I’m using the icecubes iOS app and sometimes I see the favorite star only in the detail view and not in the feed view. In this case it’s a bug in the app.

**Comment by Indeedornot** [comment]
The issue appeared both on the feed and the detail view. However I was still able to see whether I favorites the feed when looking at the people who favorites the view.

There was also an issue with lack of number of favorites.

As of today the issue seems to be resolved. Only issue I still notice is the discrepancy between the number of favorites and the number of people who favorites. But this can be blamed on the app not comparing favorite counts after fetching users who favorites.

Thank you for your fix
(This issue is ready to close, however I'd prefer you did it should there be a need for more details or anything)

**Comment by blueturtleai** [comment]
> Only issue I still notice is the discrepancy between the number of favorites and the number of people who favorites.

There can be a difference, if a user who you muted, favorited a post. The favorite is counted, but you don’t see the user in the favorite user list. At least that’s the way, how it works in my app.

**Comment by Indeedornot** [comment]
So far I have not muted anyone, so unless it's an instance mute (if these exist) it doesn't seem to be it.

Using official Mastodon app

**Comment by blueturtleai** [comment]
You could compare it to the web client and if it works there, open an issue for your app.

**Comment by soupglasses** [comment]
I will be closing this issue as it has very likely been solved. If this is not the case, please do feel free to reopen this issue, or by starting a new one. Thank you! :)
