### ISSUE TITLE
Copying portions of your documentation

### ISSUE THREAD

**Issue by sschwetz** [hachyderm/community#443]
Hi,

I am building up some documentation for the users of our small instance and would like to know if I can copy portions of your documentation. Any content copied will be attributed back to your documentation, we are only a small instance and I don't really feel like reinventing the wheel.

It will not be all content, I am looking at pages like this

https://community.hachyderm.io/docs/hachyderm/mental-health/

**Comment by hachyderm-admin** [comment]
Yes! Our docs have a copy-left / CC license :) Please feel free to re-use and adapt to suit your instance!

**Comment by hachyderm-admin** [comment]
Going to go ahead and close this one - please feel free to re-open if you have any questions.
