### ISSUE TITLE
Web page preview isn’t displayed in some cases

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#444]
### Please describe the issue you are seeing.

In some cases web page previews are missing. When I check the post on the original instance, the preview is displayed, on hachyderm it’s not.

Example: https://hachyderm.io/@spiegelnews@mastodon.social/110706355209056973 
https://mastodon.social/@spiegelnews/110706355174108436

### How long have you noticed this issue?

Starting on 13th of July

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by blueturtleai** [comment]
In the meantime the situation is worse. Now no page previews are displayed anymore for the account mentioned above, before at least some were displayed.

**Comment by blueturtleai** [comment]
Has the problem been fixed? It’s seems to work now again.

**Comment by blueturtleai** [comment]
Has this problem been fixed? Web page preview seems to work again now. A remaining problem is, that in some cases the preview text is displayed, but the preview image is missing.

**Comment by blueturtleai** [comment]
In most cases, web page previews are now displayed pretty quickly. But some minutes ago, it took several minutes. The reason seemed to be the very high latency of the pull sidekiq queue. What caused this latency? 

![IMG_3978](https://github.com/hachyderm/community/assets/113246030/cf2427dd-9e61-4e07-8549-b70633580009)

Issue #445 seems to be caused by the same problem.

**Comment by blueturtleai** [comment]
Now the pull queue latency is at 16 min.
![IMG_3979](https://github.com/hachyderm/community/assets/113246030/46ff40a9-3d6a-47ff-872a-4f69f72ef4d4)

**Comment by soupglasses** [comment]
Closing this as the issue should have been solved in #445 which also has an explanatory comment https://github.com/hachyderm/community/issues/445#issuecomment-1646190653 about the likely cause.

Please do feel free to comment here if it is also fixed for you. or if you are seeing any further issues.
