### ISSUE TITLE
Images not displayed in some cases 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#445]
### Please describe the issue you are seeing.

In some cases images in posts are missing. When I check the post on the original instance, the image is displayed, on hachyderm it’s not.

Example: 
https://hachyderm.io/@inha@masto.ai/110708216162829322

https://masto.ai/@inha/110708216108830447

### How long have you noticed this issue?

Can’t remember exactly. Perhaps since a week.

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by blueturtleai** [comment]
Now there are more and more images missing. It would be great, if somebody could check and hopefully fix this problem. 🙏🏻

**Comment by dmah42** [comment]
other instances are also reporting this for federated posts. the media does show up a minute or so after the post, so it seems like maybe a media processing delay. opening the post or refreshing seems to help as a workaround.

**Comment by blueturtleai** [comment]
I just checked the image, which was missing and it is displayed now. In this case the delay was not minutes, but hours.

If there is a processing delay, is this something which has to be fixed on the hachyderm side?

**Comment by blueturtleai** [comment]
Here another example where the image is not displayed since > 30 min.
 https://hachyderm.io/@inha@masto.ai/110716965264389244

When I open the link, instead of the image „not available“ is shown. When I click on this text, the image is displayed in a new tab. So, the image is available, but not displayed in the post for some reason.

I were surprised, that the image link points to the original instance and not to hachyderm. I expected, that the image would be replicated to the hachyderm servers and displayed from there.

**Comment by dmah42** [comment]
this appears to be an upstream issue and we're investigating alongside other Mastodon admins.  two potential causes identified so far:

- a Content Security Policy prevents the browser from displaying a player when viewing the file directly
- large files will fail to download far more often due to a stricter timeout from some DoS mitigation work

**Comment by blueturtleai** [comment]
@dmah42 Thanks for the update. I don’t think, that it’s a CSP problem, as the image is also not displayed in my app.

How does it work normally: is the image replicated to hachyderm and displayed from there? Like I wrote above, I were surprised, that the image was displayed from the original server and not from hachyderm.

**Comment by blueturtleai** [comment]
Are there any news concerning this issue?

**Comment by blueturtleai** [comment]
In most cases, the images are now displayed pretty quickly. But some minutes ago, it took again several minutes. When this happened, I checked the sidekiq queue stats and saw, that the pull latency was very high. I guess, this caused the delay. Of course the question is, what the latency increase causes.
![IMG_3978](https://github.com/hachyderm/community/assets/113246030/eb943883-dc65-4471-91dd-267f724ca955)

**Comment by blueturtleai** [comment]
Now the pull queue latency is at 16 min.
![Uploading IMG_3979.jpeg…]()

**Comment by blueturtleai** [comment]
Now the pull queue latency is at 16 min.
![IMG_3979](https://github.com/hachyderm/community/assets/113246030/7924bec3-bfe5-4180-8f07-e8bef5213487)

**Comment by soupglasses** [comment]
Hi there! Sorry for this taking a week, most of us are currently on holiday.

I just did some work on the back-end to get this problem addressed. And from my testing my changes seem to have solved the issue looking at the federated timeline for a few minutes. So i think this can now be closed. :sunglasses:

For the technical folk, it seems that the pull queues were put into a funky state after the caching redis server was abruptly stopped and then later restarted. You can read more about it in [this blog post about the incident](https://community.hachyderm.io/blog/2023/07/16/security-incident-redis-cache-exposed-to-public-internet/).

Please do feel free to reopen this issue if you see any further images fail to load. :smile:

**Comment by soupglasses** [comment]
Well as i say it, i can see it show up again with https://hachyderm.io/@savaslab@mstdn.ca/110753961944039849

![image](https://github.com/hachyderm/community/assets/20756843/c53fd10c-e94c-4f5a-9e17-44abd137e4dc)

Not sure what is causing some to fail like this.

**Comment by soupglasses** [comment]
Found the issue to be DNS related (*its always dns, issn't it* :disappointed:).

Applied a fix on the server of which is returning the failing requests, and everything in the logs seem now to be running smoothly. :tada: 

Closing again as it should be fixed for real this time. :sweat_smile:

**Comment by tehstu** [comment]
Oh wow, it really is always DNS! Thanks for taking a look.

**Comment by blueturtleai** [comment]
@soupglasses Thanks for looking into this and fixing it!
As for the pull queue latency, I wonder if it would make sense to set up some monitoring to detect these situations automatically.

**Comment by dmah42** [comment]
we do have some monitoring on queue latency.  I think maybe it's not sensitive enough.

though note that the pull queue didn't do much other than federation pulls so is not "critical" like the default queue is.  with the recent changes in 4.1.3 to image processing this may no longer be as true.

**Comment by blueturtleai** [comment]
Was the missing image issue even connected to the high pull queue latency? Or was it just a DNS problem?

**Comment by soupglasses** [comment]
I think it was both. An unclean state due to the caching redis being offline, together with a flakey DNS resolver that was unable to resolve a subset of domains.

For why the DNS got flakey after a reboot really does fail me. However, reconfiguring it to point to the same DNS server and restarting the DNS service made it happy again.
