### ISSUE TITLE
Dungeons & Dragons Emoji

### ISSUE THREAD

**Issue by jbutz** [hachyderm/community#446]
### So what emoji are you looking for?

I'd love to see the D&D logo added as an emoji. Every server I have seen has `:dnd:` as the shortcode, but `:dungeons_dragons:` or `:dungeons_and_dragons:` or `:dungeonsAndDragons:` would also work.

![dungeons-and-dragons-emoji](https://github.com/hachyderm/community/assets/736696/e05770b4-7cab-4cfe-b9fa-586406e9f16b)

**Comment by hachyderm-admin** [comment]
Done! Thank you for submitting!
