### ISSUE TITLE
Redis incident placeholder - Incident Analysis

### ISSUE THREAD

**Issue by Preskton** [hachyderm/community#449]
Placeholder for the Redis incident from July 16.

## To Do

- [x] Write up initial analysis
- [x] Post to community blog
- [x] Post to Hachyderm announcements (or via @hachyderm account)

/cc https://github.com/hachyderm/community/pull/450

**Comment by Preskton** [comment]
Using the blog instead.

**Comment by Preskton** [comment]
Will use this as a persistent ID and record of the action to post the incident analysis. The actual analysis will go in the blog.

**Comment by dmah42** [comment]
https://community.hachyderm.io/blog/2023/07/16/security-incident-redis-cache-exposed-to-public-internet/
