### ISSUE TITLE
Specialized Accounts: books2explore

### ISSUE THREAD

**Issue by DuqueDeTuring** [hachyderm/community#463]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

The account will post 1 time per day and its content will be the title of a book (will *not* include a link to a store). The books are from a variety of topics and genres, for example: biographies, science, history, history of science, art, architecture, engineering, fiction and philosophy.

### How will you ensure the community is protected?

I have read and I agree with the rules for "Specialized Accounts". 

The content for the bot will come from the README file of one of my public repos (https://github.com/DuqueDeTuring/books2explore), it is just a list of book titles that I would like to read or that I find interesting in some way. The list is maintained manually and only by me.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

The bot's code doesn´t rely on content provided by third parties and won´t be updated by anyone else.

**Comment by hachyderm-admin** [comment]
Apologies for the delay on this one - we thought we had closed it out. We'll work on this this afternoon and update here.

**Comment by DuqueDeTuring** [comment]
Don't worry, it is not an emergency.
Thank you!

**Comment by hachyderm-admin** [comment]
Thank you so much for your patience, and again sorry about that!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by DuqueDeTuring** [comment]
Profile field highlighted in green and with the green check mark.
Thank you!
