### ISSUE TITLE
Requesting resize of :fedora:

### ISSUE THREAD

**Issue by michel-slm** [hachyderm/community#466]
### So what emoji are you looking for?

The :fedora: emoji seems a bit too large - note that it seems cropped on my display name: https://hachyderm.io/@michelin

Firefox: 
![image](https://github.com/hachyderm/community/assets/85603/14dba1d5-72e6-4e2e-9f56-2dad145b02b1)

MS Edge (Chromium):
![image](https://github.com/hachyderm/community/assets/85603/d3d399bb-1585-4a5c-80a8-16467294b139)

On Tusky for Android the full emoji is rendered, but it does look slightly too big as well.

**Comment by soupglasses** [comment]
Hmm, I don't think there is a good method of replacing custom emotes in this way. I know there are a few other older emotes that are also affected by this cropping issue. I will see to look into if there is a good way to get emotes correctly rendered, as this is not ideal.

**Comment by slamp** [comment]
I re-upload it using the favicon as source and by adding 6 more pixels on each side.
@michel-slm could you check with :fedora_test: ?

**Comment by soupglasses** [comment]
I was looking to open an upstream issue, as the actual image is correct: https://media.hachyderm.io/custom_emojis/images/000/280/843/original/94f68cb48e53dcef.png

Which i think is the correct approach here.

![image](https://github.com/hachyderm/community/assets/20756843/e3c4501e-6de1-4549-92e9-6b2296cf4f46)

From a quick poke, it seems to stem from this margin line for emojione. Disabling it gives back a correctly, uncropped, image.

![image](https://github.com/hachyderm/community/assets/20756843/92519e9b-0518-4458-8d3e-d129f0eb5b8a)

**Comment by soupglasses** [comment]
Opened an issue :+1:

**Comment by slamp** [comment]
It's always better to fix the source cause than use a workaround. Thanks @soupglasses for opening the bug.
@michel-slm until that you can use the following :fedora_test: as workaround

**Comment by michel-slm** [comment]
I'll check on my laptop tonight, thank you! If I need to use the test one let's hope I have enough characters left

**Comment by michel-slm** [comment]
The workaround did look a bit better - but is too long so I can't display my other affiliation emoji (Debian). Thanks for triaging and getting this reported upstream, hopefully it gets fixed soon

(I tried both the stock UI and TangerineUI 1.9.4 and they are both affected)

**Comment by hachyderm-admin** [comment]
Thanks for the support, we will close out this ticket pending the upstream fix.
