### ISSUE TITLE
"Explore" is not updating

### ISSUE THREAD

**Issue by davidemyers** [hachyderm/community#469]
### Please describe the issue you are seeing.

The "[Explore](https://hachyderm.io/explore)" feed has not been updated for a few days. I normally browse with Ivory and view this feed through Search/Trending.

### How long have you noticed this issue?

Maybe two days.

### What geographic region are you accessing Hachyderm from?

Through different VPN servers in Ashburn, VA, USA.

### Is there anything else that we should know?

So sorry to hear about Nóva.

**Comment by madrobby** [comment]
The feed appears to have stalled some time on Friday 8/18 or Saturday 8/19.

**Comment by soupglasses** [comment]
Hi there!

You are indeed correct that the Explore tab is not updating. From a quick look over on our end, the scheduled jobs had frozen up. This has now been addressed, but it may still take some time until you will see recent posts on the "Explore" tab again.

If you want to follow its progress more closely, you can look at https://grafana.hachyderm.io/public and look under the Sidekiq worker called `scheduler`.

Thank you for bringing it up. :smile:

**Comment by soupglasses** [comment]
The https://hachyderm.io/explore page is now showing recent posts again. Closing this issue as fixed.

Feel free to open new issues if you see anything else. :heart: :smile:
