### ISSUE TITLE
Glitchy federation with infosec.exchange

### ISSUE THREAD

**Issue by durka** [hachyderm/community#471]
### Please describe the issue you are seeing.

Hi, I don't know whether this issue is with Hachyderm or Infosec.Exchange. I also know you folks are dealing with a lot right now :heart: just wanted to get this written down since it is so weird.

Look at this toot from a test account I just created in infosec.exchange, then followed with my own: https://hachyderm.io/@aburka@infosec.exchange/110953157354912227

![image](https://github.com/hachyderm/community/assets/47007/f3bfc8ab-845d-422d-89c6-0602baf33c09)

It shows 1 favorite and 1 boost. The favorite is from me. But there is no boost. If you [click on the boost](https://hachyderm.io/@aburka@infosec.exchange/110953157354912227/reblogs) to see who it was, it can't tell you.

Here is the toot on its original instance: https://infosec.exchange/@aburka/110953157338858936

No boost shown in the count or the [list](https://infosec.exchange/@aburka/110953157338858936/reblogs). But it gets weirder! (Here's where the issue might be on both sides or somehow caused by infosec.) It also shows zero favorites, but if you click on that, it [shows](https://infosec.exchange/@aburka/110953157338858936/favourites) my favorite from hachyderm.

I've tested this with [a toot on a third instance](https://hachyderm.io/@roboticist@jawns.club/110953209187110504) and I didn't see any of the same glitchy behavior.

I thought I had seen a video from infosec.exchange that failed to load, but I can't produce an example right now. Videos are so rare, it could have just been another example of #436. I'll update if I happen across one.

### How long have you noticed this issue?

A week?

### What geographic region are you accessing Hachyderm from?

us-east

**Comment by Preskton** [comment]
Hi there, @durka - thanks for reporting. We can take a peek at the db/logs and see what we can see, and please let us know if you observe this with other toots/assets.

**Comment by slamp** [comment]
I made a test and I wasn't able to reproduce the issue 
Post on infosec.exchange: https://infosec.exchange/@slaamp/111730819574938572
Favorited on hachyderm.io 
![image](https://github.com/hachyderm/community/assets/714910/86e3fd78-b76a-4195-8f3f-3bf571d09558)

It shows on infosec.exchange: 
![image](https://github.com/hachyderm/community/assets/714910/4569982b-9bd2-4884-bd78-b594c7de9ab7)

/cc @durka

**Comment by slamp** [comment]
Don't hesitate to re-open the issue if you have the problem again
