### ISSUE TITLE
High latency and timeouts on Hachyderm from home network.

### ISSUE THREAD

**Issue by PeskyPotato** [hachyderm/community#472]
### What would you like to discuss with us or let us know?

Hello, sorry if this isn't the last forum for this, feel free to redirect me elsewhere if so.

Over the last week I've noticed the hachyderm.io has been extremely slow to load on my home internet connection. This doesn't seem to be the case if I visit any other Mastodon server (mastodon.social, infosec.exchange, etc...) on the same connection. The Hachyderm.io website also loads normally on the same clients on a internet connection. Is there anything my home internet connection could do that makes the Hachyderm server timeout? Ocassionaly it loads without an issue but that's about 1 every 10 times, this is replicated through Firefox, Chrome, curl (API endpoints), Tusky and the official Mastodon android app.

Examples:

**Chrome**
![image](https://github.com/hachyderm/community/assets/35942108/7fc7a759-d716-441e-9742-944a02fc7e37)
 
![Screenshot from 2023-08-26 16-20-26](https://github.com/hachyderm/community/assets/35942108/8245bb3a-18a4-48ed-aebd-bd6f8582455d)

**curl**
![Screenshot from 2023-08-26 16-38-30](https://github.com/hachyderm/community/assets/35942108/25935a7f-f7c1-431a-8c10-fc770e71ce27)

**Comment by Preskton** [comment]
Howdy, @PeskyPotato - we haven't made any major changes that I think would play into this.

Is it consistently the `custom.css` that's taking a long time, or are you seeing that with other assets as well?

I will poke at our Frankfurt CDN host (the IPv6 address you're connecting through) and see if there's something up there.

**Comment by PeskyPotato** [comment]
Hi @Preskton, thanks for taking a look!

Here's another screenshot from Chrome network inspector, it's not always `custom.css`. My other Dutch-based network connections (mobile provider and VPS) work, which is how I've been recently accessing hachyderm.io. 
![Screenshot from 2023-08-26 16-46-54](https://github.com/hachyderm/community/assets/35942108/d72e19e7-ca23-48b3-8476-33f266fcda67)

**Comment by PeskyPotato** [comment]
Update: Just switched from IPv6 to IPv4 only on my router it now connects without any timout. I'll continue to monitor it and see to make sure it wasn't just chance.

**Comment by Preskton** [comment]
yup! the thing i was going to poke was the ipv6 stack on our side. let us know if you see things on the v4 side, too!

**Comment by PeskyPotato** [comment]
I've tried switching between v4 and v6 and it seems  the issue has somehow resolved itself. Haven't had and slow load times or timeouts since yesterday, currently working fine and back on v6. 

I can close this issue just to keep your queue clean and re-open only if the same symptoms pop up again. Thank you for the time, have a good weekend. :slightly_smiling_face:
