### ISSUE TITLE
"Explore" is not updating

### ISSUE THREAD

**Issue by joeweiss** [hachyderm/community#476]
### What would you like to discuss with us or let us know?

The Explore feed is not updating, and it looks like the "scheduler" is reporting longer than expected latency on [https://grafana.hachyderm.io/public](https://grafana.hachyderm.io/public).

This happened before and was resolved in #469.

Thanks!

**Comment by slamp** [comment]
1 of the sidekiq is busy.
There is issues with ruby hanging on multiple services, see https://github.com/mastodon/mastodon/issues/23813#issuecomment-1464811126

**Comment by Preskton** [comment]
I *think* this is OK now, as I see recent events on my feed as of today. I'm going to close this for now, but please let us know if you see anything amiss.
