### ISSUE TITLE
“terraform_logo“ custom emoji label is duplicated, causing Mona iOS app crash 

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#477]
### So what emoji are you looking for?

Please see https://mastodon.social/@MonaApp/111018238215000751 — this emoji label is apparently used by two of our custom emojis and needs to be fixed.  Thanks!

**Comment by slamp** [comment]
Yes we have it in double:
https://media.hachyderm.io/custom_emojis/images/000/048/485/original/0322728a36508c9b.png
https://media.hachyderm.io/custom_emojis/images/000/048/486/original/df7af05f3605d83e.png

**Comment by slamp** [comment]
I'm checking if there is other emoji label duplicated

**Comment by slamp** [comment]
I removed one of the entry :terraform_logo: and I added :opentf_logo: instead ;-)
[:opentf_logo:](https://media.hachyderm.io/custom_emojis/images/000/214/270/original/23f02a4f0d068c8d.png)

**Comment by mjf-pro** [comment]
Looks good, thanks for handling!
