### ISSUE TITLE
Specialized Accounts: Hacktoberfest

### ISSUE THREAD

**Issue by MattIPv4** [hachyderm/community#478]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

👋 Hacktoberfest has just launched its 2023 season, and we’ve had quite a few participants already ask us this year about whether we have a presence on Mastodon (we have a presence on X/Twitter and Bluesky, but not everyone is on those). We currently don’t have a presence on Mastodon, but would like to set one up, and were interested in using Hachyderm as our home server, as it would appear that a lot of tech folks seem to be here, including our friends over at GitHub!

Hacktoberfest is a month-long celebration of open-source that runs in October each year. We aim to introduce new folks to open-source for the first time, as well as drive existing contributors to get involved more. We'd be using our profile as a means to advocate for open-source and communicate key updates about the event each year with our following, such as when a new season launches each year, when registration opens, key milestones during the event, and recaps after the event each year.

### How will you ensure the community is protected?

Hacktoberfest is deeply rooted in open-source and community; we understand how important it is to do the right thing for the community and to respect them, and we're very familiar with engaging with the community in a constructive manner, as we do in our Discord server. We'll be using our Hachyderm account to promote open-source and encourage folks to be part of Hacktoberfest and the open-source community, not to spam marketing material on the platform or be a nuisance. We accept the specialized account expectations and absolutely intend to uphold them.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
👋 Hello! We wanted to ping this one: it looks like you haven't created your account yet. In order for the verification process to work, you'll need to first create the @\Hacktoberfest account and then we can add it to the Approvals page. Only then will the verification process work :)

**Comment by MattIPv4** [comment]
Hey! I've created the [account](https://hachyderm.io/@hacktoberfest) now. I didn't create it before as the wording in the [application process](https://community.hachyderm.io/docs/account-types/verification/#the-application-process) implied I should wait for approval first ("If you are approved, you can now create your account").

**Comment by hachyderm-admin** [comment]
Ah! Sounds like we might need to clarify our wording - thank you for your patience and for spinning up the account!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by MattIPv4** [comment]
All set, thank you!

![image](https://github.com/hachyderm/community/assets/12371363/1ba52b66-9359-4b2d-b622-5fa98a3896c0)
