### ISSUE TITLE
Cannot see linuxrocks.online

### ISSUE THREAD

**Issue by Kalankaboom** [hachyderm/community#481]
### What is your question?

Hello !

So I wanted to see posts on [linuxrocks.online](https://linuxrocks.online/), but I can't seem to find them when I search.
Even when searching for a specific user with @user@linuxrocks.online

Is this server blocked ?

Thank you for helping, and thank you for all of your work !

**Comment by hachyderm-admin** [comment]
Hello!

We took a look and linuxrocks.online and we suspended federation with LinuxRocks after a series of reports involving pretty blatant transphobia from the instance.

**Comment by Kalankaboom** [comment]
Thank you very much for your help !
