### ISSUE TITLE
Translate no longer working

### ISSUE THREAD

**Issue by mdbooth** [hachyderm/community#482]
### Please describe the issue you are seeing.

The Megalodon app shows me a Translate button on non-English posts. I believe this is implemented by Hachyderm. If not, apologies for the noise!

Until recently this worked fine, but now clicking Translate just gives "Remote data could not be fetched".

Example non-English post: https://mastodon.social/@xahteiwi/111053199481110484

### How long have you noticed this issue?

2 or 3 days

### What geographic region are you accessing Hachyderm from?

UK

**Comment by Preskton** [comment]
Howdy, @mdbooth! Sometimes LibreTranslate doesn't return the most descriptive status codes - e.g. it returns a 5xx when the language isn't supported. Happy to take a look and see what's going on, and thank you for the sample Toot to test with!

**Comment by Preskton** [comment]
Again, thank you for reporting @mdbooth - I was able to poke at some things in the backend to get Libretranslate going again. 

I'm not 100% on the initial cause for this going down, but I have a working theory around some system updates we did, `tailscale`, ephemeral keys, and lost connections.

Please retry and let us know how it goes -- and reopen if you run into trouble.

**Comment by mdbooth** [comment]
Thanks for the speedy response. All working now!
