### ISSUE TITLE
Update of Home Assistant logo

### ISSUE THREAD

**Issue by slamp** [hachyderm/community#483]
### So what emoji are you looking for?

With the 10th anniversary of Home Assistant, there is a new logo
https://www.home-assistant.io/blog/2023/09/17/a-refreshed-logo-for-home-assistant/ 
The purpose of this US is to update the logo to the new one.
Download here https://design.home-assistant.io/#brand/logo 
shortcode :homeassistant:

**Comment by hachyderm-admin** [comment]
Uploaded as :home_assistant: so it wouldn't conflict with :homeassistant: (and also for accessibility). We'll need to do some backend work so that the old logo is renamed with "legacy" or similar (this cannot be done via the UI).
