### ISSUE TITLE
Pour-over coffee emoji request

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#485]
### So what emoji are you looking for?

![IMG_1984](https://github.com/hachyderm/community/assets/119645526/cb6bcac8-6635-4524-b50b-416eb3ec7bdd)

OMG how do we not have this one yet? 😃. Please add.  Saw it in one of Stux’s recent posts… link: https://mstdn.social/@stux/111109543880432356

Thanks!

**Comment by hachyderm-admin** [comment]
:pour_over_coffee: now added - thank you for your patience!
