### ISSUE TITLE
Default & Ingress queues are beet red

### ISSUE THREAD

**Issue by mjf-pro** [hachyderm/community#486]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
2. When are you seeing the issue? When you are submitting posts? Uploading media?
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.

Please note that if there are issues with individual apps or with Mastodon core that
we can work with you to determine that to be the case, but we can not fix third party apps
and do not directly contribute to the Mastodon project at this time.

### How long have you noticed this issue?

15-30 minutes

### What geographic region are you accessing Hachyderm from?

South central USA

### Is there anything else that we should know?

Screengrab from Grafana Wednesday, September 27, 2023 at 8:34 PM CDT:

![IMG_2028](https://github.com/hachyderm/community/assets/119645526/34d123b1-ca4f-414b-b0f0-965a7e0e9050)

**Comment by Preskton** [comment]
So these are actually within acceptable operating parameters - < 250 msec for these is not bad. We can probably improve the scale so that it doesn't look so scary!

**Comment by Preskton** [comment]
Actually, after digging at this a bit more, we found that sidekiq metrics in general are not flowing. It looks like there was a change in `v4.2.0` with how these metrics get reported -- we are discussing w/ the mastodon team.

For now, will close this issue as the dashboards have been updated with new "redline" values. We are tracking the metrics collection in an internal GH issue.

**Comment by mjf-pro** [comment]
I was wondering.... hadn't seen them moving at all!  Thanks for looking into it.

-Michael
________________________________

**Comment by Preskton** [comment]
And we've re-enabled the sidekiq metrics!

**Comment by mjf-pro** [comment]
:ablobfoxheartcute:

-Michael Fisher

On Oct 4, 2023, at 10:07 AM, Preston Doster ***@***.***> wrote:

﻿

And we've re-enabled the sidekiq metrics!

**Comment by Preskton** [comment]
fyi edited our comments b/c i didn't realize GH included the full email body, lol.
