### ISSUE TITLE
Translation quality

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#487]
### What would you like to discuss with us or let us know?

It seems, that the translation quality of LibreTranslate is significantly worse than DeepL. But lately in most cases LibreTranslate is used for translation.

What is the reason, that LibreTranslate is used much more often than DeepL?

**Comment by Preskton** [comment]
Hi, there, @blueturtleai - we chose LibreTranslate as it was relatively easy to install/maintain. We aren't currently running DeepL in our infra, so no translation requests that flow through Hachy would be translated that way.

Thank you for the feedback - I wasn't aware of the differences in translation quality between the two - noted for future eval. 👍🏽

**Comment by blueturtleai** [comment]
Great, thanks

**Comment by blueturtleai** [comment]
The downside of DeepL is, that you can’t host it yourself and have to pay for API usage.
