### ISSUE TITLE
Specialized Accounts: ProjectJupyter

### ISSUE THREAD

**Issue by blink1073** [hachyderm/community#488]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

Project Jupyter is a non-profit, open-source project.  We provide software, open standards, and web services for interactive computing across all programming languages.

https://jupyter.org/about

### How will you ensure the community is protected?

Project Jupyter has its own [Code of Conduct](https://jupyter.org/governance/conduct/code_of_conduct.html) and [Diversity and Inclusion Working Group](https://jupyter.org/governance/list_of_standing_committees_and_working_groups.html#diversity-equity-and-inclusion).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

If we do use a bot, it would be to promote entries on our [Jupyter Blog](https://blog.jupyter.org/), which typically has less than 10 entries per month.  We would maintain the code for the bot ourselves.

**Comment by blink1073** [comment]
I've created the account and a PR against our website for verification: https://github.com/jupyter/jupyter.github.io/pull/741

**Comment by hachyderm-admin** [comment]
👋 Thank you for your patience!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by blink1073** [comment]
Done, thank you very much!

**Comment by hachyderm-admin** [comment]
Hello! We noticed the link wasn't highlighted in green on your profile. Most likely this means it didn't find the link on our Approvals page when added for some reason - in order to have the link highlight in green, please remove / re-add it. This will trigger the server to try and re-validate it. (We verified that your account is on our Approvals page and re-ran the GitHub Action, just in case.)

**Comment by blink1073** [comment]
I removed and re-added, and it looks good to me

<img width="343" alt="image" src="https://github.com/hachyderm/community/assets/2096628/90ddde66-6ef6-45f5-a1e4-42c212a51ab8">
