### ISSUE TITLE
Add Neofox emojis

### ISSUE THREAD

**Issue by valentinegb** [hachyderm/community#489]
### So what emoji are you looking for?

I *LOVE* the Neofox emojis- I keep seeing them around on Mastodon, but they’re not on Hachyderm so I can’t send any of them myself. I would be very very happy if they were added! Here’s the link to its website: https://volpeon.ink/projects/emojis/neofox/

**Comment by hachyderm-admin** [comment]
So cute! We'll take a look at these and update here :D

**Comment by valentinegb** [comment]
v1.3 has been released and it should be easier to import into Mastodon now!

**Comment by slamp** [comment]
Let's see if it's easy to import them

**Comment by hachyderm-admin** [comment]
Reassigning to Infra for support to add via CLI

**Comment by Preskton** [comment]
Howdy, folks - in honor of the ~1 year anniversary of this ticket, we uploaded both neofox and neocat. :)
