### ISSUE TITLE
PROPOSED RULE: Bot Accounts on Hachyderm Must Be Approved By the Admins

### ISSUE THREAD

**Issue by benwis** [hachyderm/community#49]
I believe it would be nice to have bot accounts that serve a useful function hosted on hachyderm, while still allowing people to opt out of them. In addition, we should create an approval process for these bots. In the meantime, bots that are not approved are prohibited. Rule seems fairly straightforward:

"Bot accounts not approved by admins are prohibited"

Process for approval is up for discussion, I would imagine a public design document would need to be posted and a requirement that they identify themselves and follow our other rules.

**Comment by untitaker** [comment]
>while still allowing people to opt out of them.

What's the problem with just not following the bot account? Perhaps the problem is with bots who actively mention people without them following the bot.

**Comment by benwis** [comment]
Bots hosted on our instance will show up in your Local timeline regardless if you follow them or not. Not following will keep them out of your Home timeline though.

**Comment by pezhore** [comment]
Is this a problem right now @benwis or are we trying to get ahead of a potential issue? I'm still learning how the culture of hachyderm is shaping up and I'm fine with rules/guidance as to what is and is not permitted, but perhaps bots could fall under existing spam rules until the admins/community find that a more granular approach is necessary?

**Comment by untitaker** [comment]
it seems it would be useful to require that bots post unlisted. i can see similar arguments for corporate accounts btw

**Comment by benwis** [comment]
> Is this a problem right now @benwis or are we trying to get ahead of a potential issue? I'm still learning how the culture of hachyderm is shaping up and I'm fine with rules/guidance as to what is and is not permitted, but perhaps bots could fall under existing spam rules until the admins/community find that a more granular approach is necessary?

This isn't really a problem right now. I can definitely ban bots with the spam rules in place. What I'm looking to do here is define an explicit ban with a path to approval. I can see helpful bots being a benefit to the community if setup right.

**Comment by grenierdx** [comment]
Isn't this already covered in the section on account types? https://github.com/hachyderm/community/blob/main/accounts/README.md#can-i-create-a-bot-account

It could potentially be more explicit.

**Comment by quintessence** [comment]
This is closed - we have updated our Bot Account section.
