### ISSUE TITLE
Re-federate respublicae.eu

### ISSUE THREAD

**Issue by caesar** [hachyderm/community#490]
### What domain(s) need to be added or removed from our blocklist?

I'm looking at migrating to Hachyderm but while perusing your blocklist I noticed that respublicae.eu is blocked for being a Twitter bridge.
I came across #403 which suggests it was defederated as part of a purge of dead or non-responsive bridges, but in fact it is live and active.

respublicae.eu is an instance which maintains a curated set of mirrors of the Twitter accounts of EU officials and institutions, and it's of vital importance for EU citizens on Mastodon who want to be able to follow their elected representatives who haven't yet moved off Twitter. I would appreciate it if you would consider removing it from your blocklist. Thanks!

**Comment by hachyderm-admin** [comment]
Hello and sorry for the delay here! We've re-federated with respublicae.eu . Please let us know if there's anything else we can do to assist.
