### ISSUE TITLE
Join the Cult of the Party Parrot

### ISSUE THREAD

**Issue by CoffeeCoder1** [hachyderm/community#492]
### So what emoji are you looking for?

![Partying Parrot](https://cultofthepartyparrot.com/parrots/hd/parrot.gif)
https://cultofthepartyparrot.com/

**Comment by slamp** [comment]
Should we add this one ?

**Comment by hachyderm-admin** [comment]
Thanks for the suggestion. At this time we are closing this ticket. We may reevaluate in the future if there is more interest.
