### ISSUE TITLE
@summitpgh

### ISSUE THREAD

**Issue by jhlunde** [hachyderm/community#493]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Community Event

### How do you fit in with the community?

I have had my personal account on Hachyderm for some time and appreciate the commitment to careful moderation and general social justice.

I volunteer on the planning committee for the Pittsburgh Racial Justice Summit. It is an annual conference for Pittsburgh organizers, held at the Pittsburgh Theological Seminary. The Summit creates opportunities for attendees to learn, connect, and act on behalf of racial justice. 

In the past we used Twitter, but that platform is degenerating and is no longer where we are likely to find people interested in our mission.

The 26th Summit will be January 19th and 20th, 2024. This account will be active through the Summit, and then probably go fairly quiet until next November.

https://prjs.org/

The full name "Pittsburgh Racial Justice Summit" is too long for a username, or even a display name. I chose @justicepgh because we have used that on other social media platforms.

### How will you ensure the community is protected?

The account will most likely only be updated by [@unicorndeburgh](https://hachyderm.io/@unicorndeburgh)

You can check my past posts to see how I interact online.

If we get good engagement, Kevin Jarbo may also log in to do updates. https://www.cmu.edu/dietrich/sds/people/faculty/kevin-jarbo.html

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
Hello!

Apologies for the extreme delay here, we were reviewing this request. Typically we restrict our event / specialized accounts to be tech focused, but that said we agree with your mission and decided to proceed :)

This means you've been added to the Approval page 🎉  Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by jhlunde** [comment]
Thanks!
