### ISSUE TITLE
Hachyderm seems to be down 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#494]
### Please describe the issue you are seeing.

![IMG_4634](https://github.com/hachyderm/community/assets/113246030/bf74db97-3bf6-4202-91ac-a63f4ec11d72)

### How long have you noticed this issue?

15 minutes

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by ollien** [comment]
Looks like there's ongoing database maintenance. I'm sure it will be up soon :)

**Comment by blueturtleai** [comment]
Was there anywhere an announcement I missed?

**Comment by ollien** [comment]
Scroll down on the status page!

**Comment by blueturtleai** [comment]
Thanks, got it! Tbh, I would have expected an announcement before for example via the hachyderm Mastodon account.
