### ISSUE TITLE
Specialized Accounts: flydotio

### ISSUE THREAD

**Issue by tqbf** [hachyderm/community#497]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

We want to be an example of what a positive and mutually beneficial corporate presence on the Fediverse should look like.

(We stole this from Tailscale's ticket).

We agree to the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant)

### How will you ensure the community is protected?

We agree to follow the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant) (and further believe we'd meet those expectations even if they weren't laid out so handily for us, because we're fussy about this stuff). 

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A, exclusively human posting.

**Comment by hachyderm-admin** [comment]
👋 Thank you for your patience!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by tqbf** [comment]
Looks like we're all set! Thanks!
