### ISSUE TITLE
Specialized Accounts: golang

### ISSUE THREAD

**Issue by dr2chase** [hachyderm/community#500]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

This is for the corporate-sponsored-OSS Go programming language ("golang").  Obviously we are corporate sponsored (Google LLC) and use the single-copyright-owner model, but also have a forkable open source license, and have had a [code-of-conduct](https://go.dev/conduct) for years.  Our policies are influenced by our sponsor (for example, concerns about supply chain security and both outsider *and insider* risk result in a 2-Google-employee approval requirement for every CL) but by default we welcome all contributors, including actual corporate competitors, and many of them have made valuable and even vital contributions to the Go project.

Beyond that, we try, we course-correct, and our error rate remains tolerable (in my opinion).

### How will you ensure the community is protected?

The account password credentials will reside in authentication-protected access-audited storage (using the within-Google default mechanism for protecting such secrets) so random use of the account shouldn't be a problem.  The notes there will include use restrictions (for example, a link to Hachyderm's [specialized accounts rules](https://community.hachyderm.io/docs/account-types/#specialized-accounts)).  There is also an automated post that accompanies releases (major, minor, and security), and those credentials are [stored in Google Cloud Platform Secret Management Service](https://github.com/golang/build/tree/master/internal/secret).

To prevent advertising creep, unlike the Twitter golang account, we won't share the keys with a social media team outside of the Go project, and we'll document this in the key notes.

The Go code-of-conduct of course applies to anything posted to this account.

I expect a posting rate of about once per week on average, unlikely to exceed twice per week for a while, but it could grow as we figure out Mastodon and its community.

Topics:
- (automated) release announcements, including security releases and monthly dot  release (1-2 per month).
- blog post announcements https://go.dev/blog/ (1-5 per month).
- example/perhaps "go package of the month".
- example/perhaps pointers to proposals where we want feedback.
- presumably there will be stray interactions initiated by other people, I expect our standard response will be to redirect them to other channels (github issues, usually).

Anti-topics that should not appear:
- (from the Twitter Golang account) "coming soon at Google Cloud Next!!!! (something something Go-related)".
- language wars.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

The current social-media-posting bot ([formerly targeting Twitter](https://github.com/golang/build/blob/master/internal/task/tweet.go)) is run under human control with authentication hurdles, and only runs as part of the human-controlled [Go release process](https://github.com/golang/build/tree/master/internal/relui), so it is unlikely to become disruptive.  I expect that if/when blog-post announcements are automated, that will share code and authentication, and also always have a human in the loop.

**Comment by hachyderm-admin** [comment]
👋 Thank you for your patience!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by hachyderm-admin** [comment]
Once complete, the URLs should be verified (green) similar to what you see on Tailscale's account:

https://hachyderm.io/@tailscale

**Comment by dr2chase** [comment]
Should I see the string "golang" anywhere on the approval page?  I looked, including at the page source, but did not find it.
I am looking at `https://community.hachyderm.io/approved/`

**Comment by dr2chase** [comment]
ping?

**Comment by hachyderm-admin** [comment]
Sorry about that! I don't know why it didn't show, but we re-ran the GitHub Action and Golang is there now (under The Go Language).

**Comment by dr2chase** [comment]
Done, works, thanks!
