### ISSUE TITLE
Federating with fox.gal

### ISSUE THREAD

**Issue by tinyfluffs** [hachyderm/community#505]
### What domain(s) need to be added or removed from our blocklist?

Hiya,

Not sure if federation was broken for a while, as I've had a server outage. This is a personal instance I run for myself. Can you check that activity is being sent to my server? I have made a follow request or two, but it doesn't appear to be sending it the other way.

Domain: **fediserv.fox.gal** _(displays as fox.gal)_

Let me know if there's anything I need to adjust on my end. I've got a few friends on this instance I would like to keep up-to-date with.

Thanks!
[@tinyfluffs@fox.gal](https://fediserv.fox.gal/@tinyfluffs)

**Comment by hachyderm-admin** [comment]
Hello!

There shouldn't be any issues on our end with fox.gal. As of right now, there aren't any restrictions on the instance (i.e. it's not limited or silenced). 

When you say that you've made a follow request or two but it doesn't appear to send the other way, can you clarify?

**Comment by tinyfluffs** [comment]
Hiya, 

I think this got resolved, don't worry. Will re-open if I need anything!
