### ISSUE TITLE
Many "Rate limited" messages during normal usage

### ISSUE THREAD

**Issue by cvennevik** [hachyderm/community#506]
### What would you like to discuss with us or let us know?

I've experienced this issue now for the last week in the web UI. It usually starts after I've been using it for a little while.

When it starts, messages pour in so they cover my screen with two to five identical messages at a time, and continue until the given time to wait for. It has started while browsing the main timeline and while composing messages.

It gets very annoying, especially while composing messages, because the messages stack high enough to cover the text I'm writing, despite me not doing anything. I guess the web UI does a lot of polling by default?

Note: I _may_ not have a Hachyderm tab open on my home computer, which may or may not have woken itself from sleep mode while I've been away on holiday. Can check when I get home tonight.

Using Firefox 121 for Android, from Norway.

![Screenshot_20231230-074001](https://github.com/hachyderm/community/assets/90956290/e2c2c317-52b4-4a5d-93dd-10e3360bf28f)

**Comment by cvennevik** [comment]
Update: No tabs were open at home. Alternatively, I may have had two tabs of Mastodon open on my phone at times (keeping one post open while exploring elsewhere). I'd hope this should not be enough to trigger rate limiting?

**Comment by Preskton** [comment]
Howdy, @cvennevik we are taking a look into this. This morning we set up some additional logging capture to better look for this condition. 

The next time you notice this, could you please let us know the date and approximate start/end time in UTC? This will help us narrow down your particular case, and to see if it's lining up with others.

In the meantime, we'll keep looking at incoming logs to see what we can see - the main pattern I'm observing right now is occasionally there are actors who spam certain endpoints and might be "stealing" capacity from others.

**Comment by cvennevik** [comment]
Great to hear, @Preskton! I do not use Mastodon so much now that my holiday is over, so there won't be as many chances for this to happen, but I will keep an eye out.

**Comment by hachyderm-admin** [comment]
Closing issue as it seems to have been resolved. Please open as a new issue if the messages reappear. Thank you!
