### ISSUE TITLE
Add R statistical programming language :rstats:

### ISSUE THREAD

**Issue by jimgar** [hachyderm/community#507]
### So what emoji are you looking for?

Hi, it would be awesome to have an R emoji. Our community has long used `rstats` as the phrase of choice.

Thanks for your consideration 🙂

![IMG_9939](https://github.com/hachyderm/community/assets/90831652/8eeb654c-ba05-4e7a-9070-461721705a12)

**Comment by slamp** [comment]
I'll take care of this one

**Comment by slamp** [comment]
https://media.hachyderm.io/custom_emojis/images/000/280/831/static/7170a357885a37ee.png
:rstats:
