### ISSUE TITLE
TechHub needs to ask a moderation question 

### ISSUE THREAD

**Issue by RockstarRaccoon** [hachyderm/community#509]
### What is your question?

Have a report here which seems incomplete, but potentially serious.  Need to be reached back to, cannot find a contact within Fedi.

Whichever moderator is available to deal with the recent report against a user at TechHub.Social, please PM me ASAP at @Raccoon@TechHub.social, and CC @Nicdex@TechHub.Social.

Thanks!

**Comment by hachyderm-admin** [comment]
Hi @RockstarRaccoon, Thanks for reaching out. We sent a PM your way.
