### ISSUE TITLE
Add “how to report issues” on About page

### ISSUE THREAD

**Issue by pcantrell** [hachyderm/community#51]
Consider adding a “How to report issues” section to https://hachyderm.io/about/more that includes a direct link to https://github.com/hachyderm/community/issues . The existence of this community issue tracker was a happy new discovery to me  after today’s community announcement — and while I suspect I may be unusually thick-headed, I’m sure other people are similarly unaware this channel.

There is already a link to https://github.com/hachyderm/community on that page, it’s true, but I’m not sure it makes the issue tracker sufficiently discoverable: searching the about page for “issue” or “report” comes up blank, and it takes some careful reading to realize that “Community Docs” or “We manage our community” refers to reporting problems.

**Comment by quintessence** [comment]
Will do :) 

Tagging nova and the other mods isn't usually useful as our mentions do get overwhelmed :) Adding the info to our About page. It's also in the Community repo, but you do need to know to get there to see it first which I realize is a bit of a problem :)
