### ISSUE TITLE
Specialized Accounts: @status_updates

### ISSUE THREAD

**Issue by johnl** [hachyderm/community#517]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Curated Content Account

### How do you fit in with the community?

A tech focused parody account that purports to be a non-specific online service that is always failing for increasingly more ridiculous reasons.

Currently on mastodon.social but moving due to hachyderm friends expressing concerns about how mastodon.social enables abuse.

### How will you ensure the community is protected?

Everything is posted manually by one person (me) and I'll ensure all the rules are followed (all of which I've read and agree with).

And I'm mindful that we don't ever appear to be associated with the hachyderm server itself so will be careful to avoid such confusion.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
👋 Thank you for your patience!

You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by johnl** [comment]
Thanks!
