### ISSUE TITLE
Unable to redirect account to self-hosted fediverse instance

### ISSUE THREAD

**Issue by avdi** [hachyderm/community#519]
### What would you like to discuss with us or let us know?

I'm trying to redirect my profile to new self-hosted Fediverse instance `avdi@avdi.codes` (Wordpress with the ActivityPub plugin). I can _follow_ that account from Hachyderm:

![image](https://github.com/hachyderm/community/assets/982/7dad81c8-adf5-4cb7-a708-03466e5ba170)

...but when I enter it as the redirect target, I get a "could not be found" error. 
![image](https://github.com/hachyderm/community/assets/982/bbb1edc8-a441-400e-8eb8-db586f2108f6)

**Comment by avdi** [comment]
`@avdi@avdi.codes` also doesn't work.

**Comment by hachyderm-admin** [comment]
Hello! 


The domain avdi.codes isn't limted or suspended by the Hachyderm instance, so it should federate / behave normally. Do you see any other error messages? Have you checked for any error messages on your self hosted instance as well?

**Comment by avdi** [comment]
> Hello!
> 
> The domain avdi.codes isn't limted or suspended by the Hachyderm instance, so it should federate / behave normally. Do you see any other error messages? Have you checked for any error messages on your self hosted instance as well?

I'm not sure what to look for - what does the redirect look for on the "TO" account in order to decide that it's "found"?

**Comment by avdi** [comment]
What's odd is that I can _follow_ my other account from Hachyderm, so it seems like the follow code finds it but the redirect code treats it as invalid 🤔

**Comment by avdi** [comment]
Example webfinger query for that account: 

```
$ curl -s https://avdi.codes/.well-known/webfinger?resource=acct:avdi@avdi.codes | jq
{
  "subject": "acct:avdi@avdi.codes",
  "aliases": [
    "acct:avdi@avdi.codes",
    "https://avdi.codes/author/avdi/",
    "https://avdi.codes/author/avdi/",
    "https://avdi.codes/@avdi"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "href": "https://avdi.codes/author/avdi/",
      "type": "text/html"
    },
    {
      "rel": "http://webfinger.net/rel/avatar",
      "href": "https://secure.gravatar.com/avatar/370d993f1539b0abc2ff1db87390bb75?s=96&#038;d=mm&#038;r=g"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "href": "https://avdi.codes",
      "type": "text/html"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://avdi.codes/author/avdi/"
    }
  ]
}
```

**Comment by avdi** [comment]
I worked it out: it requires the target to show the include Hachyderm user URL as an alias in webfinger results
