### ISSUE TITLE
Provide list of approved corporate accounts per the corporate covenant policy

### ISSUE THREAD

**Issue by kaniini** [hachyderm/community#52]
Hi!

It would likely be helpful to the fediverse community at large if a list of corporate accounts was published and kept up to date.  This would be helpful for a few reasons:

1. It would enable the people who don't want brands in their community to exclude those accounts in an automated fashion.
2. It would enable people who love brands to have a nice list of brands they can follow (not my thing but you never know right?)
3. It would enable the people who want to curate their federated timelines to remove the brands from that timeline in automated fashion.
4. In the case of communities using software like Pleroma, it could be used to add additional identifiers to the accounts designating that they are brands, etc.

Doing so is likely to reduce the temperature regarding some of these conversations that have come about as a result of the corporate account policy as well, since it allows admins to feel like they have more control over how their communities engage with the brand accounts.

Thanks for considering this suggestion!

**Comment by quintessence** [comment]
This is a great suggestion - I've added it to our internal tracker for documentation and will update here when complete.

**Comment by quintessence** [comment]
List is now online :) 

https://github.com/hachyderm/community/blob/main/accounts/corporate-accounts.md
