### ISSUE TITLE
Unable to move to a new account

### ISSUE THREAD

**Issue by avdi** [hachyderm/community#520]
### What would you like to discuss with us or let us know?

This is a follow-on to #519. In that ticket, I was unable to install a redirect to my self-hosted account `avdi@avdi.codes`. I resolved that issue by ensuring that webfinger at that instance listed my hachyderm account URLs as aliases. I was then able to turn on redirection.

However, I am now trying to do a full account move, and running into the exact same issue as before. I _have_ set up the needed aliases at the target, and Hachyderm sees `avdi@avdi.codes` as a working foreign account (I can follow it, reply to it, etc) so I'm not sure what else is needed?

![image](https://github.com/hachyderm/community/assets/982/dc27b54d-3537-4b56-a8ad-54b4dc44fe31)

**Comment by avdi** [comment]
More info...

I can see in the Apache logs that Hachyderm is checking the target account whenever I attempt the account move:

```
142.132.128.70 - - [09/Apr/2024:22:04:59 +0000] "GET /.well-known/webfinger?resource=acct:avdi@avdi.codes HTTP/1.1" 200 1283 "-" "http.rb/5.1.1 (Mastodon/4.2.8; +https://hachyderm.io/)"
```

Reproducing that request with curl:

```
$ curl -s https://avdi.codes/.well-known/webfinger?resource=acct:avdi@avdi.codes | jq
{
  "subject": "acct:avdi@avdi.codes",
  "aliases": [
    "acct:avdi@avdi.codes",
    "https://avdi.codes/author/avdi/",
    "https://hachyderm.io/@avdi",
    "https://hachyderm.io/users/avdi",
    "acct:avdi@hachyderm.io",
    "https://avdi.codes/author/avdi/",
    "https://avdi.codes/@avdi"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "href": "https://avdi.codes/author/avdi/",
      "type": "text/html"
    },
    {
      "rel": "http://webfinger.net/rel/avatar",
      "href": "https://secure.gravatar.com/avatar/370d993f1539b0abc2ff1db87390bb75?s=96&#038;d=mm&#038;r=g"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "href": "https://avdi.codes",
      "type": "text/html"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://avdi.codes/author/avdi/"
    }
  ]
}
```

As you can see, hachyderm is now back-linked as an alias in three different forms:

```
    "https://hachyderm.io/@avdi",
    "https://hachyderm.io/users/avdi",
    "acct:avdi@hachyderm.io",
```

What else is required to cause it to be "found" as a valid move target?

**Comment by avdi** [comment]
Update: After doing a bunch of cache debugging, I've managed to get to a new error:

![image](https://github.com/hachyderm/community/assets/982/2038be5f-9aa9-4468-9537-e26504d48dc1)

The error is now that 'avdi@avdi.codes' "is not an alias of this account".

The current alias list includes:

```
    "https://hachyderm.io/@avdi",
    "https://hachyderm.io/users/avdi",
    "acct:avdi@hachyderm.io",
```

What other back-alias do I need to add to satisfy Mastodon's requirements for migration?

**Comment by avdi** [comment]
According to my local tests with the Mastodon code, my canonical Hachyderm URL should be `https://hachyderm.io/users/avdi`. But that is included in my aliases on avdi.codes and Hachyderm is still rejecting it as "not an alias" 🤔

**Comment by avdi** [comment]
I have finally succeeded. For future adventurers, the the final piece was to modify the activitystreams output of my new profile URL at: https://avdi.codes/author/avdi/

To include:

```json
'alsoKnownAs': ['https://hachyderm.io/users/avdi']
```

As far as I can find this is documented nowhere other than the Mastodon source code.

**Comment by hachyderm-admin** [comment]
Thank you for posting all the information here and great catch - we hadn't seen this before either.
