### ISSUE TITLE
Specialized Accounts: netobserv

### ISSUE THREAD

**Issue by jotak** [hachyderm/community#521]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

[NetObserv](https://github.com/netobserv/network-observability-operator) is an open-source project that certainly falls under [the definition](https://community.hachyderm.io/docs/account-types/open-source-accounts/) of hachyderm's corporate accounts given that maintainers are currently all Red Hat / IBM people and the project being "productized" by Red Hat.
NetObserv is a network observability tool for Kubernetes.
We plan to use this account for sharing news about NetObserv to the tech community, such as release announcements and walk-through, technical blogs, presence in conferences, etc. This account may also be advertised as a conversation channel for the community to engage with the team and have Q&A. We are definitely *not* going to push repetitive content or anything close to spam. This isn't a marketing account.

### How will you ensure the community is protected?

NetObserv is maintained by people at Red Hat with a long tradition of involvement in open-source, respectful with the community and other players in the field, and welcoming diversity. We will of course follow the community rules and specialized accounts expectations.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by jotak** [comment]
(PS: I created the @netobserv account ... not sure if I had to do that)

**Comment by jotak** [comment]
We agree to the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant)

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by hachyderm-admin** [comment]
Hello @jotak ! Did you have a chance to do this yet?

**Comment by jotak** [comment]
sorry, was on holidays ... checking that right now, thanks! :-)

**Comment by jotak** [comment]
done, thank you!
