### ISSUE TITLE
Specialized Accounts: OrnithopterHosting

### ISSUE THREAD

**Issue by unusualevent** [hachyderm/community#527]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

Ornithopter Hosting is a Linux and open-source specific small business. We value lasting partnerships, communities, an ethical journey, sustainable growth, and embracing being different.

We hope to use this account to post something like a monthly business update, tutorials, maybe discounts - so maybe once a week, no more than once a day. Our own words, not repeating, etc etc.

### How will you ensure the community is protected?

We will work to do right by Hachyderm and its users, and to uphold Hachyderm values. Ornithopter Hosting agrees to follow the Hachyderm rules & additional [specialized account expectations](https://community.hachyderm.io/docs/account-types/covenant).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A - only human posting for now. If that changes in the future I'll ask your infra team for advice, will probably use an in-memory key.

**Comment by unusualevent** [comment]
Per the email discussion that account's at https://hachyderm.io/@OrnithopterHosting as requested

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by unusualevent** [comment]
Thanks folks!
