### ISSUE TITLE
Update to 3.5.5?

### ISSUE THREAD

**Issue by sindarina** [hachyderm/community#53]
What's the plan for updating to 3.5.5? I am aware that the discovered security issue is primarily a Glitch problem, but right now we're still on 3.5.3, and as far as I can tell there has been no communication about whether an update is planned, and if so, when? If it's not needed, then posting something about that would be great too, since it answers the question, can be referred to, etc.

Proactive communication about this would be much appreciated. Thanks!

**Comment by missingcharacter** [comment]
I believe it would follow a similar pattern as:
- https://github.com/hachyderm/community/issues/48#issuecomment-1319115109
- https://github.com/hachyderm/community/issues/39

**Comment by ThePowerOfDreams** [comment]
4.0.2 would be preferable as it adds ~~toot~~ post editing and translation.

**Comment by quintessence** [comment]
Closing - we updated to 4.0.2 this morning :)
