### ISSUE TITLE
Still having trouble following from qoto

### ISSUE THREAD

**Issue by sgryphon** [hachyderm/community#531]
### What would you like to discuss with us or let us know?

I check back every now and then to see if things are working. My main account is on qoto.org and I am still having trouble following users on hachyderm.io.  Qoto is no longer listed in the limited or suspended server list, but was in the past.

See similar issues that was fixed for an individual user: https://github.com/hachyderm/community/issues/448

I can follow accounts from many other servers, but when I try to follow accounts on hachyderm.io initially it looks like it succeeds, but then it change status to Awaiting Approval and never actually follows.

Some of the accounts I have been trying to follow:

udidahan@hachyderm.io
damianedwards@hachyderm.io
davidfowl@hachyderm.io
brendankowitz@hachyderm.io

My account on qoto is sgryphon@qoto.org

This could be a symptom of the previous blocking, and that I tried to previously follow these accounts and so they are stuck (similar to the #448 issue). The only other thing I can think of is hachyderm has a more up to date version (4.2.8) whereas qoto is stuck on a variant version of 3.2.1

**Comment by hachyderm-admin** [comment]
Apologies for the delay! We were able to partially automate some of the fixes for the qoto issue, but did need to fix some individual users as you saw. We took a look and you should now be able to follow Hachyderm users - can you verify? Thank you!

**Comment by sgryphon** [comment]
Looks like it is fixed (for me). Thank you.
