### ISSUE TITLE
Optional theme request for Tangerine UI

### ISSUE THREAD

**Issue by janvhs** [hachyderm/community#533]
### What is your suggestion?

Hi, I would love to see the adoption of the [Tangerine UI theme](https://github.com/nileane/TangerineUI-for-Mastodon) by Niléane ( @nileane ) as an optional theme. It provides a really nice user experience, is adopted by a lot of instances and supports the advanced user interface. Furthermore, it is really well maintained and provides support for multiple releases of Mastodon.

Our version (4.2.9) is supported by the legacy branch, and once we move to and up-to-date version, we could simply adopt the main branch.

Here are some screenshots:

- ![Tangerine variant](https://github.com/nileane/TangerineUI-for-Mastodon/raw/main/art/Screenshots/TangerineUI-tangerine.png)
- ![Purple variant](https://github.com/nileane/TangerineUI-for-Mastodon/raw/main/art/Screenshots/TangerineUI-purple.png)
- ![Cherry variant](https://github.com/nileane/TangerineUI-for-Mastodon/raw/main/art/Screenshots/TangerineUI-cherry.png)

Thank you for the consideration and have a nice day :D

**Comment by shawnthroop** [comment]
Colors +1 Bottom tab bar +1

**Comment by hachyderm-admin** [comment]
Btw this hasn't been forgotten! We're still reviewing in the context of other updates.

**Comment by slamp** [comment]
I'm fan of the tangerine them (orange on black) !

**Comment by hachyderm-admin** [comment]
Great idea - we'll (mods) make sure the Infra teams sees it :) Will first need to see how the upgrade itself goes, as it's more involved than most.

**Comment by Preskton** [comment]
Heya, @Avakining @shawnthroop @janvhs  if you didn't notice yet -- and apologies for the late notice -- we installed the Tangerine themes over the past few days!

We also created some automation so it shouldn't be a big deal for us to keep these up to date in the future.

Thanks for hanging with us on this one! <3
