### ISSUE TITLE
Translation service not available 

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#535]
### Please describe the issue you are seeing.

Since yesterday translating a post doesn’t work any longer. I’m using the icecubes app and get the error message „Translation service of your instance couldn’t be reached.“. I tried it on another instance and it worked without a problem. So it’s definitely not  an app problem.

### How long have you noticed this issue?

48 hours

### What geographic region are you accessing Hachyderm from?

West Europe

**Comment by hachyderm-admin** [comment]
Hello!

Apologies for the delay - there was some work done over the weekend on setting up a test node in Asia to improve connectivity there. While it _shouldn't've_ impacted this, it may have. Can you confirm if this is still an issue? Please and thank you!

**Comment by blueturtleai** [comment]
Hi! The problem still exists.

**Comment by blueturtleai** [comment]
It’s working now again. Thanks!
