### ISSUE TITLE
Very slow responses

### ISSUE THREAD

**Issue by llimllib** [hachyderm/community#536]
### Please describe the issue you are seeing.

A couple questions to help you get started:
1. Are you seeing error codes? If so please include the full error message and,
if it makes sense to, a screenshot.
- Most requests seem to be succeeding, but painfully slowly. Some time out
2. When are you seeing the issue? When you are submitting posts? Uploading media?
- Just trying to browse my account with elk
3. Is the issue only happening in certain circumstances?
   For example, only for uploading certain file sizes, or only when using a specific
   browser / 3rd party app. If so,  please include which and what versions.
- no, not as far as I know

Here's some requests from elk.zone:

<img width="736" alt="image" src="https://github.com/hachyderm/community/assets/7150/0c6f6eaf-7a17-42b2-823e-70de94a43e3b">

I thought it might be different if I went to hachyderm.io directly, but it doesn't seem to be:

<img width="368" alt="image" src="https://github.com/hachyderm/community/assets/7150/0466d5b7-2640-4a34-a244-dca02cbd167b">

The `NS_...` errors in there are `NS_BINDING_ABORTED`. Here is an example of a slow request:

<img width="368" alt="image" src="https://github.com/hachyderm/community/assets/7150/bc6ec395-b2a9-4539-bc06-29b5c0e480fa">

update: here's an image that took 2.3 minutes to only partially load, eventually failing with `NS_ERROR_NET_PARTIAL_TRANSFER`:

<img width="692" alt="image" src="https://github.com/hachyderm/community/assets/7150/5ef52d24-85f4-435b-b793-1cc7d04efb31">

### How long have you noticed this issue?

This morning

### What geographic region are you accessing Hachyderm from?

Maine, USA

**Comment by wolpert** [comment]
Coming from Arizona, USA the service is very slow for me too. Like 1+ min to get initial render. (I don't have the stats like OP)

**Comment by joergbattermann** [comment]
Same-ish here in California (Bay Area) / AT&T Fiber. Had issues in the morning via app / Ivory but same thing via the normal web interface / browser & network reponse/loading times look quite high:

![image](https://github.com/hachyderm/community/assets/828/f8d0e180-fa81-47d0-8e92-1ff99f313758)

**Comment by durka** [comment]
Was loading incompletely or not at all for me all day (PA, USA) but seems to be mostly back to normal now.

**Comment by joergbattermann** [comment]
Yes, can confirm it's running seemingly normal again. Thanks!?

**Comment by e-nomem** [comment]
Apologies for the sluggish responses today. One of our CDN nodes was having some issues today so if you ended up routed to that edge you would have experienced issues, but we've resolved the problem now.

Thanks for your patience!

**Comment by llimllib** [comment]
Thank you @e-nomem !
