### ISSUE TITLE
Specialized Accounts: FediTo

### ISSUE THREAD

**Issue by SoniEx2** [hachyderm/community#542]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Open Source Project

### How do you fit in with the community?

we make this project and service ( https://fedi-to.net/ ) available for folks who want some level of integration between fedi's various instances and the standalone fedi client of their choice. we would like a dedicated channel to post project updates; while the project itself is unlikely to receive many changes (it's pretty stable), we do believe the community would appreciate updates on client support.

### How will you ensure the community is protected?

we agree to follow the [Specialized Account Expectations](https://community.hachyderm.io/docs/account-types/covenant/). of particular relevance, we will not post about fedi clients whose policies are incompatible with the hachyderm rules. (they probably wouldn't be compatible with our morals anyway.)

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A

**Comment by hachyderm-admin** [comment]
👋 FediTo has been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to the profile meta data with the name/label `APPROVED`. Once this is done it should show as green on the profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.
