### ISSUE TITLE
Search timeouts

### ISSUE THREAD

**Issue by bjorn3** [hachyderm/community#550]
### Please describe the issue you are seeing.

For the past couple of days I've been getting 504 gateway time-out on the search api endpoint. This happens both on the web interface (firefox) and in the Tusky android app. It doesn't matter what I search.

### How long have you noticed this issue?

First noticed this issue July 30th

### What geographic region are you accessing Hachyderm from?

Europe

**Comment by bjorn3** [comment]
It worked for a bit a couple of hours ago, but is broken again.

**Comment by hachyderm-admin** [comment]
Hello! Apologies for the delay - we were actually troubleshooting this at the time and believe we were able to resolve it. Can you confirm if it's resolved for you?

**Comment by bjorn3** [comment]
I wasn't aware you were troubleshooting it. https://status.hachyderm.io/ didn't list any indication about it. In any case, it works just fine for me now. Thanks for fixing this!

**Comment by hachyderm-admin** [comment]
Hey absolutely not a problem and thank you for reporting it :)
