### ISSUE TITLE
Specialized Accounts: @followthecrypto

### ISSUE THREAD

**Issue by molly** [hachyderm/community#551]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Account with some, or all, automated and/or scheduled posts

### How do you fit in with the community?

The account reports updates on a sector in the tech industry (see the primary project at https://www.followthecrypto.org/). I also have my personal Mastodon account with hachyderm (@molly0xfff@hachyderm.io) and would like to have my project's account here, too.

### How will you ensure the community is protected?

I am familiar with the community content guidelines as an active member of Hachyderm on my personal account. I don't anticipate any posts that will require content warnings, but will use them if needed. Posts from the account will consistently use the `#crypto #cryptocurrency #USpol #USpolitics` hashtags to allow people to filter the posts if they wish.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

Right now all posts from the account will be manual, but I will likely automate the posts in the near future. Any automated posts from this account will follow the rules outlined in the docs, including using the `#hachybots` tag. Post automation will not include any reply/tag functionality or otherwise interact with any outside triggers. I may reply from the account if someone asks a question in a thread, but will do so manually.

At the moment the Follow the Crypto accounts (see [Twitter](https://x.com/follow__crypto) and [Bluesky](https://bsky.app/profile/did:plc:spedjz5pnontltd5cd74jdf3) examples) post one thread per
1) New expenditure from a crypto-focused political action committee
2) Election result involving a candidate who has been supported by a crypto-focused PAC

Posts do not repeat.

I may add future functionality to also post about large contributions to these committees, which are infrequent.

I'm familiar with running Mastodon bots, and have been running @web3isgreat@indieweb.social for two years without issue.

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by molly** [comment]
Thank you!
