### ISSUE TITLE
Specialized Accounts: Self-Directed Research Podcast

### ISSUE THREAD

**Issue by amanda-onevariable** [hachyderm/community#554]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Curated Content Account

### How do you fit in with the community?

We are a new weekly tech podcast with co-hosts Amos Wenger (@fasterthanlime) and James Munns (@jamesmunns)- usually about Rust, embedded, web servers, but anything is fair game.

Amos and James' different perspectives work out well for the podcast as they tend to ask each other questions that the audience may ask themselves — making presentations more approachable and fun. 

This community seems to be full of similar content with companies & people who would vibe with our vibe - we look forward to meeting them!

See more about what the podcast is/who we are here: https://sdr-podcast.com/about/

### How will you ensure the community is protected?

This instance was recommended specifically from Amos, who also is part of this community - we strive to support open-source development, experimentation and learning within the tech community, and think that Hachyderm is a great outlet for sharing our knowledge and interacting with other passionate developers. 

We are neurodiverse, welcoming and supportive, and hope to feel right at home here :) Thanks for creating a safe digital space!

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
Hello!

Thank you - this is approved. Can you please create the account and put the handle here? Then we'll put the handle on our approved page.

**Comment by fasterthanlime** [comment]
Thanks! The account is https://hachyderm.io/@sdr_pod

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by hachyderm-admin** [comment]
Hello! We wanted to check in and see if you were able to do this yet?

**Comment by fasterthanlime** [comment]
Hi! I've just done so. Thanks again for the approval.

![CleanShot 2024-08-21 at 22 19 57@2x](https://github.com/user-attachments/assets/b11eea00-cb7a-4b6f-b848-8c3234f88c60)

**Comment by jamesmunns** [comment]
(as a note, @amanda-onevariable is on vacation at the moment, so please feel free to close this for us, or they can do it when they return!)

**Comment by hachyderm-admin** [comment]
We gotcha! Closing :)
