### ISSUE TITLE
Specialized Accounts: Freexian

### ISSUE THREAD

**Issue by anupaaj** [hachyderm/community#557]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

Freexian SARL is a software company specialized in Free Software and in particular in Debian GNU/Linux.
Our [Mission statement](https://www.freexian.com/about/) reflects the values Freexian believes in.
All of Freexian’s employees and partners are active contributors in the Free software community.
Hachyderm community feels like a good place for us to have a presence in Mastodon.

### How will you ensure the community is protected?

Our plan is to use this Mastodon account to reach out to the Fediverse.
We do not intend to post or make any offensive remarks through our Mastodon handle.
Freexian agrees to follow the Hachyderm rules & [specialized account expectations](https://community.hachyderm.io/docs/account-types/covenant/).

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.
