### ISSUE TITLE
hit rate limit while manually editing settings of my lists

### ISSUE THREAD

**Issue by dalehagglund** [hachyderm/community#559]
### What would you like to discuss with us or let us know?

I've started to try out lists to control the flood of traffic in my main federated timeline, and had 10 lists that I wanted to change settings for. In particular, I was enabling

- hide posts from home, and
- show replies from any followed user

for these 10 lists. (If you check my account, you'll see more lists now, because I'm still experimenting with how to split things up.)

I was doing this via the stock web interface at hachyderm.io, and 
after changing 6-7 of them, I started getting "rate limite exceeded" errors, telling me I could continue after a few minutes. I waited that amount of time, and was able to continue making my changes.

So functionally everything's fine, but it feels like the rate limits might be a bit low if I can manually exceed them doing what seems like not that big a batch of changes. (I'm pretty sure I'm not inhumanly fast at the keyboard and mouse.)

Anyway, I realize that adjusting rate limits of this sort is a thankless task, and there may just be no happy medium here, but I thought I'd mention it.

**Comment by ThisIsMissEm** [comment]
This might be better forwarded to the mastodon project, since it sounds like you hit a rate limit there.

**Comment by ThisIsMissEm** [comment]
The limits in Mastodon should be 300 requests to the API per 5 minutes from your IP address.

**Comment by dalehagglund** [comment]
I was just typing "I don't see how that can be possible", and the I realized that sometime (maybe just a few minutes) before the rate limiting kicked in, I'd loaded www.mastodonlistmanager.org continue trying to sort my follows into lists, and I'm certain *that* does a lot of api requests given 700 follows.

I hadn't made the connection until just now, and I think that's a pretty likely explanation for what happened.

**Comment by dalehagglund** [comment]
Closing since in my view there's a reasonable explanation for what I observed.
