### ISSUE TITLE
SECURITY: Add CAA record for hachyderm.io.

### ISSUE THREAD

**Issue by ThePowerOfDreams** [hachyderm/community#56]
Currently hachyderm.io has no CAA header, allowing any CA to issue a TLS certificate for it, enabling shenanigans such as [these](https://archive.ph/c9fBJ):

```
% dig CAA hachyderm.io.

; <<>> DiG 9.10.6 <<>> CAA hachyderm.io.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62998
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;hachyderm.io.			IN	CAA

;; AUTHORITY SECTION:
hachyderm.io.		900	IN	SOA	ns-1277.awsdns-31.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 205 msec
;; SERVER: [snip]
;; WHEN: Fri Nov 18 [snip] 2022
;; MSG SIZE  rcvd: 126
```

I recommend adding the following two records to the `hachyderm.io.` zone, locking issuance (including wildcard) to Let's Encrypt (the current provider) and emailing @krisnova in the event of issues:

```
hachyderm.io.		86400	IN	CAA	0 issue "letsencrypt.org"
hachyderm.io.		86400	IN	CAA	0 iodef "mailto:admin@hachyderm.io"
```

More info [here](https://letsencrypt.org/docs/caa/) and [here](https://sslmate.com/caa/).

**Comment by dmah42** [comment]
~  dig CAA hachyderm.io.                                                               12:10:14

; <<>> DiG 9.10.6 <<>> CAA hachyderm.io.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51639
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;hachyderm.io.			IN	CAA

;; ANSWER SECTION:
hachyderm.io.		300	IN	CAA	0 iodef "mailto:admin@hachyderm.io"
hachyderm.io.		300	IN	CAA	0 issue "letsencrypt.org"

;; Query time: 15 msec
;; SERVER: 192.168.178.101#53(192.168.178.101)
;; WHEN: Sun Nov 27 12:10:22 GMT 2022
;; MSG SIZE  rcvd: 119

**Comment by ThePowerOfDreams** [comment]
Great! I see you've given it a 300-second TTL, but I recommend giving `CAA` records a reasonably long duration such as `86400` for moar sekure.
