### ISSUE TITLE
Specialized Accounts: https://hachyderm.io/@techtonica

### ISSUE THREAD

**Issue by MaggieFero** [hachyderm/community#562]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

As a nonprofit partnering with tech companies to provide software engineering training with need-based, sliding-scale, subsidized tuition and stipend scholarships with supplied laptops, job placement and/or job search support to women and non-binary adults seeking economic empowerment, Hachyderm is where our community is. All of our participants are women and nonbinary adults, and our current cohort includes 25% trans or nonbinary participants (the cohort is too small to break them out separately).  As our graduates enter the tech industry, Hachyderm is the kind of respect-focused online space we can comfortably recommend they go.

### How will you ensure the community is protected?

We intend to participate in the community actively, offering requested resources as available (such as resources from our[ fully open-source curriculum](https://github.com/Techtonica/curriculum)) and just generally being a part of the conversation. We will report any violations of community norms to admins just like we would on our individual accounts, and adjust our behavior or posting habits as requested.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

N/A

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by MaggieFero** [comment]
We've got it added to our profile and it's showing as green! Thank you very much!
