### ISSUE TITLE
"Request not signed"?

### ISSUE THREAD

**Issue by nedbat** [hachyderm/community#565]
### What would you like to discuss with us or let us know?

Hi, I've been fetching data from https://hachyderm.io/users/nedbat/followers.json for a long time now, and it's been working great.  But today it failed with:

> {"error":"Request not signed"}
> 401 from https://hachyderm.io/users/nedbat/followers.json:

Is this an intentional change? If so, where can I read about what I should do?

**Comment by ThisIsMissEm** [comment]
This is due to hachyderm recently enabling authorized fetch. I'd recommend using an API access token instead; you can create one at: https://hachyderm.io/settings/applications/new (every application created there automatically has an access token issued which is bound to your account)

**Comment by hachyderm-admin** [comment]
Btw @nedbat - please let us know if this resolves the issue you are seeing. If it does, please close the ticket and if it doesn't please give us an update for what you still see after generating the token.

**Comment by nedbat** [comment]
Thanks, I got a token, and added it as a header: `Authorization: Bearer`, but it doesn't help.  I guess I need the full OAuth flow...

**Comment by hachyderm-admin** [comment]
Can you tell us a bit a more about what you're specifically trying to do? That'll help us provide guidance.

**Comment by nedbat** [comment]
I'm trying to get a count of my followers, but that seems to require getting a list of all the followers, which needs a signed request, correct?

I was using Python code to get the JSON from `https://hachyderm.io/users/nedbat/followers.json` which worked fine.  Now it needs a signed request, which might be too much trouble.

Do you know of an example in Python that shows using the token correctly?

**Comment by ThisIsMissEm** [comment]
Yeah, that endpoint is the ActivityPub collection for your followers, you'd probably want this endpoint instead:

https://docs.joinmastodon.org/methods/accounts/#followers

The `GET /api/v1/accounts?id[]=...` endpoint also returns a count of your followers: https://docs.joinmastodon.org/methods/accounts/#index

**Comment by ThisIsMissEm** [comment]
You can also see python libraries for the Mastodon API here: https://docs.joinmastodon.org/client/libraries/#python

**Comment by nedbat** [comment]
Thanks, I think I will do without the follower count for now.

**Comment by nedbat** [comment]
Coming back to it, the `/api/v1/accounts/lookup` URL is easy to use.  Here's a shields.io URL with it:

```
https://img.shields.io/badge/dynamic/json?label=Mastodon&query=followers_count&url=https%3A%2F%2Fhachyderm.io%2Fapi%2Fv1%2Faccounts%2Flookup%3Facct=nedbat&logo=mastodon&style=flat-square
```
![sample](https://img.shields.io/badge/dynamic/json?label=Mastodon&query=followers_count&url=https%3A%2F%2Fhachyderm.io%2Fapi%2Fv1%2Faccounts%2Flookup%3Facct=nedbat&logo=mastodon&style=flat-square)

**Comment by ThisIsMissEm** [comment]
Ah, neat! (This'll only work for public profiles)
