### ISSUE TITLE
Specialized Accounts: highland

### ISSUE THREAD

**Issue by SwiftedMind** [hachyderm/community#567]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Corporate Account (must have already gone through email invite process)

### How do you fit in with the community?

- I genuinely enjoy the ios community that's been developing here on hachyderm and I love to be part of it.
- I am a passionate ios developer that loves to build apps and open source swift frameworks. Hachyderm feels like a great place to share that passion
- I want to have a separate account whose sole purpose it is to inform about my ios app "Highland" in an honest and transparent way without manipulation, tricks, deceptive marketing or anything like that

(I am not sure "Corporate Account" is the correct type. None of the options really fit. The account is for an app that I am developing in my free time. There is no corporation involved, but I guess it's the closest of all the options. I did not receive an email invite, but I did have an exchange with the admins/mods about verification)

### How will you ensure the community is protected?

- The account will only be used to inform people about the development of the "Highland" ios app, e.g. in the form of app update information, feature introductions or public support work (i.e. answering questions about the app)
- All engagement (post boosting, replying, ...) will be related to the app. I will not use the account for personal or off-topic matters
- I will not engage in any kind of hateful, discriminatory, disrespectful, harassing or otherwise unacceptable conduct
- I will do my best to closely follow and adhere to the _Specialized Account Expectations_ and Mastodon/Hachyderm rules in general, all of which I fully agree to.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

_No response_

**Comment by hachyderm-admin** [comment]
👋 You've been added to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.
