### ISSUE TITLE
End of British Indian Ocean Territory and the .io TLD

### ISSUE THREAD

**Issue by j3j5** [hachyderm/community#571]
### What would you like to discuss with us or let us know?

It's not really an issue (yet) but something to keep an eye on. The UK has announced that will hand over the British Indian Ocean Territory, also known as the Chagos Archipelago, to Mauritius. Which means that the io may stop being on the ISO 3166-1 alpha-2 list.

Now, nobody knows whether ICANN will do anything about it (probably not), also, it isn't even clear whether the registry will change hands (it belongs to a private company, not the UK), but as mentioned above, it's something to be watching this year.

Reference: https://domainincite.com/30395-future-of-io-domains-uncertain-as-uk-hands-over-chagos-islands

**Comment by hachyderm-admin** [comment]
Thank you for making sure we were aware! We have parked a few alts for Hachyderm (as a TLD) that we can have ready to go as needed for this.

Thank you again!
