### ISSUE TITLE
spam wave

### ISSUE THREAD

**Issue by llimllib** [hachyderm/community#572]
### What would you like to discuss with us or let us know?

I've been reporting them, but the volume of spam is exceeding my reporting ability:

<img width="796" alt="image" src="https://github.com/user-attachments/assets/5fdca995-f154-4913-bd0b-393588ca4784">

They come from different instances, but all have the same or similar text

**Comment by hachyderm-admin** [comment]
Hello!

Thank you for sending all of the reports in - we're aware and actually several instances are coordinating  (via IFTAS) to moderate the instances that are coming through as a spam wave. We're working hard to identify and remove.

**Comment by hachyderm-admin** [comment]
Closing this for now - please let us know if this needs to be reopened :)
