### ISSUE TITLE
Add option for old (<4.3.0) dark theme

### ISSUE THREAD

**Issue by gozzarda** [hachyderm/community#575]
### What is your suggestion?

While many visual impairments benefit from higher contrast, mine causes secondary ghost images to appear around (especially below) the real image. In high-contrast dark modes this makes it look like multiple copies of a block of text are overlapping each other, offset slightly. Dark modes with a slightly grey background (particularly more pastel themes) avoid this, as the background becomes brighter than the ghost text but not the real text.

With the update my to 4.3.0, the default dark theme has changed from one that was perfect for me to one that isn't as accessible. It's probably not this straightforward, but if it would be possible to provide the pre-4.3.0 dark theme as an option that would be a huge help. The light theme works a bit better but isn't anything like as good as a lower contrast option.

Thanks for running a great service. Hopefully this isn't too difficult a request.

**Comment by Preskton** [comment]
Howdy, @gozzarda - we did some quick research, and it seems like those themes no longer exist. We've recently installed https://github.com/nileane/TangerineUI-for-Mastodon that provides a few more options, and maybe one will feel a bit better.

I would strongly recommend making a request on the upstream [Mastodon project](https://github.com/mastodon/mastodon). If you do end up doing that, do you mind cross-linking this issue so we have a nice paper trail?
