### ISSUE TITLE
@davidgerard@circumstances.run shows "account suspended" from hachyderm.io

### ISSUE THREAD

**Issue by huronbikes** [hachyderm/community#579]
### What would you like to discuss with us or let us know?

I have been following David Gerard's written work regarding cryptocurrency and AI hype in addition to other rot-economu issues for some time. I noticed recently that the user account appears suspended only on hachyderm.

**Comment by SnoopJ** [comment]
The Hachyderm moderation team has [confirmed](https://hachyderm.io/@hachyderm/113489261394915501) that a moderation action was taken, cutting Hachyderm users off from interactions with David Gerard's account. There are no details about the specific action, inline with the [recent synopsis of moderation policy](https://community.hachyderm.io/blog/2024/09/01/hachyderms-introduction-to-mastodon-moderation-the-report-feature-and-moderator-actions/) and the [Hachyderm Community docs](https://community.hachyderm.io/docs/) (emphasis mine):

> The main focus of moderation is community safety, so if a specific user or instance has been temporarily or permanently moderated, then the most common reason is that we saw an incident or behavioral pattern that we believed posed **a risk to community safety.**

Although I have voiced my concern in the above linked thread, I'll briefly recapitulate it here: in light of the previous proximity of Hachyderm to the Nivenly Foundation's flirtation with supporting an AI project, and David Gerard's outspoken criticism of AI grift, I find myself wondering what exactly the danger he posed to the community.

The official policy of the moderation team is not to publicly discuss why a moderation action was taken (beyond _"community safety"_), so as far as I know, the only action that can be taken from here is for David Gerard to get in touch with the Hachyderm administrators, which they say he has not done.

**Comment by huronbikes** [comment]
@SnoopJ thanks. I read the thread and while any possible remediation now depends on David coming up with a response that some how appeases the Hachyderm moderators, this incident troubles me.

I'm guessing that this moderation decision will not be reversed and that the best course of action given that I wish to continue to follow Mr. Gerard is to leave Hachyderm, an action which I do not wish to do.

As stated before, thank you and all the best.

**Comment by hachyderm-admin** [comment]
Although this thread is closed, we're still going to comment in the interests of communication. To help with future requests, it really helps if the specific concern is voiced in the original question so we can directly answer it. For reasons discussed, while we cannot divulge the entirety of someone's situation, as it would involve their personal information and perhaps the information of others depending on what happened, that doesn't mean that we can't answer any questions or that we're trying to be particularly opaque. "I would like to know about this user's moderation status" is considerably more broad than a specific concern like "I am concerned that this user was moderated for being critical of AI". 

To answer the question: "was this user (or any user) moderated for their opinions on AI" the answer is no. We have no community rules about AI or opinions on AI for a user to break, other than not allowing "financial account types" (basically, similar to our limitations on corporate accounts, we wouldn't allow a "bitcoin @ hachyderm" or "venmo @ hachyderm" account).

This is something that can be verified by looking at our Community Rules and noting the absence of AI as a rule to be followed or broken. Another method that could be used to see if we're moderating for opinions critical of AI is to look at some of the other accounts on Hachyderm, including Molly White. Candidly, we'd host hundreds of Molly Whites very happily.

As for what does go into moderation decisions: again, as stated, we moderate for community safety. This means that someone violated one or more Community Rules in such a way that we determined that we needed to intervene. How severe, or how permanent, the intervention is would depend on the full context of what happened. If there was a thread, that means looking at power dynamics, intersectionality, severity, repetition, and so forth. 

When a user or server has been moderated they can ask us about their personal moderation data at any time. It doesn't need to be a particularly long request, a simple "Hey I noticed I was moderated on your instance and would like to learn why" is more than enough. Similarly, a discussion to change our decision doesn't necessarily need to be particularly long either. 

We appreciate that this discussion is closed, so we'll leave it at that in this GitHub Issue and leave the Issue closed.

**Comment by huronbikes** [comment]
Best course would have been to say nothing further and leave things as they were and yet here you are trying to have the last word.

> Hey I noticed I was moderated on your instance and would like to learn why

That was the original request. I am reopening because now I want to know as much as is willing to be shared, so do tell.

**Comment by hachyderm-admin** [comment]
Hello. The goal of the prior post was not to have a final word, merely to answer the questions as they appeared. In answer to the question "was this account moderated for their views on AI" the answer is no, as stated. In answer to "can I have a broad deep dive into someone else's moderation status", the answer is no also as stated.

Please note that the sentence you quoted, where we stated "Hey I noticed I...", is only for the moderated person to request, as we also tried to be clear about.

**Comment by huronbikes** [comment]
That's funny, because it seems your assuming that my best guess as to what happened was due the person subject to the moderation action having views on AI. That was never my intent nor do I fully believe that would be the case, at least overtly.  Which brings us to an issue: I have no idea why the action was taken after talking to various people. If there is some troubling pattern of behavior happening, I would like know so I may avoid actively contributing to such behavior.

**Comment by MHLoppy** [comment]
> it seems your assuming that my best guess as to what happened was due the person subject to the moderation action having views on AI

**Comment by MHLoppy** [comment]
> it seems your assuming that my best guess as to what happened was due the person subject to the moderation action having views on AI.

I think that topic was brought up in this GitHub issue without necessarily being directed at you specifically, because David linked this GitHub issue and [speculated](https://circumstances.run/@davidgerard/113487492538743433) that the AI thing was the reason for the moderation.

**Comment by hachyderm-admin** [comment]
> I think that topic was brought up in this GitHub issue without necessarily being directed at you specifically, because David linked this GitHub issue and (separately) [speculated](https://circumstances.run/@davidgerard/113487492538743433) that the AI thing was the reason for the moderation.

That, and in combination with the initial post here making reference to David Gerard's opinions on AI, which we assumed was done because the requestor felt it was relevant to include. So we decided to directly answer what seemed to be an indirect question that either the original poster had, or was inspired to have by David Gerard's speculation. Maybe it helped, maybe it didn't - we can only do our best.

We did want to answer some of the speculation here about criticisms as we think it might be helpful. As always, please keep what is helpful and don't what is not.

Something that we have in common with Nivenly, as a Foundation project, is a certain core ethos that is a side effect of co-operative structure. One thing that includes: active criticism is desired and healthy. The reason that Foundations like Nivenly exist to try and lay down governance groundwork is specifically for coordinating effort and no small part of that is dispute resolution (how much process would we need if we agreed, you know?).

So in this case, both here and in the Fedi thread, there seems to be a few parties that are interested in a nuanced discussion about the balance of privacy, safety, and transparency. We have outreach offering them time to meet and discuss, should they wish, and look forward to seeing what opportunities it may open for new ideas and collaboration.

As for this, since the discussion isn't fruitful here, we're going to go ahead and lock this thread. As always, please feel free to open new threads and ask additional questions as wanted or needed.
