### ISSUE TITLE
Specialized Accounts: @ooh_directory_bot@hachyderm.io

### ISSUE THREAD

**Issue by comatory** [hachyderm/community#582]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

I like to create software and I think having automated post account for ooh.directory will help people discover the articles there.

### How will you ensure the community is protected?

I read the posts that the bot posts, so if there's anything conflicting with the server rules, I will immediately remove such post.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

My bot posts once a day so it should not be disruptive. I'll make sure to add `#hachybots` hashtag to all its posts.

**Comment by comatory** [comment]
I already created the account 😓 sorry about that I misread the process.

**Comment by hachyderm-admin** [comment]
No worries and apologies for the delay! We're a little behind with holidays in the US.

We're going to update the instructions to reflect, having the account handle parked at this stage is perfectly fine. 

We're unfamiliar with ooh.directory - would you be able to show an example of what a typical post should look like to help us?

**Comment by comatory** [comment]
Sure, here's the latest post: https://botsin.space/@ooh_directory_bot/113582643692865213

(Btw I had a deployment bug 2 times and it posted excessively, but I fixed that. Once a day is the usual)

**Comment by comatory** [comment]
![Image](https://github.com/user-attachments/assets/0f8a65b9-f012-45eb-b0f0-af0f515b418e)

Closing this, I added verification URLs (both to the site of the bot itself on GH pages & my personal site).
