### ISSUE TITLE
Specialized Accounts: naturalist_bot

### ISSUE THREAD

**Issue by fmichonneau** [hachyderm/community#584]
### Which type of specialized account are creating? If more than one apply, please select the primary type.

Bot Account

### How do you fit in with the community?

The [naturalist_bot](https://botsin.space/@naturalist_bot) has been live for just about a year but with botsin.space shutting down, I'm trying to find a new home for it. This account posts 4 times a day random observations from iNaturalist that were made on that day the year prior. The code for the bot checks that the data licensing to select the observations that will be posted. It's a fun hacking project that celebrates the diversity of life in all its forms. 

### How will you ensure the community is protected?

I agree to the Specialized Account Expectations.

Given that the bot only post accounts and doesn't interact with the community directly. The content only includes photos of wildlife and standard text that provides context about the observation.

### (Accounts with Automated Posting/Bot Accounts Only)
What method are you using to validate your bots code to ensure that any future updates don't disrupt the community?

The account only posts at regular intervals and doesn't engage by responding to users or process data from users. I have no intention of changing how the bot behaves at this time. If, in the future this would change, I'll be sure to seek a new approval.

**Comment by hachyderm-admin** [comment]
Hello! Looking through your posts, it seems like your bot would be a lovely addition to our instance. Please go ahead and create the account handle and we'll add you to the approval page, posting next steps.

**Comment by hachyderm-admin** [comment]
Awesome! We've added you to the approval page. Please follow the instructions on the [Account Verification](https://community.hachyderm.io/docs/account-types/verification/) page to add `https://community.hachyderm.io/approved/` to your profile meta data with the name/label `APPROVED`. Once this is done it should show as green on your profile. If so, please close this ticket. If the verification fails for some reason, please let us know here and leave the ticket open.

**Comment by fmichonneau** [comment]
It worked perfectly! Thank you so much 🎉
