### ISSUE TITLE
Policy when permanently banning/blocking/deleting accounts

### ISSUE THREAD

**Issue by zeroby0** [hachyderm/community#59]
Heyo!

I imagine a lot of the people involved are really busy keeping up with the sudden growth, so please take your time.

In good faith, should we give offending users a period of notice before deleting their accounts so they can export their data? And maybe 'quarantine' them in the notice period by limiting interaction with mods only.

**Comment by benwis** [comment]
This already happens. Check out the different moderation actions here:
https://docs.joinmastodon.org/admin/moderation/

**Comment by zeroby0** [comment]
Perfect! Thanks :)
