### ISSUE TITLE
GitHub verification (option 1) not working

### ISSUE THREAD

**Issue by mamercad** [hachyderm/community#62]
Following [this](https://github.com/hachyderm/community/blob/main/verification.md#updated-with-new-information) and verification is not working; GitHub profile is [here](https://github.com/mamercad) and I've added `@mamercad@hachyderm.io` to the Bio section of my profile.

GitHub:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/6192266/202851602-8255f23e-c1ce-4830-895e-09084bc1d3a8.png">

Hackyderm:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/6192266/202851632-8ed70edb-ea61-47ee-a45d-229dd429501f.png">

**Comment by morman** [comment]
To get it to work I think you need to replace this profile link:

[mamercad.github.io/about](http://mamercad.github.io/about)

With the Hachyderm link:

https://hachyderm.io/@mamercad

**Comment by morman** [comment]
I swapped to Option 1 and it seems to work. Let me see what happens if I add another @ in front of the Hachyderm @ as you have... No, I can't seem to get it to fail. Maybe my verification is cached and this isn't a valid test.

Can anyone else replicate the issue @mamercad sees here?

**Comment by morman** [comment]
Aha! I have successfully broken my Github verification by changing the Github link from the working:

https://github.com/morman

To the failing:

https://github.com/morman/

Apparently the addition of a trailing slash to the GitHub profile in Mastadon causes verification to fail?

@mamercad See if removing the trailing slash solves the issue for you.

Meanwhile, is this an open issue with Mastadon itself?

**Comment by morman** [comment]
I have replicated this issue after some trial and error.

**Comment by wlonkly** [comment]
I noticed in the HTML that Github is automatically linking `@mamercad` to your Github handle, so the string `@mamercad@hachyderm.io` never appears consecutively. I wonder if that breaks verification? 

For what it's worth, I verified by updating my Github website field to have my hachyderm URL, saving my profile here (to trigger verification), and then once verified I set my Github website back to what I wanted there.

**Comment by mamercad** [comment]
> I noticed in the HTML that Github is automatically linking `@mamercad` to your Github handle, so the string `@mamercad@hachyderm.io` never appears consecutively. I wonder if that breaks verification?
> 
> For what it's worth, I verified by updating my Github website field to have my hachyderm URL, saving my profile here (to trigger verification), and then once verified I set my Github website back to what I wanted there.

Ah, nice observation; I'll try the "switcheroo".

**Comment by mamercad** [comment]
> > I noticed in the HTML that Github is automatically linking `@mamercad` to your Github handle, so the string `@mamercad@hachyderm.io` never appears consecutively. I wonder if that breaks verification?
> > For what it's worth, I verified by updating my Github website field to have my hachyderm URL, saving my profile here (to trigger verification), and then once verified I set my Github website back to what I wanted there.
> 
> Ah, nice observation; I'll try the "switcheroo".

The "switcheroo" worked for me as well, thanks for the workaround. Since you might have found the root cause, I'll leave this open and perhaps we can close it by updating [the docs](https://github.com/hachyderm/community/blob/main/verification.md#updated-with-new-information) highlighting this potential (breaking) edge case.

**Comment by wlonkly** [comment]
@untitaker Ah, good point, I didn't realize every server verified links at view time. That said, I brought up my own profile from another account, and _neither_ of my links show as verified -- even though the website (but not the github, where I did the switchero) should be verifiable at any time.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1545955/202922803-2e8880d6-b9d5-4e96-88e8-6e5eecc50d1f.png">

I also tried a bunch of non-Hachyderm users I follow, and their links show verified on their local profile but not on their profile-viewed-through-Hachyderm. Are you sure links _ever_ show as verified outside the local instance?

**Comment by untitaker** [comment]
@wlonkly yes, if the rel=me stays permanent it should show up on every instance. See `@untitaker@hachyderm.io` on other instances.

**Comment by wlonkly** [comment]
Ah, and there it is. I guess `halifaxsocial.ca` hadn't verified me _yet_ when I tried earlier. (And rats, that's too bad, but verifying that verification is current is a good thing!) 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1545955/202929576-729c524d-fbf2-4515-988c-aaa1c6574dcd.png">

I'll update my PR to remove the recommendation for the switcheroo, but still call out the bio edge case. (Although the more I think about it, the more I think the bio edge case is a bug on Github's end, because Github shouldn't auto-link a `@username` mention that's not followed by `/\s/`...)
