### ISSUE TITLE
DMCA agent?

### ISSUE THREAD

**Issue by chx** [hachyderm/community#64]
https://www.copyright.gov/dmca-directory/ we should have a designated agent to receive DMCA reports.

**Comment by rboyer** [comment]
There is a longer form list of related suggestions for Mastodon server operators here: https://twitter.com/rahaeli/status/1593819064161665024

**Comment by quintessence** [comment]
Thank you for this! I've added it to our internal tracker / ToDo and we'll be on it ASAP. Closing issue for now :)

**Comment by helmingstay** [comment]
@quintessence Does liability insurance deserve a new issue, or is it already on your tracker? From raheili's excellent thread^^:
"I also strongly recommend that if you run an instance, incorporate as a LLC and -- this is the critical part -- take out an umbrella liability insurance policy with coverage of at least $2m per incident and covers attorney costs and fees."

I want to underscore that as a queer-friendly community, it behooves Hachyderm to think proactively about DDoS attacks, both technical and social (e.g., spurious lawsuits, troll armies, etc).

**Comment by quintessence** [comment]
Already in the tracker, just had some other things to do this week with the service 🙃
