### ISSUE TITLE
Defederate journa.host, and clarify boundaries of moderation

### ISSUE THREAD

**Issue by untitaker** [hachyderm/community#65]
It seems journa.host hosts transphobic content and has taken an explicit stance to further allow that content while at the same time having "no transphobia" in their CoC.

See the #fediblock hashtag, as is visible on hachyderm.io today.

https://journa.host/@parker/109366337128882245
https://hachyderm.io/web/@parker@journa.host/109366337429914961

Also rapidblock appears to have blocked journa.host, for a different reason I don't understand: https://hachyderm.io/web/@rapidblock@rapidblock.org/109371315116740882
https://social.rapidblock.org/@rapidblock/109371315073267948

----

Regardless of how the journa.host situation evolves, it would be good to clarify which of your server rules apply to users on your instance and which criteria are used for defederating.

**Comment by grenierdx** [comment]
Following up, it looks like journa.host responded to this situation by suspending the people speaking up for themselves and putting out a vague, opaque "press release": https://journa.host/@info/109372514074976879

In light of this action and in the spirit of Hachyderm rules 10 and 11, I support defederation with journa.host.

**Comment by untitaker** [comment]
https://blog.infosec.exchange/2022/11/20/an-update-on-journa-host/

Removing from local timeline seems like an obvious move

**Comment by pcantrell** [comment]
I would encourage us to listen to and consider the wishes of the people directly involved: https://masto.ai/@parkermolloy/109377879615134816

**Comment by untitaker** [comment]
I would argue to still unlist them at least for now, which imo is not an invasive action, prevents transphobic content from reaching the federated timeline and can be undone easily. Past actions of journa.host have not inspired confidence and the fact that Parker has had a heart-to-heart with their admin doesn't really change that.

**Comment by kweerious** [comment]
Given Parker's follow up perhaps we should consider a lower action such as "silence" while we assess?

**Comment by pcantrell** [comment]
I thought this was a particularly thoughtful walkthrough of the decision process of infosec.exchange: https://infosec.exchange/@jerry/109377034083882648

**Comment by quintessence** [comment]
I'm adding this to our internal issue tracker for domain blocking - thank you!

**Comment by dmah42** [comment]
added a silence.

**Comment by quintessence** [comment]
That might be worth a new issue about silencing in general - can you open a new ticket?
