### ISSUE TITLE
Update the favicon for web browsers

### ISSUE THREAD

**Issue by numbertheory** [hachyderm/community#67]
I'm not sure exactly what it should be. Maybe, one of the emojis here? https://emojos.in/hachyderm.io

But, I usually bookmark things in the browser with just the favicon, so it might be nice for branding.

**Comment by jessestricker** [comment]
It should be the `:nova:` emojo, obviously.

**Comment by quintessence** [comment]
This is done :)

**Comment by sandipb** [comment]
@quintessence I still see the standard Mastodon favicon for hachyderm.io. Is this ticket not for the favicon visible in the browser tab?
<img width="40" alt="image" src="https://user-images.githubusercontent.com/105359/206091325-58cc62de-d2e4-4766-a5a9-eff3410b4aa4.png">
