### ISSUE TITLE
FOSS project emoji

### ISSUE THREAD

**Issue by aclater** [hachyderm/community#68]
The cool kids @ https://fosstodon.org/ have an extended set of emjoi for FOSS projects and companies, including Red Hat and Fedora. Would love to have those available for us as well.

TY!

**Comment by quintessence** [comment]
Maybe I/we can reach out to their maintainers - I've been uploading icons from my "Slack Icons" project, that now works for Discord and Mastodon. I should probably rename it at this point.

https://github.com/quintessence/slack-icons/

**Comment by aclater** [comment]
Looks like that is @kev@fosstodon.org and @mike@fosstodon.org

**Comment by quintessence** [comment]
Ah thank you! 

Also these emoji have been added :)
