### ISSUE TITLE
Consider locally increasing toot length limit

### ISSUE THREAD

**Issue by enygren** [hachyderm/community#70]
It may be worth considering increasing the toot length limit.  This allows for better engagement on technical topics that don't easily fit in 500 characters without needing to thread.  (Threads don't display well in timelines due to reverse-chrono.)

I've noticed that infosec.exchange has a higher toot length limit and as a result the toots from there on technical topics are more readable.  This doesn't necessarily mean that we want to have full blog posts in toots, but it would be helpful to be able to have more nuanced comments and discussions.

From a scaling perspective, my instinct is that increased toot length limits would actually help.  The size of more text is in the noise, but the operation rates and metadata overhead from threads is likely much worse.

Threads can still have benefits, allowing individual bullets to be boosted or liked on their own, but this also has downsides in a federated model.

Caveat: I don't know to what degree increased toot length limits are supported by various clients and servers.  It may be worth consulting with some other instance operators who have already done this.

**Comment by SteveDinn** [comment]
Speaking of longer toot lengths, does anyone have a CSS-modification or whatever to make the toot box bigger (wider)?

**Comment by quintessence** [comment]
👋 Mod here

I added this to our internal tracker and am closing the issue here for now. We will take a look at it and will make sure that we understand the implications (e.g. if other instances in the fediverse will have difficulties depending on Mastodon version, within reason, etc.) :)
