### ISSUE TITLE
Emoji Name Length and Character Limits

### ISSUE THREAD

**Issue by jmerritt** [hachyderm/community#72]
Extremely low priority fluff issue, but in the interest of using emoji in our usernames would it be prudent to shorten their naming?

_ex1-_ `:nix:` vs `:nix_snowflake_logo:`

Usernames have a char limit that is pretty easy to hit with an emoji or two.
Thank you for the consideration.

**Comment by slamp** [comment]
This is a duplicate of https://github.com/hachyderm/community/issues/54

**Comment by jmerritt** [comment]
> This is a duplicate of https://github.com/hachyderm/community/issues/54

Thanks for that don't know how I missed it. Closing.
