### ISSUE TITLE
Emoji request: Esperanto Flag

### ISSUE THREAD

**Issue by neoeinstein** [hachyderm/community#75]
Requesting that the Esperanto flag be added as a custom emoji on the server. [Example from another server.](https://emojos.in/esperanto.masto.host?show_all=true&show_animated=true)

Options for the emoji name:
* `eo` (the ISO-Alpha-2 designation for Esperanto)
* `esperanto` (more descriptive)
* `flago` (flag, in Esperanto)

**Comment by quintessence** [comment]
Done! Emoji name is `esperanto`
