### ISSUE TITLE
Undelete account 

### ISSUE THREAD

**Issue by mattbrailsford** [hachyderm/community#76]
Hey,

I was experimenting with a hachyderm account as I wasn’t sure whether to move my mastodon.social account to it. As I wasn’t sure I ended up deleting my account. 

I’ve since seen a lot of similar minded folk move over and so have decided I’d like to do the same, but am I able to reinstate the deleted account?

I didn’t make any posts so it’s just bringing back the account/username I’m trying to do. Is this possible?

The username was @mattbrailsford

**Comment by mattbrailsford** [comment]
NM I understand this is perminant now 👍

**Comment by mattbrailsford** [comment]
Anyone know if this is possible. From what I read it says deletion is permanent, but I’ve also seen user initiated deletions appear as suspensions to the admin.

**Comment by quintessence** [comment]
👋 Hello! We actually were investigating this for another user with a similar issue. It looks like deleted accounts cannot be reactivated, not exactly. The issues that it causes with federation results in a "zombie" like state as other Mastodon servers will have stored the information that this account is deleted. 

There is information about it on the mastodon/mastodon repo here:

https://github.com/mastodon/mastodon/issues/16626#issuecomment-1278570170

We know this isn't ideal and have also submitted an issue to their tracker to see if there's anything in the 4.x releases that would allow us to do this. (We haven't had success thus far.)

I know this isn't an ideal answer :(

**Comment by mattbrailsford** [comment]
Thanks @quintessence 

I thought this might be the case but I was reading mixed information so I really appreciated you clarifying. 

I’ll hold tight for a little while and keep track of the other issue to see if it’s something that can be resolved in a future update, otherwise I’ll go with a different username 👍🏻

thanks again for your insight

**Comment by dmah42** [comment]
i'm going to close this as there's nothing more i think we can do.  feel free to reopen it if you learn something about undeletions.
