### ISSUE TITLE
502 from hachyderm.io 

### ISSUE THREAD

**Issue by Toudahl** [hachyderm/community#77]
I am getting errors in the android client I use, and a 502 from the webpage.
Status.hachyderm.io reports all well

Is this something on my end, or are others having this issue too?

**Comment by untitaker** [comment]
there is currently maintenance which was announced in the app but imo should've been communicated on https://status.hachyderm.io

**Comment by Toudahl** [comment]
Ah, I didn't see that earlier. Do you know what time it was announced? Perhaps I missed it. Or perhaps tusky doesn't clearly show those type of announcements?

**Comment by untitaker** [comment]
I only saw it minutes before the site went down. TBH I really think it's the wrong channel to announce things when the channel itself goes down

**Comment by Toudahl** [comment]
If that is the case, I'm guessing it is unplanned downtime. That cannot always be communicated as one would want.

Perhaps  could give some thought on how to better reflect the downtime on the status page.

But other than that, I got my answer - so I am closing this.
