### ISSUE TITLE
API returning "This API requires an authenticated user"

### ISSUE THREAD

**Issue by trickjarrett** [hachyderm/community#80]
I am trying to migrate over my blog's API hookup to Mastodon. I use it to direct post from my blog, or for a twice/daily automated post about the new entries I've made. I've been running down the code and have ended up getting a 401 error, "This API requires an authenticated user."

This URL suggests it is an instance limitation: https://mcole18.github.io/documentation/docs/entities/error/

I am totally cool if this is a platform decision for the instance to limit automated Spam, but I couldn't find it called out anywhere in the instance documentation, and just want confirmation that is the case and not that it is an issue with my code.

Thanks

**Comment by untitaker** [comment]
This error appears if you just don't provide an api token. You need to authenticate in order to post: https://docs.joinmastodon.org/client/authorized/

You are trying to publish something on your account. That always requires you to be logged in. The secure mode that admins can enable also requires it to retreive otherwise public information from the instance.

**Comment by LGUG2Z** [comment]
I actually just set up [something similar today myself](https://hachyderm.io/@LGUG2Z/109384617622573313). You'll need to go through the [OAuth callback from to get an access token](https://docs.joinmastodon.org/spec/oauth/) which you can use when making calls to the [POST /statuses endpoint](https://docs.joinmastodon.org/methods/statuses/). That endpoint requires the `write:statuses` scope which is important to specify when going through the OAuth flow.

If you don't want to implement the whole flow yourself, you could use something like [this project](https://takahashim.github.io/mastodon-access-token/) to generate a one-off access token, though I would vet the source code a little before trusting it completely.

**Comment by trickjarrett** [comment]
I will work through the code again when I get home. This error began coming up after I got through the OAuth process and got the bearer token. It certainly could still be the issue at play here.

**Comment by trickjarrett** [comment]
So I ran back through everything and checked my stored variables, I requested a new OAuth code and had it provided with scope of 'read write'

I then stored that variable, and also double checked the client key and client secret from the app I have registered with the instance.

When I run the Oauth script it returns the following:

```
stdClass Object
(
    [access_token] => [REDACTED]
    [token_type] => Bearer
    [scope] => read write
    [created_at] => 1669012058
)
```
So it's returning an Oauth token. I put that in and I tell it to post to Mastodon. I realized I was using an old format for the header, after reformatting it to be a proper array in PHP, I get the following error.

```
stdClass Object
(
    [error] => The access token is invalid
)
```

Here's the code I'm using to post, which is what I used previously before switching instance. Anything jump out to folks?

```
    $headers = [
      "Authorization" => "Bearer ".MASTODON_BEARER;
    ];

    $status_data = array(
      "status" => $status,
      "language" => "eng",
      "visibility" => "public"
    );

    $ch_status = curl_init();
    curl_setopt($ch_status, CURLOPT_URL, MASTODON_INSTANCE."api/v1/statuses");
    curl_setopt($ch_status, CURLOPT_POST, 1);
    curl_setopt($ch_status, CURLOPT_POSTFIELDS, $status_data);
    curl_setopt($ch_status, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch_status, CURLOPT_HTTPHEADER, $headers);

    $output_status = json_decode(curl_exec($ch_status));

    curl_close ($ch_status);
    print_r($output_status);
```

**Comment by trickjarrett** [comment]
This turned out to be a larger issue with how I was connecting with Mastodon, this issue is closed.
