### ISSUE TITLE
ToS;DR Review Privacy Practices

### ISSUE THREAD

**Issue by cyberop5** [hachyderm/community#81]
Duck Duck Go's browser extension grades the privacy of websites.  Hachyderm.io currently has a B+ rating because the privacy policy is hasn't been reviewed.

Solution: Request a review of the privacy practices from [Terms of Service; Didn't Read](https://tosdr.org/) . The link to request a new service is https://tosdr.org/en/new_service.

Alternative/Additive: Place a tosdr.txt file in the root of the website and run it through the validator https://tosdr.org/txt. An example file is at https://tosdr.org/tosdr.txt.

See thread: https://hachyderm.io/@Cyberop5/109383117715172184

**Comment by duthils** [comment]
I requested a review with the Privacy Policy hosted at https://hachyderm.io/privacy-policy.

**Comment by duthils** [comment]
The service [has been created](https://edit.tosdr.org/services/6987), but not yet rated.

**Comment by dmah42** [comment]
what does "rating: n/a" mean?

**Comment by cyberop5** [comment]
N/A usually means Not Applicable.

The Duck Duck Go browsing extension isn't listing the "Unknown Privacy Practices" anymore. In fact, it's no longer issuing letter grades. Hachyderm.io has three green checkmarks instead.  I think they updated their extension and may have removed the feature. 

![image](https://user-images.githubusercontent.com/5078557/204150642-618a4f39-4178-4dff-be5e-639255190670.png)
