### ISSUE TITLE
Verifying Corp and Bot accounts?

### ISSUE THREAD

**Issue by grenierdx** [hachyderm/community#83]
Is it possible to use Mastodon's verification functionality to validate approved corporate and bot accounts? The flow I'm envisioning:

1. Account requests approval manually
2. Account is approved and given a hachyderm.io endpoint for verification
3. Approved account puts the endpoint in their profile metadata, gets a green checkmark

This way Hachydermians wouldn't have to check a bot against a separate list of approved accounts; checking the bot's metadata for a verified hachyderm.io address would be enough.

**Comment by quintessence** [comment]
👋 Mod here - we'll take a look at this. I'm adding it to the internal tracker where I'm tracking updates for handling special account types. Thank you!
