### ISSUE TITLE
Hachyderm needs a logo!

### ISSUE THREAD

**Issue by zmc** [hachyderm/community#84]

**Comment by baweaver** [comment]
Would be up to sketch out a few ideas. First thought is some type of cyberpunk elephant, but not quite sold on it.

**Comment by zmc** [comment]
What about a _solarpunk_ elephant?

**Comment by cosmicfire** [comment]
Hi, I can also help out with any design & graphics needs. Let me know how I can help.

**Comment by quintessence** [comment]
👋 We actually are in the process of looking for a logo :) Stay tuned :)

Going to go ahead and close this. There'll be more info once we have an announcement to make.

**Comment by cosmicfire** [comment]
OK. I'm here if you need help. :)

And by here I also mean: @***@***.***
