### ISSUE TITLE
Set up a bot account for issues, alerts, statuses

### ISSUE THREAD

**Issue by zmc** [hachyderm/community#87]

**Comment by quintessence** [comment]
Can you expand a little bit on what you'd like to see here?

**Comment by zmc** [comment]
I actually created this for @krisnova and wasn't sure about specifics. My _guess_ would be a bot account for the Mastodon instance that could toot about (filtered?) events, but it could also mean a github bot for e.g. nagging about issue staleness

**Comment by slamp** [comment]
@zmc automated feedback during outage is discussed here https://github.com/hachyderm/community/issues/127

**Comment by quintessence** [comment]
Closing as this is being discussed in #127 as linked above :)
