### ISSUE TITLE
GDPR Applicability and Mastodon

### ISSUE THREAD

**Issue by slamp** [hachyderm/community#89]
Even if your Mastodon instance is hosted outside of the European Union (EU), you may need to comply with its General Data Protection Regulation (GDPR).

Using the link below we can generate a Data Protection Notice in HTML and then hosted somewhere in hachyderm.io
https://blog.riemann.cc/projects/mastodon-privacy-policy-generator/

**Comment by krisnova** [comment]
@slamp would you be interested in helping us adhere to the GDPR notice on our websites?

**Comment by slamp** [comment]
I can draft a version but I will need your input for few answer. I will ping you on discord

**Comment by slamp** [comment]
I created a draft version using the following assumption. 

Instance name: hachyderm.io
Instance Community: curated network of respectful professionals in the tech industry around the globe
Instance Topic: mainly linked to Tech Industry, Economics, OSINT, News, Rust, Linux, Aurae, Kubernetes, Go, C, Infrastructure, Security, LGTBQIA+, Pets, Hobbies
Instance E-Mail: admin@hachyderm.io
Instance Administrative Location: Seattle, Washington, USA
Instance Donation URL: https://ko-fi.com/krisnovalive
Instance Donation Provider: Ko-Fi Labs Limited, UK Limited company registered in England and Wales under company number 11087704
Instance Donation Provider URL: https://ko-fi.com
Instance Hosting Provider: Hetzner, Germany
Instance Hosting Provider URL: https://hetzner.de
**Instance E-Mail Notifications Provider: Hetzner, Germany
Instance E-Mail Notifications Provider URL: https://hetzner.de
Instance E-Mail Inbox Provider: Inbox_Provider, Provider_City
Instance E-Mail Inbox Provider URL: https://inbox-provider.com**

I have a doubt for the last 4 entries:
Is hachyderm mastodon instance using Hetzner.de as mail provider ?
What's the E-Mail provider for admin@hachyderm.io

(The idea is to modify only those values to be able to generate a new version of the GDPR Privacy Policy when the generator is updated)

**Comment by slamp** [comment]
I need to review the infrastructure to identify where PII data are processed.
(Linode but also Digital Ocean for the S3 storage)

**Comment by dmah42** [comment]
this is a great start for sorting out a policy we can post publicly.  the rest of the gdpr story is something we will take care of.

thanks.
