### ISSUE TITLE
Profiles within the bio are not clickable 

### ISSUE THREAD

**Issue by itrich** [hachyderm/community#9]
Contrary to my former instance, the referenced profile in my bio is not clickable. Is this behaviour intended?

**Comment by jakesmolka** [comment]
Please add more info 🙂 
For reference: https://hachyderm.io/web/@EduardItrich

According to https://instances.social/list/old hachyderm and

**Comment by itrich** [comment]
> Please add more info slightly_smiling_face 

Sorry, of course! 😇

> For reference: https://hachyderm.io/web/@EduardItrich And assuming the former instance is chaos.social

My former instance was <digitalcourage.social>, see <https://digitalcourage.social/@EduardItrich>. See the attached screenshot as reference
![image](https://user-images.githubusercontent.com/29982899/200513935-ae589165-eeea-4ac0-9cfa-1c75aeed5fcd.png)

Contrary to my current bio on <hachyderm.io>
![image](https://user-images.githubusercontent.com/29982899/200514236-8d591ed0-5a8f-47be-9bbf-674370adea3f.png)

> 
> According to https://instances.social/list/old hachyderm and chaos.social are running on the same version. AFAIK hachyderm has no custom tweaks, patches etc.
