### ISSUE TITLE
Emoji request: elixir

### ISSUE THREAD

**Issue by eToThePiIPower** [hachyderm/community#93]
Elixir is a functional, highly-concurrent programming language with a Ruby-inspired syntax for the Erlang BEAM. Several other instances (https://fosstodon.org, https://floss.social) already have the emoji available (as `:elixir:`):

https://cdn.fosstodon.org/custom_emojis/images/000/088/885/original/28532a9e9dd84bbd.png

**Comment by quintessence** [comment]
Done ^.^
