### ISSUE TITLE
I was verified ✅😎 but now I am not 😔

### ISSUE THREAD

**Issue by joshuamkite** [hachyderm/community#95]
I'm new to Mastodon and trying to get my profile to show as verified based on my website. I followed the guide at https://opensource.com/article/22/11/verified-mastodon-website and got 2 green ticks immediately ✅✅😎 I then tried removing one link to avoid having 2 labels for same link. I lost green ticks and now I can't get this back for my website link in my profile 😔. Website is deployed via Hugo to s3/CloudFront and kept in source control so I have high confidence that that hasn't changed since I did see verification. I've tried playing with link syntax- including/excluding `http://`/`https://`/`www.` etc Anything else I can do?

**Comment by wlonkly** [comment]
I honestly don't know if this matters, but it couldn't hurt to try...

I noticed that your `rel="me"` `<a>` tag is outside your website `<body>`:

```
</body>
<a rel="me" href="https://hachyderm.io/@joshuamkite">Mastodon</a>
</html>
```

Try putting it in the body and see if verification succeeds? If the verification check traverses the DOM it wouldn't find that `<a>`.

**Comment by untitaker** [comment]
if your website still has the rel=me tag, just edit your profile again (in any way) to make the server re-verify. if you don't do that the green checkmark will appear _eventually_ (idk, a couple hours or so)

**Comment by quintessence** [comment]
This one has me a bit stumped for why it isn't working. Something to try perhaps is using `<link>` instead of `<a>` and putting it in the page headers?

https://github.com/hachyderm/community/blob/main/verification.md

**Comment by joshuamkite** [comment]
Thanks all, this now seems to be fixed with a combination of the above advice.  I've had a busy couple of days so couldn't action/respond before now. What I did:

### Move verification link to body of webpage
(suggested by @wlonkly )
 
For me this depended on **not** displaying the link visibly (see below) because I am using Hugo which builds my website from 'partials' and markdown rather than individually created web pages  and I didn't want a site-wide banner link. 

### Change verification link 
(suggested by  @quintessence )

from 
`<a rel="me" href="https://hachyderm.io/@username">Hachyderm</a>`
to 
`<link rel="me" href="https://hachyderm.io/@username">`

to avoid using a visible link as referenced at https://github.com/hachyderm/community/blob/main/verification.md 

### Edit verification link on hachyderm.io
(suggested by @untitaker )

In my case I removed the trailing backslash from the link in my hachyderm profile and the change caused the server to re-verify. In my case this was immediate

Thanks Everyone!
